### ISSUE TITLE
avoid double issues in community

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#100]
check in send of publication if issue was already send before sending

**Comment by SadiaRasheed** [comment]
Tentative estimations for this task are  3 to 4 days.

**Comment by SadiaRasheed** [comment]
- After analyzing this issue I have thought of the following strategy
- Need to check if the publication has been already sent to the selected community or not in the send button functionality. 
- If yeah , it will show the message that the publication has been already sent to the selected community 
- If no, the publication will be sent to the selected community
- After the publication is sent, success message will appear

**Comment by SadiaRasheed** [comment]
Sub Task 1 : At nation level, need to update the publication database so that community names can be saved

**Comment by SadiaRasheed** [comment]
Sub Task 2: Applied checks if the publication has already been sent to the specific community or not
Sub Task 3: If publication has not been sent then send the publication and update the database for that community so that it can be checked that publication has been sent to this community
SubTask 4: If publication has already been sent then just display a message that " This publication has already been sent to the selected community"

**Comment by SadiaRasheed** [comment]
Github commit issue
https://github.com/open-learning-exchange/BeLL-Apps/commit/3c2f0eb87c93ba49ee3907dce8d828c5b2b422f6

**Comment by SadiaRasheed** [comment]
Important notes: 
    - This feature will work from this release and onwards. 
   - Previous publication can not be sent using this feature 
  -  You have to make new publication and then you can add resources and send to the community

**Comment by SadiaRasheed** [comment]
github commit link:
https://github.com/open-learning-exchange/BeLL-Apps/commit/1eec1f4a6c5d152f4438d822df0a0ad0ffa88e2e

**Comment by SadiaRasheed** [comment]
There was random behavior while updating of publication document.
Internal Server error (500) problem
It is solved now
https://github.com/open-learning-exchange/BeLL-Apps/commit/4e9c5c1273c8a0bf1536021126eafc4ec66e8643

**Comment by dogi** [comment]
Now (version 0.11.76) when I on nation retry to publish the same issue following happens ...

![76e1](https://cloud.githubusercontent.com/assets/13684059/11267321/ae690f36-8e78-11e5-99e7-3883bf20874b.png)

**Comment by dogi** [comment]
did further tests it happens only to older publications

since for now all nations are managed by us and even UI crashes/stops the result is the same no double issues published
