### ISSUE TITLE
nation: on publication page find a way to show "send to" communities

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#101]
that and maybe also if hey had success in downloading it

**Comment by SadiaRasheed** [comment]
So you want us to show the community name where the publication has been sent.
Tentative estimations for this task are 3 or 4 days excluding this part "and maybe also if they had success in downloading it" .

**Comment by jstearnsw** [comment]
Please describe how you would show this solution - how you would display all of the communities connected to the nation with an indication of which community the publication was sent to

**Comment by SadiaRasheed** [comment]
- Get the names of the communities to which publication has already been sent 
 -Read from database and display the community names to which publication has already been sent on the publication page

**Comment by MWakas** [comment]
This issue has been resolved.Here is the screen shot of solution:

and here you can find changes in the code on GitHub:
https://github.com/open-learning-exchange/BeLL-Apps/commit/672a797e55c1430af063cdb3f701930a67c860a3
