### ISSUE TITLE
Update the Logo

### ISSUE THREAD

**Issue by bsocial** [open-learning-exchange/BeLL-Apps#1010]
We need to update the default OLE logo that is used-in the user interface. 

![ole-logo](https://user-images.githubusercontent.com/4063398/29883027-e99f06aa-8d7c-11e7-978f-3370962baae7.png)

Note the old logo in this example:

![logo-placement-example](https://user-images.githubusercontent.com/4063398/29883768-3f547254-8d7f-11e7-9acc-8c4546469a06.png)

**Comment by artrixscode** [comment]
hello @dogi what format and size options do you want the logos?

**Comment by artrixscode** [comment]
Hello @dogi i have got the new logo in ai, png, svg and pdf also have the favicons as well. Please check this link to download https://we.tl/83F2oJHYuo .

**Comment by dogi** [comment]
https://files.gitter.im/open-learning-exchange/UX/hYHx/OLE_Logo.png

**Comment by dogi** [comment]
@artrixscode please next time you leave the picture or picturelink here ;)
so that developer do not have to search it ...

> https://we.tl/83F2oJHYuo /google drive is not a good way to do that ... people still need to search the right one from many pictures thats why drag and drop the picture in here is best one ...

![ole_logo](https://user-images.githubusercontent.com/13684059/31168658-18a9fc54-a8c4-11e7-8cba-38a008735776.png)
