### ISSUE TITLE
AutoPublication : old database conflict

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#1016]

**Comment by dogi** [comment]
@/all where are all the nice picture I made ...

**Comment by Pr0chin** [comment]
ok sure @dogi  we ll have some snapshot .

**Comment by Rupesh87** [comment]
There are two issues which happen when dealing with old `publication` data:
- [x] main publication overview page crashes
![17-1](https://user-images.githubusercontent.com/18145146/30044291-f5e2ff0e-921b-11e7-872f-a1ce1c6858f6.png) without showing the publication issues - when fix also make sure the button gets shown when `autopublication = undefined` -> `enable auto publication`

- [x] publication issues edit pages shows the wrong button
![17-2](https://user-images.githubusercontent.com/18145146/30044292-f5f6d646-921b-11e7-93c0-40cfa0bb02c3.png) it should be `enable auto publication`
