### ISSUE TITLE
Create MUI supporting Urdu

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#103]
As an initial step, it is suggested to render bell-Apps in Urdu language.

--Collected the data required to create a one-on-one mapping between phrases on DashBoard and their corresponding exact matches in Urdu.

**Comment by SabaBaig** [comment]
As per the strategy discussed in https://docs.google.com/document/d/13XJ3QEe0iAEKjmfK2XAkRq6bWh0s_u-Jqtb7lFAwIYo/edit?usp=sharing
Created a map for Urdu Language
![languages_doc_urdu](https://cloud.githubusercontent.com/assets/13994879/10044938/febde19c-6217-11e5-99c9-8618eb2e8c29.PNG)
Then, finally tokenized all the terms in HTML and also worked on the elements being appended from server-side
So, as an initial effort came up with something as follows 
![poc_mui_ole_2](https://cloud.githubusercontent.com/assets/13994879/10044957/27068064-6218-11e5-9a8b-ae2d4eb8383e.PNG)

**Comment by SabaBaig** [comment]
--Gathered dataset and then added them in the map, in the most appropriate format. (with the help of Google Translate)
--Worked on rendering date in Urdu, on dashboard.
--Worked on enabling current language to be selected from the available languages on the configurations page. (Realted to Issue#104)
--Still working on using different CSS for each Language. (Styling for urdu is also in progress)
![p4](https://cloud.githubusercontent.com/assets/13994879/10136013/8245a6fc-660b-11e5-94df-d438b69d8e95.PNG)
![poc_mui_ole_3](https://cloud.githubusercontent.com/assets/13994879/10136018/8a34a62e-660b-11e5-96f7-6c8b3ddde327.PNG)

**Comment by SabaBaig** [comment]
--Created separate styling sheet for both Urdu and English Language.
--Deciding at run-time which css to load, as per the current Language set in Configurations page.
--Made the Language to be selected from the drop-down in Set Configurations page of community.
--Formatted all the elements on page, as per the rules of Urdu Language.
--Working on a dashboard of Nation, that requires few changes.
![poc_mui_4](https://cloud.githubusercontent.com/assets/13994879/10163109/ee2cf730-66c9-11e5-9a79-191fb257df26.PNG)

**Comment by SabaBaig** [comment]
Issue#103 (Creating MUI supporting Urdu)
--Adjusted the suggested Allignment on page for Urdu Language, while preserving the formatting for other languages.
--Completed and tested the code for multi-lingual interface on Dashboard at nation-level as well.
--Separate out the document for each language and adjusted the code accordingly.
--Re-structured the map, as per need.
--Removed the redundant piece of work.

**Comment by SabaBaig** [comment]
--Gathered the data set required for Login and Library Page and then updated the map.
-- Completed the Login Page.
![login_page](https://cloud.githubusercontent.com/assets/13994879/10392657/7812a172-6ea2-11e5-92a1-b94000c0147f.PNG)

--Library Page is still in progress.
![library_page](https://cloud.githubusercontent.com/assets/13994879/10392689/e4474c62-6ea2-11e5-9d21-aca7a6dd7cfb.PNG)

**Comment by SabaBaig** [comment]
--Library page is modified now, but still some changes are yet to do.
![resource_page](https://cloud.githubusercontent.com/assets/13994879/10453665/a19e299e-71c7-11e5-904a-3ddab6bd513b.PNG)

**Comment by SabaBaig** [comment]
git hub commit link
https://github.com/open-learning-exchange/BeLL-Apps/commit/b921c102490353467e083d0e9298462d6d3075fc

**Comment by SabaBaig** [comment]
Courses page is also supporting Urdu Language now, for its live-working you can refer to saba.nbs.ole.org
The github commit link for this is,
https://github.com/open-learning-exchange/BeLL-Apps/commit/729222ab8f542a8ff55018a1a317de21719a02c3

**Comment by SabaBaig** [comment]
Here are few important questions regarding the MUI support for Urdu.
   1)  What is the minimum and maximum device resolution that you prefer this web-application to support?
    2)  Do you want Responsive/Liquid UI?

**Comment by SadiaRasheed** [comment]
We had a meeting with our design experts here at NBS and here is the recap

     - Center-alignment of Bell-Apps
        -- Need to center-align the Bell-Apps and which is User friendly. Please see the links below for other MUI sites as they all have centrally aligned UI
            --- http://www.bbc.co.uk/learningenglish/persian/
            --- http://www.urduvoa.com/
       - Zoom-In Zoom-Out will cause scrolling and UI elements will be distorted
       we can work on this in other iteration
       - Have tested Bell-Apps on mini tablets and its working fine
       -  Direction (right, left) change ( after selecting language ) is not a solution as it should be centrally aligned.
       - Tested it on 1024 (minimum resolution for devices ) resolution and it seems fine
      -  Content of the containers should be right aligned and the page should be centrally aligned

**Comment by SadiaRasheed** [comment]
https://docs.google.com/document/d/1wNKrOPenCeQjnDjl8kbesZc0Nf-vBLuPDREQ5e6Jv-c/edit

**Comment by SabaBaig** [comment]
Arabic translation for following words is required,
https://docs.google.com/document/d/1wNKrOPenCeQjnDjl8kbesZc0Nf-vBLuPDREQ5e6Jv-c/edit

**Comment by SabaBaig** [comment]
You can check the working of MUI in English, Urdu and Arabic on (Login, Dashboard, e-Readers, Library, Courses). Please run the file install_windows.js  to have documents of Languages into your newly created community.
Command: 
(For example)
node install_windows http://[IdOfYourLocalDb] : [passwordOfYourLocalDb] @[URLofCommuntity]
andto update databases on  nation, please run the file push_nation_design_Docs.js located in update_nation folder...
Same goes for nation
node push_nation_design_docs  http://[IdOfYourDb] : [passwordOfYourDb] @[URLofNation]
You can find the latest, of these files in the following commit
https://github.com/open-learning-exchange/BeLL-Apps/commit/23529f8d4106f15b4ffcfdbb99bca786b32efb88

**Comment by SabaBaig** [comment]
-There is a suggestion from our side, that the messages displayed in the form of alerts to notify user about the current status of their task should also be in the language selected by the user, it is not yet part of this application. But there is a suggestion to compensate this as well, if desired.
Following is a demo
![alert](https://cloud.githubusercontent.com/assets/13994879/10752610/ae5d88ce-7cac-11e5-90a7-489fee84984d.PNG)

**Comment by SabaBaig** [comment]
Members page is now providing Multi-Lingual support now. Here is, how it looks,
![members](https://cloud.githubusercontent.com/assets/13994879/11590403/d1ae5934-9ab1-11e5-8918-68963d9fdcc1.PNG)
you can find this, with all relevant changes on the following commit link,
https://github.com/open-learning-exchange/BeLL-Apps/commit/3ba6c346e497c3d8b5f9c7699ef0026734fba706

**Comment by SabaBaig** [comment]
Reports and Feedback pages along-with all updated languages documents can be found on following Github commit links,
https://github.com/open-learning-exchange/BeLL-Apps/commit/d341f6b6f85e2072974a4ff8c065bfaa73288331
https://github.com/open-learning-exchange/BeLL-Apps/commit/debe4eb618c884bd0f0ce4c2a24377899b675ffb
https://github.com/open-learning-exchange/BeLL-Apps/commit/dd375d81b87b05513e0e228b3945fe257d09a609

------------------
Reports Page
------------------

![reports](https://cloud.githubusercontent.com/assets/13994879/11709582/862feab2-9f3a-11e5-8897-8c12e87e81eb.PNG)

--------------------
Feedback Page
--------------------

![feedback](https://cloud.githubusercontent.com/assets/13994879/11709596/98f091a6-9f3a-11e5-8425-370a9b27fc30.PNG)

**Comment by SabaBaig** [comment]
Follwoing pages are provided MUI now, which are available on given commit links
--Add New Collection Page,
https://github.com/open-learning-exchange/BeLL-Apps/commit/4717ef545aec0248c54cc77b57ef9389346626b1
--Add Resource Page
https://github.com/open-learning-exchange/BeLL-Apps/commit/784a91073b9729470516e8c3ab5d41914d151c58
--Request Resourcce/Course/Meetup page
https://github.com/open-learning-exchange/BeLL-Apps/commit/15c0ac8f28a64d1646a6cda8bcdc4e1836dc09c2

**Comment by SabaBaig** [comment]
Search page is now providing MUI and is available on the following commit link,
https://github.com/open-learning-exchange/BeLL-Apps/commit/9f65f71338804ba82ba467127565f404ba31f884

**Comment by SabaBaig** [comment]
Following advancement in this issue can be found on provided github commit links,
- Issue#103(Collections page on Library is in MUI)
https://github.com/open-learning-exchange/BeLL-Apps/commit/2d6e2a5be4e6a675378cc943d4262a9e3b8905b4
- Issue#103(Merge Collection is now in MUI)
https://github.com/open-learning-exchange/BeLL-Apps/commit/27f8a1b4c81f4c9c614c4839248d6a2bd5705db3
- Issue#103(Resource Feedback is in MUI)
https://github.com/open-learning-exchange/BeLL-Apps/commit/239f174508e981be67224099bab4a6f85dc2ea83
- Issue#103(Updated Languages docs for Library Module)
https://github.com/open-learning-exchange/BeLL-Apps/commit/900e4a3e2c4775746bc664f500af0372bce603e2
- Issue#103(Add Feedback for Resource in MUI)
https://github.com/open-learning-exchange/BeLL-Apps/commit/67467b5033556ba7b31877f0305a0ec6bb67b4ca
- Issue#103(Incorrect Label on Feedback page is resolved)
https://github.com/open-learning-exchange/BeLL-Apps/commit/8971a05efe010860431b16d3c0de07ab1dc293bb

**Comment by SabaBaig** [comment]
Edit Collection page is now in MUI and can be found on following Github Commit Link,
https://github.com/open-learning-exchange/BeLL-Apps/commit/653863c10beef85ed86f2a2b83fe9e652e4b1611

**Comment by SabaBaig** [comment]
Add Course page is provided in MUI along-with updated language Documents,
https://github.com/open-learning-exchange/BeLL-Apps/commit/a5044a69802cac73fb283488d7a08e5eee38f695

**Comment by SabaBaig** [comment]
--Issue#103(Manage Course page in MUI)
https://github.com/open-learning-exchange/BeLL-Apps/commit/938342990984dc7070aebd856030f2f591fe9d56
--Issue#103(Add Course Step Form in MUI)
  https://github.com/open-learning-exchange/BeLL-Apps/commit/5303bb70e116ad7482f57f316d3645a0ba12202b
--Issue#103(Update Languages Docs and removed margin issue on Add Step)
  https://github.com/open-learning-exchange/BeLL-Apps/commit/6e4ca00f5178ddb3e9c3690c10f1b223a4223080

**Comment by SabaBaig** [comment]
Following advancement is made on MUI in BeLL-Apps, [[under Courses Module]]
--Added Custom Validator Message in Add Course Step
https://github.com/open-learning-exchange/BeLL-Apps/commit/72af17062ba1b1549569137056dcef4f1eee52be
--LevelRow view is now in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/a493df4379c9e526bf981e5b3c4a084268ca76ce
--Add Resource/Search page is now in MUI) 
https://github.com/open-learning-exchange/BeLL-Apps/commit/b4f6787b02d867a432480b3c6c6e451ad1c05ed9
--Courses/CourseStep/AddResource/SearchResults in MUI)
https://github.com/open-learning-exchange/BeLL-Apps/commit/0af4008fd1fe84b8ae5518fb281d9c0fc758487f
--Updated Labels on LevelView File)
https://github.com/open-learning-exchange/BeLL-Apps/commit/6bba1b1b01bd3da7e709901bb7d313b3545fa7d3
--Corrected styling for Edit/Add Course Step page)Issue#103(Create Quiz page in MUI)
https://github.com/open-learning-exchange/BeLL-Apps/commit/1d09e58f9dd0e99a4cff34c738eae6b6cc041e7c
--Create Quiz page in MUI)
https://github.com/open-learning-exchange/BeLL-Apps/commit/45d0ea90bfef0d91cb331f7a5d43d5f283784377
--Updated Languages docs for Arabic, Urdu and English) 
https://github.com/open-learning-exchange/BeLL-Apps/commit/1cb388d07107d5494a482a0b39864718a26dafe6

**Comment by SabaBaig** [comment]
-Manage Course/ Progress in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/1cc42c55e52c7ce24f5201244e48177136a8e7ec
-Invite Members for Course partially in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/b4a7f33f25d2ac3cbc3d788e304e523b63ea516e
-Updated languages docs for Urdu, Arabic and English
https://github.com/open-learning-exchange/BeLL-Apps/commit/dad45d8e06b08861f3d2b0aee960b61525140e32

**Comment by SabaBaig** [comment]
--Invite Members for Course completed
https://github.com/open-learning-exchange/BeLL-Apps/commit/14dff9ac89a59a3e5762f09439e30c8af01bec68
   --Manage Course/Members page in MUI with updated language docs
https://github.com/open-learning-exchange/BeLL-Apps/commit/c13c527efd6802455d91dd6b83af86c3aea0c28e
   --Corrected the eventHandling on course/Members page
https://github.com/open-learning-exchange/BeLL-Apps/commit/1f4d0ba10a03ffe1448189182f61299c5fcbf23a
   --Send Email to Members of Course in MUI with updated languages docs.
https://github.com/open-learning-exchange/BeLL-Apps/commit/eb2c7e02e6feba0fcd0ed412d005b8f525bed3a5

**Comment by SabaBaig** [comment]
--Resolved the workflow of InviteMembers for all languages
https://github.com/open-learning-exchange/BeLL-Apps/commit/560b5a791a292f87140c8d2fdd9d82bb6ae7ecc3
--CourseInfo in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/0e04028b7496d49653d20399255c6196dc00e00f
--Resolved onChange event for Level and Member does not fire up
https://github.com/open-learning-exchange/BeLL-Apps/commit/013e4d134b9155b401ecfee2efbd0c92b9c5cb67
--Course/Resign in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/0f1364b4d8d133f8863989608232acc243697525
--selectAllMembers corrected for Courses
https://github.com/open-learning-exchange/BeLL-Apps/commit/da66a9191bf683aacef5f5c4e58cb61f596174b1

**Comment by SabaBaig** [comment]
--UserCourse Details page in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/a018a2b2152d762a013513707308efb61554e4b0

--UserCourse Details/Feedback in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/0ee4a5592abd501585cb1907eeb4f90ad203dfb9

--Take Quiz page in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/df53a5ccf641680ccd2a3b81ed9c55dcca32615b

--Take Quiz Result page in MUI with update language docs)
https://github.com/open-learning-exchange/BeLL-Apps/commit/d1c0cb33dce5926f8cd7e53d348ee4806f034e06

--Resolved : Undefined OutComes in UserCourse details
https://github.com/open-learning-exchange/BeLL-Apps/commit/7515fe0750c18c3d5d9b444b809e6cc3138f207d

**Comment by SabaBaig** [comment]
--Lables on COurse/Report corrected on graphs)
https://github.com/open-learning-exchange/BeLL-Apps/commit/cdae622fecddad7f04457981aa874d33bde11c8b

--View Course Details page in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/6e1afb2051e8f755396202818168ea91b887f326

--Courses/barchart in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/71919159796e4a9cf07b581db93fccc75b476e17

--Courses/Admission in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/affafbee5b5a03b89b7671a533082a97fdba33cb

**Comment by SabaBaig** [comment]
--Corrected label on Course/Details page
https://github.com/open-learning-exchange/BeLL-Apps/commit/3df9801fe0c416325a18faffcf666f4ffabe391e

**Comment by SabaBaig** [comment]
Allignment corrected for Text on mail for RequestAdmin
https://github.com/open-learning-exchange/BeLL-Apps/commit/0380b19940bb0c2ef048cbbf2782d1691ef0834d

**Comment by SabaBaig** [comment]
- Add/Edit MeetUp and InviteMember for MeetUp in MUI)
https://github.com/open-learning-exchange/BeLL-Apps/commit/f4c013280fb6ff16650cce0092bd47d470327cfe
- MeetUp details page in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/06c08511d662b4d6cea2f0c42cc8d9c0112b92ce
- MeetUp delete Prompt added alongwith MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/0b6c555458e59eaf45be312c8703ac744d1400d4
- UserMeetUp details from dashboard in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/b19691501cdb8abd86ec7b96fd45b36d5f048ba8
- Prompt added on memberDelete with MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/2d87d81c46f8458bc29e75f42815b016831760a1
- Add Report in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/353e0033524926de69fe7e5b13922640d719b799
-

**Comment by SabaBaig** [comment]
- LogReports page in MUI)
https://github.com/open-learning-exchange/BeLL-Apps/commit/31521da7a9d700fc7f784151cf6d41c219363aa4
- N/A and NaN replaced on Reports
https://github.com/open-learning-exchange/BeLL-Apps/commit/2b33909e5b36656cf7779468b2fae8b4d2630283
- Design of Activity Reports page is completed
https://github.com/open-learning-exchange/BeLL-Apps/commit/1b5a08bcc2834876bf5f52b6c13959b23b149c91
- Trend Activity Reports Completed on Community
https://github.com/open-learning-exchange/BeLL-Apps/commit/20acb8ea4c5506b60ae6d1826165f3a245fb437a
- Resource Detail page on Shelf in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/7419193995e0e21c4f9ff52d408d148796a53d52

**Comment by SabaBaig** [comment]
- Comment box on Reports in MUI
https://github.com/open-learning-exchange/BeLL-Apps/commit/cb46e2f6df4ebdb20f2a277f759188895ffd7a4a

**Comment by SabaBaig** [comment]
- Make AvailableLanguages dropdown dynamic on Login Page
https://github.com/open-learning-exchange/BeLL-Apps/commit/abe32c7bc634decd8728da5fadfd397d0d3fe52c
 - corrected dropdown for Configurations
https://github.com/open-learning-exchange/BeLL-Apps/commit/b6e9c895e8d8f9d72606f22b4199fe888c133290
- Code Dependency Removed for adding new language
https://github.com/open-learning-exchange/BeLL-Apps/commit/07a5d14f8adb91be4496f8332c1789219eaa2a77

**Comment by SabaBaig** [comment]
-  Delete existing availableLanguages attributes from Configurations on update
https://github.com/open-learning-exchange/BeLL-Apps/commit/1c7c626850bdd75deb4fc371e8616b1f9b8151c5
 - Correction in dropdown of Languages on Configurations page
https://github.com/open-learning-exchange/BeLL-Apps/commit/55955a37d094c2fa34a5b2a095fe587286199dbe

**Comment by SabaBaig** [comment]
@dogi I have a question here, if we are fetching the list of available languages in BeLL-Apps each time from languages database instead of configurations so that they can be displayed on all dropdowns that offer user to select language, then there are two dropdowns that need our attention the most.

 - **Select Language dropdown on Add Resource page** 
According to our current logic, it will display the user only those languages which are present in databse, but if a user wants to upload a resource in any other language say French whereas we do not have any corresponding document to French in our database then he will not be able to do so. 

 - **Select Language dropdown on Search page**
Similarly, all those resources which are in other languages (whose corresponding languages documents are not in database) would not be searched by their specific  language. 

So, in these cases, we are left with 2 solutions as per current observations
1) Hard-Code the all possible languages (in model of Resource only) a user can choose for these two dropdowns.
2) Let the user be displayed only those languages which are available in our database and we assume that from now onwards no user will be able enough to add a resource in a language which is not in our database.

Please share your thoughts with us, so that we may proceed accordingly on this issue.

**Comment by SabaBaig** [comment]
- Languages dropdown corrected for Add/Edit Resource)
https://github.com/open-learning-exchange/BeLL-Apps/commit/659ed3387b6c1935c13a385ec7ab66c157332b83

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/eea962d6acc5f83716ad2b7ee66642fcd52d8da2
https://github.com/open-learning-exchange/BeLL-Apps/commit/30fd6d1ca9ad3765ecb2a3b37422634a20d9a473
https://github.com/open-learning-exchange/BeLL-Apps/commit/061e340c078624db5f4b83a7978126839bb69b89
https://github.com/open-learning-exchange/BeLL-Apps/commit/83da2e23fd85ee00fb97224b98491b1ab62f59e1

**Comment by SabaBaig** [comment]
- [Resolved MUI issues on Members and Configuration page] (https://github.com/open-le arning-exchange/BeLL-Apps/commit/7aeea0d29b1e27922b48937e451e48634e4cc0ab) 

- [AddEvent page supporting MUI)](https://github.com/open-learning-exchange/BeLL-Apps/commit/fc164dc9f44abe1d4be6204b116562b12c9937e8)

- [Edit/View Event supporting MUI)](https://github.com/open-learning-exchange/BeLL-Apps/commit/f2e5b217ac49b2e2b54ef29075dfe35e9f70a274)

- [AddOrUpdate Welcome Video page in MUI](https://github.com/open-learning-exchange/BeLL-Apps/commit/a38feeb22e91fa53718a0b8c73719c4aae9ac101)

**Comment by umarWaris** [comment]
- [updated languages files](https://github.com/open-learning-exchange/BeLL-Apps/commit/276ac78c9987a878816b101ca74de2cbddfd3422)
- [Survey page corrected](https://github.com/open-learning-exchange/BeLL-Apps/commit/feaebe35a90440bea37acf96ab2cfced6dfe6725)
- [sync with nation page](https://github.com/open-learning-exchange/BeLL-Apps/commit/0382fe860597aac9dd6211a5d8d1f9d49be63b32)
- [Configurations page in MUI](https://github.com/open-learning-exchange/BeLL-Apps/commit/061e340c078624db5f4b83a7978126839bb69b89)
- [Corrected label on configurations file](https://github.com/open-learning-exchange/BeLL-Apps/commit/2e73ab61f8d8e1a36f62e91df6d33c53706bbb14)
