### ISSUE TITLE
Current Language is not being saved

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#104]
When we change the current language in the configuration form and save it, the language is not updated in the configurations database and older language appears there as shown in screenshots 

![issue 104](https://cloud.githubusercontent.com/assets/10362799/10039437/6d2f5818-61eb-11e5-9bd4-56db9474fac5.PNG)
![issue 104 b](https://cloud.githubusercontent.com/assets/10362799/10039441/7435e618-61eb-11e5-8f08-e5d465d5a68d.PNG)
![issue 104 c](https://cloud.githubusercontent.com/assets/10362799/10039451/8addf6bc-61eb-11e5-9936-b039236041dd.png)

**Comment by dogi** [comment]
Wonder if it is also possible to merge both form fields into one.
The Title could be simple "Language" and you would just select select a language out of a drop down menu filled with all items of "available language"
default preselection would be "English" (first time)
and after that "current language" would be preselected

**Comment by MWakas** [comment]
This task has been completed and here you can find changes in the code on github:
https://github.com/open-learning-exchange/BeLL-Apps/commit/72a12815fb216af5d3199d81543d0e4b3b573146
https://github.com/open-learning-exchange/BeLL-Apps/commit/b964471e4e7b527f822857bca49e846ff4d734d2
