### ISSUE TITLE
Kilifi Community needs manual intervention

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#105]
it seem like something in the report functionality is not working (locally and with that also on the nation) ... for example 40 new members are not showing up in September

**Comment by dogi** [comment]
Contact info will follow in an email

**Comment by SadiaRasheed** [comment]
Please send contact info so that I can contact with them

**Comment by SadiaRasheed** [comment]
I have sent an email to Kalifi for an online Troubleshooting session

**Comment by dogi** [comment]
please try again to get in contact with them ;)

**Comment by SadiaRasheed** [comment]
Okay, Writing them email
