### ISSUE TITLE
Narok Community needs manual intervention

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#106]
looks like there we have the same problem as we encountered already 2 months ago with some of our Dadaab Communities ... member sync is throwing an error

**Comment by dogi** [comment]
Contact info will follow in an email

**Comment by SadiaRasheed** [comment]
I have sent an email to Narok for an online Troubleshooting session

**Comment by dogi** [comment]
please try again to get in contact with them

**Comment by SadiaRasheed** [comment]
Okay. writing them email

**Comment by SadiaRasheed** [comment]
Narok Troubleshooting Meeting Details with Nase Kelel 
1) I found that they have following problems
      - Magdalene from Narok Bell showed me the problem with the graphs as the graphs are not showing correct figures and numbers
      - When reports are synced with Kenya Bell the results are not showing up at Kenya nation
     - The latest publications are not showing up at Narok ( #113)
     - I started with publication problem 
     - Debugged the code at narok and also checked the databases and views at kenya bell
Compared the publication and publicationDistribution databases at kenya bell
     - Filtered out the publications for Narok community
    - Filtered out the publicationDistribution databases for Narok community
    - Checked the publication database at Narok community
    - New publication count shows up at dashboard page but on publications page they are not showing up ( not available for syncing )
    - Found some views and collection and now I am debugging at Narok
   - Narok is getting all the publications from nation but there is something during rendering process. I will continue my debugging at Narok side today

**Comment by SadiaRasheed** [comment]
I will have another session with Narok today
