### ISSUE TITLE
Text fields are spreading on whole page at Nation's Configurations

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#107]

**Comment by SabaBaig** [comment]
![041da24db03de1e612c27d1b89b10ce1877adcfd7692904773 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/13994879/10193458/acc1c9dc-679c-11e5-9b8b-03425d8efb6c.jpg)

**Comment by SabaBaig** [comment]
![config](https://cloud.githubusercontent.com/assets/13994879/10193498/ee923e6e-679c-11e5-9b3f-e8e9bfceaa0a.PNG)

**Comment by dogi** [comment]
good catch ;)
-> it looks like it only happens in Nation's

**Comment by MWakas** [comment]
Yes and I am gonna fix that,It only will take about half an hour.

**Comment by MWakas** [comment]
It is fixed and here is the link to find changes on github:
https://github.com/open-learning-exchange/BeLL-Apps/commit/c91c4cd8d882168dd48ef4f2289f1b44145a995c
