### ISSUE TITLE
Different results show when adding new collection in community versus nation

### ISSUE THREAD

**Issue by jstearnsw** [open-learning-exchange/BeLL-Apps#108]
aka - name of collection does not show for resource on library page

**Comment by jstearnsw** [comment]
This is related to https://github.com/open-learning-exchange/BeLL-Apps/issues/41

I tried running the same create collection/create resource/delete collection/check resource test that I did for #41 (link above):
- I created a new collection called test
- I created a new resource called a
- I added resource 'a' to collection 'test'
- I went to the main library page to confirm that collection 'test' was added to resource 'a' -- this is where I think I found a bug: 'test' is not displayed after Collection on the main library page (see screenshot):

**Comment by SadiaRasheed** [comment]
We only need to reload the page after the collection is saved so that newly created collection can be synced in both pouch and couch db.  This will resolve the issue.

**Comment by SabaBaig** [comment]
After analyzing the scenario, it is observed that there is nothing to do with databases, since its consistent with current situation exactly. All we need to do, is to reload our page to render the most recent changes correctly. Tentative estimate for this is 30 minutes.

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/bdc8ea06819632bed4411e0f94c4902010983f90 done

**Comment by jstearnsw** [comment]
We tested this again in the new local community and new nation.  We can see that the collection is hidden from checking CouchDB:
![collection utils for local community new](https://cloud.githubusercontent.com/assets/11721132/10258094/c49c7c3a-6929-11e5-8cab-3f7c0d9a9282.JPG)
![collection utils for nation new](https://cloud.githubusercontent.com/assets/11721132/10258095/c49c8eaa-6929-11e5-9bf0-562aec7821ac.JPG)

Here is the screenshot from the nation and community showing the collection still listed for the resource even after refreshing and logging out/back in:
![collection still showing local community](https://cloud.githubusercontent.com/assets/11721132/10258104/da1a0de8-6929-11e5-9e6c-867289e80e4e.JPG)
![collection still showing new nation](https://cloud.githubusercontent.com/assets/11721132/10258103/da18d676-6929-11e5-8077-deb379559556.JPG)

**Comment by jstearnsw** [comment]
I decided to look a bit further and found that if I opened the view details for the resource and hit save again, when I am returned to the main library page, the collection is finally no longer listed.  This works on both community and nation.

**Comment by SabaBaig** [comment]
I would like to know the version number of your nation both previous and current.

**Comment by dogi** [comment]
@SabaBaig we tested on the actual build of BellApps  0.11.64 - in this case here both nation and community was fresh installed

**Comment by SadiaRasheed** [comment]
github commit link
https://github.com/open-learning-exchange/BeLL-Apps/commit/3765ae4bc03092414152ee39dd6cf55ee35b62fb
