### ISSUE TITLE
branch library

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#109]
With the [Branch Library](https://github.com/dogi/ole--rpi-bells/blob/master/branch/branch-autorunonce.sh) script, it is possible to clone/duplicate Communities and to keep them eventual consistent to each other.

As you can see in following picture there is too much functionality available - "Manager" menu, "Update Welcome Video", "Publication" link and "System Upgrade Available" -
![20150930branch1](https://cloud.githubusercontent.com/assets/13684059/10213150/7c3a17ac-67d7-11e5-9470-37f0a673f295.png)
all functionality which potentially could interfere with our existing "Community <-> Nation"-Exchange

Idea:

Detect Branch by ongoing "Continuous Replication",
![20150930branch2](https://cloud.githubusercontent.com/assets/13684059/10213272/dba79fce-67d8-11e5-9d7c-62fd805247a0.png)
which is the only thing differentiating Branches from Communities, to then disable all this functionality ...

**Comment by dogi** [comment]
please comment this idea and/or bring up other solutions

**Comment by MWakas** [comment]
Ok,We will analyze this issue and will put comments in here.

**Comment by SadiaRasheed** [comment]
Initial thoughts on this are:
- Configurations database should not be replicated in cloned community.
By doing this we can get rid of "Update Welcome Video", "Publication" link and "System Upgrade Available"  buttons
- Need to hide "Manage" button in the code while making replica of the community

**Comment by dogi** [comment]
Thanks  good idea ;)
I will change my  script until next time

Still wonder how the code part would look like

**Comment by dogi** [comment]
If detect in configuruations 
"subtype":"Branch"
then
hide Manager Button

**Comment by SadiaRasheed** [comment]
-I have handled “nationName” and “NationUrl” problem. So you don't need to delete these attribute now or change their values. Button will not show up now in case of Branch Library
-Created an attribute "subType" in database  in such a manner that it does not show up on configurations page. It would be a hidden indicator for Branch Library. So you don't need to create this manually
-@Stefan: You only need to find a way to set value of “subType” to “branch”. How are you going to change the “subType” attribute value from configurations database? manually or you will do it via some script?
-If  
  "subType" :"branch" (case sensitive you must enter "branch" in database and NOT "Branch")
then the community will behave as Branch library

**Comment by SadiaRasheed** [comment]
Here are some screenshots

**Comment by SadiaRasheed** [comment]
here is the commit link
https://github.com/open-learning-exchange/BeLL-Apps/commit/7c4ce67133e961144c36d4687586fc6cbb6d517e

**Comment by dogi** [comment]
awseome

just 2 other things:
- [ ] maybe  you can still show  Manager just make it not linkable anymore, so the komma doesn't stand out
- [ ] also please hide this settings icon

**Comment by SadiaRasheed** [comment]
Okay. I am going to complete this

**Comment by SadiaRasheed** [comment]
Applied required changes. Here is the screenshot

![settings](https://cloud.githubusercontent.com/assets/10362799/10535534/15c2567e-73fd-11e5-909b-6c62b89df034.PNG)

**Comment by SadiaRasheed** [comment]
Here is the github commit link for the new changes
https://github.com/open-learning-exchange/BeLL-Apps/commit/00a00f17db8400a7d1196dd07aa6e9699b52dae9

**Comment by SadiaRasheed** [comment]
This branch library issue has beend done at community level. Do you want me to do this for nation too?

**Comment by treehouse-su** [comment]
good question

let me think ;)

**Comment by SadiaRasheed** [comment]
okay :)

**Comment by SadiaRasheed** [comment]
Added only  "subType" attribute at nation level
Here is the commit link
https://github.com/open-learning-exchange/BeLL-Apps/commit/bacb67cc45e7aa5689c8c55d83dc6a24b268893a
