### ISSUE TITLE
Search is not responding to Arabic

### ISSUE THREAD

**Issue by jstearnsw** [open-learning-exchange/BeLL-Apps#110]
Is it working in Urdu?

**Comment by SabaBaig** [comment]
Its working fine at our side, given that the parameters provided follow those rules, that are valid for searching as we do for English.

**Comment by SabaBaig** [comment]
-Steps followed to query resources from library in search feature goes as follows (on Community Level)
1) Added a new resource with a title, Publisher and Author name in Urdu along-with a document being attached having name in Urdu.
![urdu-1](https://cloud.githubusercontent.com/assets/13994879/10305553/244ab04e-6c3a-11e5-976f-b398631b8936.PNG)

2) Then, searched the resource using its full resource title
![urdu-2](https://cloud.githubusercontent.com/assets/13994879/10305572/4d4a50e4-6c3a-11e5-9002-a0c0194295f9.PNG)
3) Also, searched via substring of title of resource
![urdu-4](https://cloud.githubusercontent.com/assets/13994879/10305585/68c8d980-6c3a-11e5-87f7-e0ae5cf5efa9.PNG)
4) Searched via publisher name
![urdu-5](https://cloud.githubusercontent.com/assets/13994879/10305601/7a42886e-6c3a-11e5-83ad-2d21086ef9bb.PNG)
5) Via Author name
![urdu-6](https://cloud.githubusercontent.com/assets/13994879/10305603/8227ccba-6c3a-11e5-8964-a23391e1d65f.PNG)
All of these queries resulted in same search result
![urdu-3](https://cloud.githubusercontent.com/assets/13994879/10305614/94a5bb40-6c3a-11e5-9073-e8d5855aa6c8.PNG)

**Comment by SabaBaig** [comment]
As per my testing results on Chrome and firefox,
 Nation : nbsbell.ole.org (version : 64)
 Chrome and Firefox: Search is working fine with both Arabic and Urdu
Nation: openbell.ole.org (Version: 63)
Chrome: Search is neither working for Arabic nor for Urdu.
Firefox: Search is working fine with Arabic. 

There is no missing piece of code, so currently working on to figure out the reason of search not working across-browser.
