### ISSUE TITLE
Survey Functionality in the BeLL

### ISSUE THREAD

**Issue by jwritt** [open-learning-exchange/BeLL-Apps#111]
We would like to add survey functionality to the BeLL - perhaps to the Manager pages at both the community and nation levels (screenshots below)
![community and nation manager pages](https://cloud.githubusercontent.com/assets/11721132/10258446/315053e0-692c-11e5-94b7-c47ef2e3dcc0.JPG)

1. We want a survey creation function and a way to administer the survey to a respondent - what are your thoughts on this?

2. We would like to do some brainstorming for how we can implement this from a creation standpoint - any ideas?  

3. We would also like to brainstorm how we would deploy surveys to specific groups of or all members - what would be the best way to do this?  

4. Any ideas on how we should design the user experience?

**Comment by SadiaRasheed** [comment]
Here are some questions regarding survey functionality.
- Should it be a form which should be opened when user click on a button named survey?
- What kind of questions you want us to include in the survey?
- Should the question vary for different user groups?
- Can you provide us an example form or another thing like that? So that we can have a big picture in mind about what we are going to build.
- Will you provide us questions or information that will be included in the survey?

**Comment by MWakas** [comment]
Here are some points for discussion:
1. Place a survey button on nation's manager page.
       -click on this button
       -communities list is shown
       -chose a community and send the survey to that selected community. 
( Just like publication )
2.  Survey is sent to a community.
        -the community manager can see a notification of survey on dashboard
(Same as the update version and publication notifications).
3. select people on the basis of there roles,e.g. Leader,Learner,Manager or Super Manager etc.
        -decide who can add surveys.
(Same as only managers can view the update button,update welcome video button and publication button,no member other than admin/manager can see those buttons).

**Comment by MWakas** [comment]
Here are some points to discuss:
1. Survey page layout.
2.  Structure of  the Questions in the survey(open ended question  OR close ended questions).

**Comment by jstearnsw** [comment]
1.  Survey page layout - please show us some options (pictures) for where we would fit the survey page in the community manager page

2.  Structure of the questions - We would like to start by having you create a single survey that has multiple questions on it with the answer format for each question being a text area that can have multiple lines of text entered

**Comment by dogi** [comment]
good example for form creation is http://applywizard.com/

**Comment by MWakas** [comment]
I visited the above link and did some experiments to understand the questions types.I also have create a "Survey" feature branch and GitHub and is now solving the initial and base cases of Survey functionality.Until now, I have added a survey db in couch and solved the following base cases for this db:
1): On newly installed community, this db should also in the db's list.
2): Same as #1 for the newly installed nation.
3): Solved db issue for community update.
4): Solved db issue for nation update.
Here are the links on GitHub:
https://github.com/open-learning-exchange/BeLL-Apps/commit/11f5134082e54f10abe6657bbec8a9ef8e7bb8de
https://github.com/open-learning-exchange/BeLL-Apps/commit/2b6603fcf55a7fa8f98659a42b5d4ebbf60a698b
https://github.com/open-learning-exchange/BeLL-Apps/commit/abe8d8df822284e9a91184dd1901847ab6479b5d
https://github.com/open-learning-exchange/BeLL-Apps/commit/2129b6eeacf8abd427b1253ac90659a9b271887b

**Comment by MWakas** [comment]
Here are the GitHub commit links:
https://github.com/open-learning-exchange/BeLL-Apps/commit/d49e6b35d1aa686ebcf5df21e9018c29927016a7
https://github.com/open-learning-exchange/BeLL-Apps/commit/78ab3ef2fc71600a515a0ae9e08c31c765c44d86
https://github.com/open-learning-exchange/BeLL-Apps/commit/eb476a18c124951cd7f81d1b7ea2a0ff4bcb8dab
https://github.com/open-learning-exchange/BeLL-Apps/commit/36f21d652a3ec4d89a0341de03813b1385c512fc
https://github.com/open-learning-exchange/BeLL-Apps/commit/488e4e33bce1c9e1c4ce37e1a99c04c2180e1804
https://github.com/open-learning-exchange/BeLL-Apps/commit/48f7f345a3225efbace4849e8c9513d61c9819f0
https://github.com/open-learning-exchange/BeLL-Apps/commit/c5f08b8088d75956b3f0b5d1fb5dfaf9fbbd5d62
https://github.com/open-learning-exchange/BeLL-Apps/commit/93404494bc8097b003ca6489a4674f0b55fcd14f
https://github.com/open-learning-exchange/BeLL-Apps/commit/c3731ab7bf630cb98f6fa9d57490d09d625e94dd
https://github.com/open-learning-exchange/BeLL-Apps/commit/116f3404ada8a0ca608d403bad73d10585cacda1
https://github.com/open-learning-exchange/BeLL-Apps/commit/db8bc67334fff5098b543947b2ba36c32fed7341
https://github.com/open-learning-exchange/BeLL-Apps/commit/176b408c0d22073f3bafacdb850c1c15024c660d

**Comment by SabaBaig** [comment]
AddSurvey form is now provided at following gitHub Commit link,
https://github.com/open-learning-exchange/BeLL-Apps/commit/6ffa731c704d9d2bb441d2b5b5e7fd489d51a9d5

**Comment by MWakas** [comment]
GitHub Commit links:
https://github.com/open-learning-exchange/BeLL-Apps/commit/2f874cdeb56671a888a63cbc369b0f2dee4952a0
https://github.com/open-learning-exchange/BeLL-Apps/commit/6dd8aaa12facc6b2deabff9982a1fd6dcaf25630
https://github.com/open-learning-exchange/BeLL-Apps/commit/c1f553307d9ecde48fe0b42ceceb067526a0db16

**Comment by MWakas** [comment]
Here are the GitHub commit links for SentTo communities page and functionality: 
https://github.com/open-learning-exchange/BeLL-Apps/commit/e8fcb04ab74332f8e870049805c9cb73e191a297
https://github.com/open-learning-exchange/BeLL-Apps/commit/b9a4b53501759a479a8d44d1d8eeb14d5bb5a9a7
https://github.com/open-learning-exchange/BeLL-Apps/commit/851cd3fd386c22948b7eee17089f0de3e20d2570
https://github.com/open-learning-exchange/BeLL-Apps/commit/4ee9ab3dfe4f205f2ec96b757e2b26e1c115f257
https://github.com/open-learning-exchange/BeLL-Apps/commit/8d30a1bd7cb96c9087eb8fa2b5869aa27d5b1d33
https://github.com/open-learning-exchange/BeLL-Apps/commit/0aec3925663a970f1edb57c0b96bbade91380bc1

And here are the screenshots of the pages which can not be shown through the app yet:

**Comment by MWakas** [comment]
Here are the commit links on GitHub:
https://github.com/open-learning-exchange/BeLL-Apps/commit/fe153c968159f577420fe5f528f6d24f321f6650
https://github.com/open-learning-exchange/BeLL-Apps/commit/c13d792d6944fd45fbb2597bb15e7639e61d3deb
https://github.com/open-learning-exchange/BeLL-Apps/commit/18fab76472ce1178deb1f1692f6c81e15fe1c9c4

**Comment by MWakas** [comment]
GitHub commit links:
https://github.com/open-learning-exchange/BeLL-Apps/commit/e91ea349c608778540433e6b13f08ccc2f3a57bc
https://github.com/open-learning-exchange/BeLL-Apps/commit/b7c861f17c77d5c82042473e7914da9b16e47936
https://github.com/open-learning-exchange/BeLL-Apps/commit/cdf2d8b67fac02579c12c7fa274a213626cb7bff
https://github.com/open-learning-exchange/BeLL-Apps/commit/cf6e4ebd09b18bb43c2f0b8060c20ac55200ee62

**Comment by MWakas** [comment]
GitHub commit links:
https://github.com/open-learning-exchange/BeLL-Apps/commit/abf6fe351db7a9cb0a049349ee83459b0aed11ed
https://github.com/open-learning-exchange/BeLL-Apps/commit/e3e4663f4daa4ddd8459b8973aff09a53a998fc1
https://github.com/open-learning-exchange/BeLL-Apps/commit/f4f0a4c76b00a8684606dc9de4165e525ff5b1fc

**Comment by MWakas** [comment]
GitHub commit links:
https://github.com/open-learning-exchange/BeLL-Apps/commit/e2eb003762ead36a09784bf138c48eedc019754f
https://github.com/open-learning-exchange/BeLL-Apps/commit/88b513b7c9729fa08a2b0da20cc90e8e36b7ef6c
https://github.com/open-learning-exchange/BeLL-Apps/commit/01269bb3e3d9e31151f5c40606fd59af6ec3a6f6

**Comment by MWakas** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/24d99b119a9d4bff3c1c78fff202343101e52451
https://github.com/open-learning-exchange/BeLL-Apps/commit/633895da3e6a98d5c7ab2f9e7d7610255344352b

**Comment by SabaBaig** [comment]
-  Functionality of addQuestion is added 
https://github.com/open-learning-exchange/BeLL-Apps/commit/4d3742b3ebaad6aa647c61553329c5615135f64f
- Disabled AddQuestion while sending a Survey
https://github.com/open-learning-exchange/BeLL-Apps/commit/f647a2b0cc953f62acfa6e14f0ca0c3e8e674102
- Corrected EventHangling on Dialog of Questions
https://github.com/open-learning-exchange/BeLL-Apps/commit/df9de128d5b10a61e9988b274cf6f81639215c85

**Comment by MWakas** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/b60ab3ded5c26d812ef6aacaf847df89ee72f449
https://github.com/open-learning-exchange/BeLL-Apps/commit/6745eb1ead02f2ac9125b6145761de85d5de2160
https://github.com/open-learning-exchange/BeLL-Apps/commit/7d2a4c25e12a526a0a7830b8ddc44f2f8e533085
https://github.com/open-learning-exchange/BeLL-Apps/commit/f351c14ff7f25796028c5929da2bbf96129c856e
https://github.com/open-learning-exchange/BeLL-Apps/commit/dfc25cb166c150ceff63f7acce27f29b7b91b931

**Comment by MWakas** [comment]
GitHub commit links:
https://github.com/open-learning-exchange/BeLL-Apps/commit/183affaa119c14c57911a3c54f41cee662787fad
https://github.com/open-learning-exchange/BeLL-Apps/commit/98e977a8e7c70728af7dd07a67b13ba3e87f65f2
https://github.com/open-learning-exchange/BeLL-Apps/commit/7c4de76a22bc1e528d195a77923038876b149229
https://github.com/open-learning-exchange/BeLL-Apps/commit/64102c2e5b0726484be23c49ef0626b3d8d3d7bd
https://github.com/open-learning-exchange/BeLL-Apps/commit/b6be5f6635a05abd08e0e9b256aad921cc455a38
https://github.com/open-learning-exchange/BeLL-Apps/commit/048555365759a1a3ca1c10f027799897ce39bc72
https://github.com/open-learning-exchange/BeLL-Apps/commit/ac66c9e0864473614086fc630efc783f34bed620
https://github.com/open-learning-exchange/BeLL-Apps/commit/80c27510428cef339408dcab2a86fb15c230046a
https://github.com/open-learning-exchange/BeLL-Apps/commit/65ef4e534367fff3506d681efdf0f6b6a190b01d
https://github.com/open-learning-exchange/BeLL-Apps/commit/363ed687fe8d64e9ec5ccf11147208b1dcbb7c82

**Comment by MWakas** [comment]
GitHub commit links:
https://github.com/open-learning-exchange/BeLL-Apps/commit/4c6526ddba3dad56f1904a595ea6f1ae300f38c9
https://github.com/open-learning-exchange/BeLL-Apps/commit/be279586d2d21fc26ecce36eb4a6649d92165620
https://github.com/open-learning-exchange/BeLL-Apps/commit/898b52a5f7cd5d3303cf15891d63dba2c2e2095d
https://github.com/open-learning-exchange/BeLL-Apps/commit/78d123bedd14df0ffe78ab1f9198dc05aa91299b
https://github.com/open-learning-exchange/BeLL-Apps/commit/0a4c3c1be36d83f172a480393c3c967f981c3560
https://github.com/open-learning-exchange/BeLL-Apps/commit/a3858aadb16e0726b2db07314b1f23e9a11b0a62

**Comment by MWakas** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/303aea69da0540e61000532c13f571a83b2afdbe
https://github.com/open-learning-exchange/BeLL-Apps/commit/6fbfc2a8eb3fe57776d78a230dbf1f365dad6469
https://github.com/open-learning-exchange/BeLL-Apps/commit/43426a622d25fa39619f96955af3b52359753a3a
https://github.com/open-learning-exchange/BeLL-Apps/commit/37523d57fcc05b27573d729bd4a4adf1d97553d9
https://github.com/open-learning-exchange/BeLL-Apps/commit/399ea57dee466248452875af033cddc030055320
https://github.com/open-learning-exchange/BeLL-Apps/commit/0a01976b38303758ffc5fa044525cd34169b30fc
https://github.com/open-learning-exchange/BeLL-Apps/commit/96f3ab2c6741c5d955f5bf0f9c96b4ed1203f6b9
https://github.com/open-learning-exchange/BeLL-Apps/commit/c204ac05570a9294d49ef55c21a211cdfe31adaf
https://github.com/open-learning-exchange/BeLL-Apps/commit/b59f8f0cc696335f52f5f8910439662f9f311cbd
https://github.com/open-learning-exchange/BeLL-Apps/commit/3e92803890d20631dd46601f4ec51d8acbf52052
https://github.com/open-learning-exchange/BeLL-Apps/commit/7a803d6ed9b4b79893021eba80feb6845cf28451
https://github.com/open-learning-exchange/BeLL-Apps/commit/e2ab5798998089c6876d10000e7918c828f3a307
https://github.com/open-learning-exchange/BeLL-Apps/commit/26ab0a58208b07887194b0e7c5adca8e5b9e2398
https://github.com/open-learning-exchange/BeLL-Apps/commit/c4a1af26817bc81065e46269cbbe938fe329ed3f

**Comment by MWakas** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/aee7a00d1ca2f04451a449a4f64fa17e0db2b5e4
https://github.com/open-learning-exchange/BeLL-Apps/commit/634578299d4b31eb5a51244d1abe40785e1a47df
https://github.com/open-learning-exchange/BeLL-Apps/commit/67a174af6c58a32d7044e2e858ba70af72aaa9b5
https://github.com/open-learning-exchange/BeLL-Apps/commit/36565d35aad51ae24ee5a225afac9273bc37a8f4

**Comment by MWakas** [comment]
List of surveys at community side:
![surveylistcomm](https://cloud.githubusercontent.com/assets/10882476/13417889/ba087a60-df91-11e5-8dc0-b2ed52944f1f.PNG)

**Comment by MWakas** [comment]
GitHub commit links:
https://github.com/open-learning-exchange/BeLL-Apps/commit/4bcdbfcfe374cc6ad9987ab907b834f4e1d1477f
https://github.com/open-learning-exchange/BeLL-Apps/commit/585495f88d44e9bf7056baca499f9e0344ccc589
https://github.com/open-learning-exchange/BeLL-Apps/commit/f8cb557f98c0e6ee10a3ba706ee05c2b2acd7572
https://github.com/open-learning-exchange/BeLL-Apps/commit/4a6548b27627be64ac56f3ba50ec1e2e867074e1
https://github.com/open-learning-exchange/BeLL-Apps/commit/932a0fbf1be39671034d375b39fb062d965f87c2
https://github.com/open-learning-exchange/BeLL-Apps/commit/41e48b207eeaf0db46b3bb7d2373fc8ecc3f31a1
https://github.com/open-learning-exchange/BeLL-Apps/commit/a0621563f11bc5ca902703716d12d4d43e5536f3
https://github.com/open-learning-exchange/BeLL-Apps/commit/eda9ef72c46095e04f5f2c6f3910b96e55cbbd71
https://github.com/open-learning-exchange/BeLL-Apps/commit/5a542702a1a449b7e91e23108fc61ba054bcd07c
https://github.com/open-learning-exchange/BeLL-Apps/commit/514ffd59d690600c2209c41a8896126f34cf34bf
https://github.com/open-learning-exchange/BeLL-Apps/commit/f981899c58fb2ccb4d29a79b5f5b75cf95defeb1

**Comment by MWakas** [comment]
Here are the screenshots of survey at community side:
![surveylistatcomm](https://cloud.githubusercontent.com/assets/10882476/13492512/51791f7a-e15a-11e5-9e38-c02152bb6362.PNG)
![opensurvey](https://cloud.githubusercontent.com/assets/10882476/13492524/61354830-e15a-11e5-9bb5-e4388f939b6c.PNG)

**Comment by MWakas** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/e7deae9e70f3fc5297b923ab958b58d1479c25d9
https://github.com/open-learning-exchange/BeLL-Apps/commit/a464a92da0a24508ffb0cfe78b46ed91f7444faa
https://github.com/open-learning-exchange/BeLL-Apps/commit/3705d58a59806269475f47d2833a7390c14331cc
https://github.com/open-learning-exchange/BeLL-Apps/commit/fab761890395418620877698f12d2c20125d78bc
https://github.com/open-learning-exchange/BeLL-Apps/commit/1f39697c68d9dc6ba012a6ff8b08a7586388d196

**Comment by MWakas** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/33c7e2912e1d780f8ad797713afa4a71e5820b6f
https://github.com/open-learning-exchange/BeLL-Apps/commit/b424926edd2fa22ccac0e07ef03db4452e400a81

**Comment by MWakas** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/801d47b00ec528dc8e740a53d4248717d81ecb43
https://github.com/open-learning-exchange/BeLL-Apps/commit/ac92816a9e3eecc505606a2addae15c338e41e2e
https://github.com/open-learning-exchange/BeLL-Apps/commit/61d7777970f0b4e13c0f7b1864be7174be6c726c
https://github.com/open-learning-exchange/BeLL-Apps/commit/cf1e051fe9a039bc17cd0e07bc0f00181e59da87
https://github.com/open-learning-exchange/BeLL-Apps/commit/93047238816406304f3abe39fd18a7d2a73804dc
https://github.com/open-learning-exchange/BeLL-Apps/commit/50e0b62aa90f9df5b0a7e56319570d7789401d82

**Comment by MWakas** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/51b90d3ad8647d2d5f65af191a4390b63052b4d2
https://github.com/open-learning-exchange/BeLL-Apps/commit/ac271ae851f856d91bd1bfe2b8b33ab170602056
https://github.com/open-learning-exchange/BeLL-Apps/commit/b4303939ec50764daf05ea7ae4ab3716461f4663
https://github.com/open-learning-exchange/BeLL-Apps/commit/20cc58eccd1a41613a2205cb947204414b6ed93e
https://github.com/open-learning-exchange/BeLL-Apps/commit/18e9f5f7752cdc41039ccc8cc18597d86b3fd27e
https://github.com/open-learning-exchange/BeLL-Apps/commit/20b6dc8c5595803b0f5e04b9233c73a4d7b378f4
https://github.com/open-learning-exchange/BeLL-Apps/commit/20b6dc8c5595803b0f5e04b9233c73a4d7b378f4
https://github.com/open-learning-exchange/BeLL-Apps/commit/ea8357a6049caa057ce2d1d37b9a7628c6abf968
https://github.com/open-learning-exchange/BeLL-Apps/commit/ea8357a6049caa057ce2d1d37b9a7628c6abf968
https://github.com/open-learning-exchange/BeLL-Apps/commit/2e77011eab045414134a30cafa7f2f46bdd9ac48
https://github.com/open-learning-exchange/BeLL-Apps/commit/8fb77ace761574784d7346aa2dbaad315e6add7c
https://github.com/open-learning-exchange/BeLL-Apps/commit/4c3d39713eab88b75629f9169f07424d9c9003ba
https://github.com/open-learning-exchange/BeLL-Apps/commit/ebd221488e0ea0c7075538c0aacb4d94a999bf70
https://github.com/open-learning-exchange/BeLL-Apps/commit/c80381b4d221ac4bd19fab000fb9bb5d573b43d0
