### ISSUE TITLE
On Community after ~ 45 Publications no new Publications are showing up 

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#113]
even on Dashboard there is the alert showing 2 more Publications to download,
in the Publication Sync View there are no new ones showing up -
in other words it looks like that on kenyabell and somaliabell we reached a certain limit so the last 2 (3) publication are not being able to be downloaded, because there is nothing showing up on the publication sync page

**Comment by SadiaRasheed** [comment]
I reproduced this issue on my side by send above 50 publications to my community  and I found out
              1- when publication at community level reaches to some limit like 50 or above ( on my community it was 52) then some of them does not
              2- when I delete a publication ( which is already sent to the community) at nation level then many of the publication on community side does not show up
  Need to debug the code to find out what is causing this

**Comment by dogi** [comment]
awesome looks like you are on the right track - by reproducing the error you solved already first step

**Comment by SadiaRasheed** [comment]
This task is In-Progress

**Comment by SadiaRasheed** [comment]
SubTask: Problem occurs if you delete a publication.
If a "publication" is deleted then its relevant document in "publication distribution" database should also be deleted to avoid any inconsistency between these two databases

**Comment by SadiaRasheed** [comment]
Scenario #1:
-Debugged code at nation and community level
-I added new publication issues at new nation 
-Registered my community with new nation
-Sent publications from nation to my community 
-Counted the publication 
-Deleted all publications from “publication” database at nation but the document that contains information of publication and the community to which it was sent was still there in publication distribution database which caused inconsistency
-When a publication is sent to a specific community then a document is saved in “publicationdistribution” database which have information of publication and the community. If there is any inconsistency between “publication” and “publicationdistribution” database then all the publication wont show at community level. because at community level
-Deleted all the documents from “publication distribution” database then no notification was showed up at community level
- If a publication is deleted, then its relevant document also needs to be deleted from the “publication distribution” database to avoid inconsistency

**Comment by SadiaRasheed** [comment]
Github commit link for scenarion 1 for Issue#113:
https://github.com/open-learning-exchange/BeLL-Apps/commit/ec8474ab26878a58e27ad8773079de8da21bc97d

**Comment by SadiaRasheed** [comment]
Scenario 2: For older communities that have been created before version 0.11.66 (if this version have been installed )
If a publication is deleted but there is still its reference in publication distribution document in older communities
-find all those publications which have been sent to the community
-need a code snippet which will compare both the databases
-find if the publication is deleted but relevant document is still there in other database
-then delete the extra docs to avoid inconsistency

**Comment by SadiaRasheed** [comment]
Hindrances that I am following to solve this issue
-Nations response very slow 
-It took me one day to reproduce this issue on my side 
        -As I had to create almost 56 publications (which was a very slow process and took long)
       -Had to send all the publication to the community and see for the missing
       -Pushing code and debugging on nations is also slow most of the time especially when your internet is slow
-Need to cater every scenario for older version and newer versions 
       -As I have solved this issue( Scenario #1:  when someone deletes a publication) for newer versions (starting from 0.11.66)
      - Now I need to do this for older versions two which requires totally different strategy
    -Same goes for Scenario 2 and scenario 3
-NOTE: As a scenario gets completed I am updating waffle with comments and commit links

**Comment by SadiaRasheed** [comment]
NOTE: Two scenarios will be delivered in this release. Trying to complete other scenarios too

**Comment by SadiaRasheed** [comment]
Scenario 1 has been completed for older and newer version
(If a publication (that is sent to community) is deleted then its reference from publication distribution is also deleted)

**Comment by SadiaRasheed** [comment]
Scenario#3: 

3-when publication at community level reaches to some limit like 50 or above  then some of them does not show up on publication sync page and can't be downloaded
-------------------------------------------------------------------------------------------------------------

**Comment by SadiaRasheed** [comment]
github commit link:
https://github.com/open-learning-exchange/BeLL-Apps/commit/9ed48afe9bcbae22f923d2b04314b1cc36f0b8ac

**Comment by jstearnsw** [comment]
Additional to scenario #3 - Is it possible to sort the list of publications so that the latest (most recent) publication shows up at the top of the list?

**Comment by SadiaRasheed** [comment]
latest publications are showing at the top
https://github.com/open-learning-exchange/BeLL-Apps/commit/571930de825de6ff0563a9458eb469d36f76428d

**Comment by SadiaRasheed** [comment]
latest publication shows up at the top. Here is the screen shot from my local community
![latest pubs](https://cloud.githubusercontent.com/assets/10362799/10659341/88c715f0-78b8-11e5-8780-f87f76067ba2.PNG)
