### ISSUE TITLE
Brainstrom: What is the information of a community which can be restored out of a nation

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#114]
Dagahaley Community lost everything due factory reset, so we wonder now what is able to be recovered from a somaliabell

**Comment by dogi** [comment]
so far I know that from  http://somaliabell.ole.org:5987/_utils/database.html?members/_temp_view we can extract Dagahaley members with

```mapreduce
function(doc) {
  if (doc.community == "dagahaley") {
    emit(null, doc);
  }
}
```

Is there other stuff we can gather from our nations

**Comment by dogi** [comment]
From our partner communities (ifo, hagadera) we can take a copy of  resources.couch file.

Are there other databases we can get from them?

**Comment by SadiaRasheed** [comment]
you can get publications from them.

**Comment by SadiaRasheed** [comment]
and other things like activity logs, you can get from nation.
