### ISSUE TITLE
Update is not possible because version number is not set

### ISSUE THREAD

**Issue by jstearnsw** [open-learning-exchange/BeLL-Apps#115]
We used the 1.0.47 version of bell-installer-for-windows, then tried to update to the latest version of bell apps (0.11.67) - on the login page for community the version number did not show up

**Comment by jstearnsw** [comment]
We found that we were not able to update the BeLL without first going into Configurations, setting the version to a previous one (0.11.63) - only after doing that were we able to update (the update button showed)

Is it possible to set up the Configurations page so that the version number is displayed when a user first logs into a newly installed BeLL?

**Comment by MWakas** [comment]
I just follow the above mentioned steps and  reproduce this issue on our side.I am starting this issue so that it can be solved as soon as possible.

**Comment by MWakas** [comment]
This issue has been resolved. Here you can find changes on Github:
https://github.com/open-learning-exchange/BeLL-Apps/commit/8b13f62c9a1209c1d8d5e9aaff0ca6f93f917dbe
