### ISSUE TITLE
Add resource to publication error

### ISSUE THREAD

**Issue by jstearnsw** [open-learning-exchange/BeLL-Apps#116]
When adding resources to a publication:  If a user does not select any checkboxes (to indicate selection of resources to be added to publication) but still selects 'add resources', there is no error message displayed indicating that there were no resources selected.   

In other words, the system displays add resources success even though no resources were selected to be added by user.

**Comment by SadiaRasheed** [comment]
-Need to put an error message there if no resources have been selected

**Comment by MWakas** [comment]
This issue has been resolved.Here you can find changes in the code on GitHub:
https://github.com/open-learning-exchange/BeLL-Apps/commit/b44aea2557b8c1fd23169db6731beaa1f08cd93a
