### ISSUE TITLE
Is Search having scaling issues

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#117]
On http://openbell.ole.org (111GB of resources) and also on Dadaab Communities (90GB of resources) search is really often not completing - spinning never stops

**Comment by MWakas** [comment]
i tried to re-produce this issue on open-bell but was unable to reproduce the scenarios.If you please give me some use cases on which this issue arises,then it will be very helpful for me to trace this issue.Please also tell me that either this issue arises on AND search or simple search.

**Comment by EmilyLarkin** [comment]
It can be reproduced when you essentially click through a number of pages quickly forcing the BeLL to load content quickly. The process of reproducing is not perfect, but if you search and select a resource to view and then return quickly to search, then you will often get the continuous spinning. If you do this several times or if there are multiple users, then you will get the continuous spinning circle. It seems to be an issue of how many people are working on it: if two or three people are working on the BeLL, it will happen with much more frequency than if one person is one working on it. Continuous editing by two or three users causes the BeLL to have the spinning circle.

**Comment by dogi** [comment]
it looks like there are javascript errors
