### ISSUE TITLE
Bell installer for windows is missing to install some language files

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#124]

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/Bell-Installer-for-Windows/commit/5b1e3a1171278a133b974e1e9c5396db9702c67a done

**Comment by MWakas** [comment]
This issue has been resolved now.There were some json parsing issues and file formats issues.Its working now.Here is the commit link on Github:
https://github.com/open-learning-exchange/Bell-Installer-for-Windows/commit/95a0388e56c1bd63aa4a47152f1e70626e210985
