### ISSUE TITLE
Loop in first fill in of configuration form

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#126]
after filling out the form and pressing submit (even database gets the new values) you will get redirect into an empty "configuration form" again instead of langing on the Dashboard (Bell Installer for Windows 1.0.55)

**Comment by SabaBaig** [comment]
This issue is resolved now, here is the commit link
https://github.com/open-learning-exchange/BeLL-Apps/commit/859a127c6d37f324ab3363a890c6bdab4931d2aa
