### ISSUE TITLE
Code Refactoring required in Update's button functionality

### ISSUE THREAD

**Issue by MWakas** [open-learning-exchange/BeLL-Apps#129]
I see that the update button 's function contains hundreds lines of code.Adding new code in that function is very difficult,as it needs time to understand the whole code and to manage the older ajax calls etc and insert new ones.It must be refactored, there are so many lines which can be named as a function,e.g: the lines which update the version number should be separate function.Also the code lines which do other things must be converted into a smaller function.After writing the smaller functions,we can call them from update button's function.In this way,the code understanding,managing the old functionality,inserting the new functionality will be very easy and time saving.Please give me your thoughts on it,We can do it whenever our main priority tasks get completed.

**Comment by MWakas** [comment]
The above is the part 1.Here is another one:
Part2: Solving the double update requirement.
      -Whenever there is a change in the functionality of the update button,we need to do "update twice scenario" e.g.first update from older version to newer and second update from newer to newer(same version).It is because we have to run the newer functionality of the update button.

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/75484ca2250981394f6d8e2be05643a03dbf5e75

https://github.com/open-learning-exchange/BeLL-Apps/commit/447d7145006aeb5458803618335846e174bc8bf0

https://github.com/open-learning-exchange/BeLL-Apps/commit/f914a38ada31860a4654019b83b29463a802536f

https://github.com/open-learning-exchange/BeLL-Apps/commit/a2a86ee8d9f5f980f1eb8988fce0a85cc31ae832

https://github.com/open-learning-exchange/BeLL-Apps/commit/d46277108cf7268088deca87ea7879f6c5530046

https://github.com/open-learning-exchange/BeLL-Apps/commit/2509de92f87fdabc4bc8ca2707fa4e1ab4946602

https://github.com/open-learning-exchange/BeLL-Apps/commit/2cd07fa33dd1b81987a866526ef89b48c4ddd7c3

https://github.com/open-learning-exchange/BeLL-Apps/commit/2d367ba7f4425e235de693c09320b87e25bafb20

https://github.com/open-learning-exchange/BeLL-Apps/commit/008ebc0f6603abad4f368e186f882c282f976bda

**Comment by MWakas** [comment]
Github links for part1: 
https://github.com/open-learning-exchange/BeLL-Apps/commit/871890717e2ed0a611c07d386287976b870eba06
https://github.com/open-learning-exchange/BeLL-Apps/commit/03ea369e0c0c04c3ce91df05424f91c9e267e671
https://github.com/open-learning-exchange/BeLL-Apps/commit/15e920764ff06bd16e1b7f2634da1bab54a7ef23
https://github.com/open-learning-exchange/BeLL-Apps/commit/7dd322730d7e211c1121425ae6b87de4bd78196a
https://github.com/open-learning-exchange/BeLL-Apps/commit/7d972e6eff26b9a703953a3d59d918b88c28de2c
https://github.com/open-learning-exchange/BeLL-Apps/commit/548af64ca7611bdbfe0d18eee2fe6058db008983
https://github.com/open-learning-exchange/BeLL-Apps/commit/e095c7e3ce2e44ceb608c48414e018a638b13115
https://github.com/open-learning-exchange/BeLL-Apps/commit/124a62dca98592d4698e4ade290f3c71911a2137
https://github.com/open-learning-exchange/BeLL-Apps/commit/626d0e7fdea1a46c9377393c12df28de36443652
https://github.com/open-learning-exchange/BeLL-Apps/commit/8d8ad3af056960849b9d24cf4b88be26d9b17c40
https://github.com/open-learning-exchange/BeLL-Apps/commit/7c529d6f53d1461ee6da57efb22dd93a13284121
https://github.com/open-learning-exchange/BeLL-Apps/commit/924523201c772293a82725ba02d2ab7f4ab97962

**Comment by SadiaRasheed** [comment]
latest change in the flow of double update problem
here are the commit links
https://github.com/open-learning-exchange/BeLL-Apps/commit/351e065d352d27d28064c00c45d50b2fb106ddd1

https://github.com/open-learning-exchange/BeLL-Apps/commit/e19dbdce1280d05e68afde3bcc700bd803186d17

https://github.com/open-learning-exchange/BeLL-Apps/commit/d0ebf5362ce1ba48e7b20b5eb195cd5b08266203

https://github.com/open-learning-exchange/BeLL-Apps/commit/4c9dd7339b8ae4acc9ab4fe4012878f9c474e25b

https://github.com/open-learning-exchange/BeLL-Apps/commit/623e177e2b5a976997ef28216bb6a6087ff3310c

https://github.com/open-learning-exchange/BeLL-Apps/commit/2de420fcfb75916c22def66170d55983f83f0ade

https://github.com/open-learning-exchange/BeLL-Apps/commit/8bda8ff5aeff7b0ab02212c748c0de4b10262d23

https://github.com/open-learning-exchange/BeLL-Apps/commit/3e02669a1bb4d24e17b2fe67057cccc2ca68768d

https://github.com/open-learning-exchange/BeLL-Apps/commit/a2a2e0ba1eff72f3e70be65ebc451df489581e5b

https://github.com/open-learning-exchange/BeLL-Apps/commit/1fae92a03b58252eebd9b53e1233f6e091442bca

https://github.com/open-learning-exchange/BeLL-Apps/commit/df08c7775af6cf2e5a077799150a9da1c2618a00

https://github.com/open-learning-exchange/BeLL-Apps/commit/dc03c53c1875bb49e22c061be18264a2fa0b8a78

https://github.com/open-learning-exchange/BeLL-Apps/commit/6384806d8e28e02ad47b7f1c59050af7a040d523

https://github.com/open-learning-exchange/BeLL-Apps/commit/92299fec520932d612f0f3968a1fa7b296c6a032

https://github.com/open-learning-exchange/BeLL-Apps/commit/4c457da6b169955f29718ef8382e50bfec1b0fad

https://github.com/open-learning-exchange/BeLL-Apps/commit/0756adc9a7e8c470d4b8013e57ac423d2652ebfa
