### ISSUE TITLE
MUI:missing spaces in resource details

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#132]
There should be one space in heading and it's value in resource details in Library
![missing space](https://cloud.githubusercontent.com/assets/10362799/10910931/180032c4-8264-11e5-8066-39312d6540d7.PNG)

**Comment by SabaBaig** [comment]
This issue is resolved now, Here is the commit link,
https://github.com/open-learning-exchange/BeLL-Apps/commit/c3358de349da2dca5db3185bb6fd8a2419491be5
