### ISSUE TITLE
MUI:Header_Table Issue

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#134]
Header Table is slightly displaced towards right.  This issue was observed while we updated 0.11.73 on nbsbell and saba.nbs

**Comment by SabaBaig** [comment]
This issue appears for Urdu and Arabic languages.
![headertableissue](https://cloud.githubusercontent.com/assets/13994879/11299676/a0e319f0-8faa-11e5-9d72-21efe1f9618c.png)

**Comment by SabaBaig** [comment]
Following are the relevant links,
https://github.com/open-learning-exchange/BeLL-Apps/commit/ce28b2783888e9cbfed4286c54f16d1cf962687b
https://github.com/open-learning-exchange/BeLL-Apps/commit/4a5cd6a8c3ab34fe523a0e31b02f4e5253e2eea6

**Comment by SabaBaig** [comment]
The displacement in header table on dashboard page is now resolved , on all screen-sizes
-----------------------------
For English language
-----------------------------

![eng](https://cloud.githubusercontent.com/assets/13994879/11621882/50038552-9ce2-11e5-8c15-bc91f1b2c53e.PNG)

-----------------------------
For Arabic language
-----------------------------

![arabic](https://cloud.githubusercontent.com/assets/13994879/11621897/728c2e76-9ce2-11e5-8cac-0f377b0ce152.PNG)

You can find it on following commit link,
https://github.com/open-learning-exchange/BeLL-Apps/commit/b64c8d7299c7f154cee4f9e27d77d2ee6c652696

**Comment by SabaBaig** [comment]
Bottom tray on dashboard page is corrected for RTL languages supporting all device resolutions,
https://github.com/open-learning-exchange/BeLL-Apps/commit/d0cbc1c58e4bf86ef57d3264d4ef2230fdaad2e8
