### ISSUE TITLE
MUI:right aligned pages

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#136]
After visiting library page or courses page, following pages get right aligned
-Configurations
-Feedback

**Comment by SadiaRasheed** [comment]
![right aligned](https://cloud.githubusercontent.com/assets/10362799/10937544/4df585d0-8315-11e5-9171-eae6f2b690e5.PNG)

**Comment by SabaBaig** [comment]
This issue is resolved now,
https://github.com/open-learning-exchange/BeLL-Apps/commit/8604ea372f47bbefffab0643da248343a40fac13
