### ISSUE TITLE
MUI: clicking on "Request Resource" reloads

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#137]
Installed 0.11.73 on an old nation nbsbell.ole.org.
select urdu
Goto Library
click on Resources
click "Request Resource"
Page keeps reloading

**Comment by SadiaRasheed** [comment]
![request resource reloads](https://cloud.githubusercontent.com/assets/10362799/10937460/c2ab645e-8314-11e5-86a7-0b0e349e98e1.PNG)

**Comment by SabaBaig** [comment]
This issue is resolved now,
https://github.com/open-learning-exchange/BeLL-Apps/commit/77c06222590f3bba30635835a561d34fbd877eda

**Comment by dogi** [comment]
Issue solved, but now Navigation-bar is dissappearing on every click

**Comment by SabaBaig** [comment]
@Stefan, i did testing of this disappearing of navigation bar on 69 version then i came to know that this is the default behaviour. In 69 version when Request Resource is clicked then navigation bar disappers, so its not an issue. (Default Behaviour)
