### ISSUE TITLE
MUI: Date Orientation is distorted

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#139]

**Comment by SabaBaig** [comment]
When Language is Urdu/Arabic, this appears on Add Resource Page
![date](https://cloud.githubusercontent.com/assets/13994879/10966149/821bac90-83d3-11e5-8fd3-1ca2ff2d4eea.PNG)

**Comment by MWakas** [comment]
This issue has been resolved now.Here is the screenshot:

And here you can find changes on GitHub:
https://github.com/open-learning-exchange/BeLL-Apps/commit/85b2ebe76bffa163139cdfd565f56e9a356dcc65
