### ISSUE TITLE
MUI: Updating Nation duplicates documents in Languages db.

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#143]
Whenever a nation is updated, then languages database gets the new documents for all three languages but the old-ones are still there. Which creates lot of documents in it on each update.

**Comment by SabaBaig** [comment]
--I have resolved this issue, and now it will delete old documents of the specified language and then insert the new one. For this reason, i have been facing various errors like 
--Document Update Conflict
--No DB File
--Invalid JSON/Unrecognized token for Urdu and Arabic files
apart from other tiny issues as well...
But now, you can find out the solution on the following commit link
https://github.com/open-learning-exchange/BeLL-Apps/commit/32022fd4642177319198ead5c3d8f5373ec07f55

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/04f605659d6a0e266cf0ee7bc44f1e02e5b9ec49

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/32022fd4642177319198ead5c3d8f5373ec07f55
