### ISSUE TITLE
Activity Reports is not working

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#156]
after updating to 0.11.80 the Activity Reports are not being opened on following communities and Nations
Nations
  - Somaliabell
  - kenyabell

Communities
 - Hagadera
 - Dagahaley
 - IFO

**Comment by SadiaRasheed** [comment]
![report](https://cloud.githubusercontent.com/assets/10362799/11623740/abacc946-9cf0-11e5-8cd2-22907b3de8e2.PNG)

**Comment by MWakas** [comment]
This issue has been resolved.Here is the GitHub commit link:
https://github.com/open-learning-exchange/BeLL-Apps/commit/eb76001a9a6037b4ce918e02a6957abf646fb8cc
