### ISSUE TITLE
Feedback jump always to Library

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#163]
In case the Resource is called trough the Library Page that is as we want it, but when called in a Course it should not jump to Library Page ... it should stay in Course

**Comment by SabaBaig** [comment]
This issue is resolved now and can be found on following github commit link,
https://github.com/open-learning-exchange/BeLL-Apps/commit/2b6c9b0abf546688c0daad307082f80c3a98c2b4

**Comment by dogi** [comment]
not resolved for courses

**Comment by SabaBaig** [comment]
Update solution for this issue is available on following github commit link,
https://github.com/open-learning-exchange/BeLL-Apps/commit/54c2aa0ff37786b673d725352e53c9eadc8a0b0f
