### ISSUE TITLE
Open Button on Library does not work for first time

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#165]
When we click to open a Resource then it does not show the Feedback Form for the first time but it does it correctly when we hit Open button again...

**Comment by MWakas** [comment]
This issue is resolved.Here you can find changes on GitHub:
https://github.com/open-learning-exchange/BeLL-Apps/commit/659453207c2dfaac6bddbcd1a0c1d357cfc19a69
