### ISSUE TITLE
only manager should see new publications

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#169]
right now everybody not only is able see new publication in My Home, they are also able to download them

**Comment by dogi** [comment]
![88-1](https://cloud.githubusercontent.com/assets/13684059/12139790/b5cfc656-b430-11e5-9c3c-f6089e4d71f0.png)

**Comment by dogi** [comment]
-> checked already software update is like wanted not showing up

**Comment by SabaBaig** [comment]
This issue is solved now and here is the commit link,
https://github.com/open-learning-exchange/BeLL-Apps/commit/cc6f76dd8d6c56b40128f61d37762c2a6d189a58
