### ISSUE TITLE
send publication to multiple communities is buggy

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#172]
when I send a publication to x communities first community get that publication x times second community x-1 times ... last community gets it once
![88-5](https://cloud.githubusercontent.com/assets/13684059/12255656/10ba166a-b8c4-11e5-89fd-95e877bc9c41.png) <- this is suppose to be only 1 publication

**Comment by SabaBaig** [comment]
This issue is solved now and available on the following commit link,
https://github.com/open-learning-exchange/BeLL-Apps/commit/b0379122d520de664d45c9627db776cf0a45e8ae
