### ISSUE TITLE
styling Issue on ManageCourse and AddCourse page

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#178]
# Add Course page
![untitled](https://cloud.githubusercontent.com/assets/13994879/12472897/ab20db28-c02e-11e5-8bf9-863890917a6f.png)

# Manage Course page
![untitled1](https://cloud.githubusercontent.com/assets/13994879/12472912/f47c1bac-c02e-11e5-9462-9ce22802ebde.png)

**Comment by SabaBaig** [comment]
This issue is resolved now and is available on the following GitHub link,
https://github.com/open-learning-exchange/BeLL-Apps/commit/756313cc8566fb36ddb4eb04eac973b63a4c7042
# Add Course
![untitled1](https://cloud.githubusercontent.com/assets/13994879/12473308/ea427cea-c032-11e5-8394-08c51a9f0529.png)
# Manage Course
![untitled](https://cloud.githubusercontent.com/assets/13994879/12473309/f16532b0-c032-11e5-832a-293863972979.png)

**Comment by treehouse-su** [comment]
awesome
