### ISSUE TITLE
overhaul "Become a Member" and edit Member

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#181]
required fields:
- [ ] First Name
- [ ] Last Name
- [ ] Username (check against existing ones)
- [ ] Password
- [ ] Birth Date (unset) (range 5-120 years)
- [ ] Gender (unset)
- [ ] Level (unset)

adding fields to members document:
- [ ] loginDate
- [ ] lasteditDate (if not set or older then a year revisit edit member page)

**Comment by SabaBaig** [comment]
Follow GitHub commit links,
--Required Validation working on Add/Member
https://github.com/open-learning-exchange/BeLL-Apps/commit/4cca89e3390de7ea55044a738ab04641d1a6fb3b

--Resolved the workflow of authentication for all useCases)
https://github.com/open-learning-exchange/BeLL-Apps/commit/a1c9cee71739a6b412a081580befbe3d53094b04

--Validation on Age is added
https://github.com/open-learning-exchange/BeLL-Apps/commit/a6a10f990b8bc01dfaa09b0bbbaeb2dd9f67827d

--LastLogin date added
https://github.com/open-learning-exchange/BeLL-Apps/commit/aad8290a20de9afd5efd7e4b7b45613d19f209ab

--Remind user to review his credentials
https://github.com/open-learning-exchange/BeLL-Apps/commit/754638c927198f60dd394c3b08c36dfc21ea58bc

--Resolved workflow of reminder for Add and Edit Member
https://github.com/open-learning-exchange/BeLL-Apps/commit/907b3401407004e2792f7fe1b84ece2a9e6e949d

**Comment by dogi** [comment]
Things to change:
- [ ] "Please Review your configurations to update them." should be "Please update your Profile."
- [ ] "Admin" should maybe be an exception of this process (also Cancel button not working here)
- [ ] Cancel-Button brings me always back to  the "edit member" from instead to "MyHome", but Main Navigation is still working ... I used that as a cancel replacement
- [ ] Resign-Button brings me always back to  the "edit member" from instead of logging me out (Resign is now Reinstate Button)
- [ ] Update-Button should bring me to "My Home"

all of this was when I had to do forced Profile update, when doing normal "Member edit" by menu it should work as usual ...

**Comment by SabaBaig** [comment]
@dogi I have a question here regarding point # 02
"  "Admin" should maybe be an exception of this process (also Cancel button not working here) "
 By making "Admin" an exception in forced profile update, do you mean all those members that have the role "Manager" ? 
Also, Cancel button was disabled for all those members that have invalid information in their profiles and have not updated their profiles long ago. Otherwise, they could just skip that update by pressing Cancel button.

**Comment by treehouse-su** [comment]
On Fri, Jan 29, 2016 at 12:11 AM, Saba Baig <notifications@github.com>
wrote:

> @dogi <https://github.com/dogi> I have a question here regarding point #
> 02
> " "Admin" should maybe be an exception of this process (also Cancel button
> not working here) "
> By making "Admin" an exception in forced profile update, do you mean all
> those members that have the role "Manager" ?
> Also, Cancel button was disabled for all those members that have invalid
> information in their profiles and have not updated their profiles long ago.
> Otherwise, they could just skip that update by pressing Cancel button.
>

Gotcha - what I mostly mean is that a fresh installed system should not pop
up my admin profile for correction ...

-> maybe we just fix this guy
https://github.com/open-learning-exchange/BeLL-Apps/blob/dev/init_docs/admin.txt

**Comment by dogi** [comment]
@SabaBaig  Gotcha 

What I mostly mean is that on a fresh installed system should not pop up admin profile for correction ...

-> maybe we just fix this file
https://github.com/open-learning-exchange/BeLL-Apps/blob/dev/init_docs/admin.txt
Should an "admin" be 99 years old gender "female" and level "higher"?
the cleaner solution was to just make an exception for it

**Comment by SabaBaig** [comment]
Required navigation is added now,
https://github.com/open-learning-exchange/BeLL-Apps/commit/560b5a791a292f87140c8d2fdd9d82bb6ae7ecc3

**Comment by dogi** [comment]
![98-1](https://cloud.githubusercontent.com/assets/13684059/12908211/820fc13e-cec2-11e5-9fed-b1dfe2fc5f23.PNG)

this is the screen after I did  not fill out any of our scroll fields Birthdate, Gender and Level
-> the design breaks ;)

also the error message should be more specific

**Comment by SabaBaig** [comment]
- Revised workflow to resolve design problems
https://github.com/open-learning-exchange/BeLL-Apps/commit/a38d7133f6e92bcb42ab2e97b07591b86d2558ed
- Customized text on dropdowns and refined error message
https://github.com/open-learning-exchange/BeLL-Apps/commit/90d6ca063743c9deec04787dc23dd4e069314daf
-
