### ISSUE TITLE
search of adding Resource to Publication should be left-aligned

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#183]
![95-1](https://cloud.githubusercontent.com/assets/13684059/12667090/403d0ed4-c615-11e5-8171-214f23f3d198.png)

**Comment by SabaBaig** [comment]
This issue is resolved now,
https://github.com/open-learning-exchange/BeLL-Apps/commit/3d9a471a0ba83520df863b592eba6dfca4a9668b

![capture](https://cloud.githubusercontent.com/assets/13994879/12716753/ac2f7d60-c904-11e5-96a6-adb43b7661b3.PNG)
