### ISSUE TITLE
MUI: Invitation Type

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#185]

**Comment by SabaBaig** [comment]
The label on invitationForm is corrected now,
**Demo**
![untitled](https://cloud.githubusercontent.com/assets/13994879/12807133/650e6dde-cb2e-11e5-8d6a-2c78dad7935a.png)

**GitHub Commit link**
https://github.com/open-learning-exchange/BeLL-Apps/commit/b27bdabc675e7c9c6fdb7635b333e920524e860b
