### ISSUE TITLE
open resource by URL/URLpart

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#187]
for example:

- http://new.qa.ole.org:5985/resources/5cf42ee2d9906b74cb2032456f0055f3/index.html?file=94a204df08669e780d40131dd7002471

-  /resources/5cf42ee2d9906b74cb2032456f0055f3/index.html?file=94a204df08669e780d40131dd7002471

**Comment by MWakas** [comment]
GitHub commit link:
https://github.com/open-learning-exchange/BeLL-Apps/commit/a366c3d80fa738b2327137f639c5b840db6688c6

**Comment by MWakas** [comment]
GitHub Commit Links:
https://github.com/open-learning-exchange/BeLL-Apps/commit/ad77447020593426b334194363470482a865073f
https://github.com/open-learning-exchange/BeLL-Apps/commit/ddb99755a60c6b6851f0c98e891705f3b0050fe2
