### ISSUE TITLE
language selection for every member

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#194]
- [x] define global bell language
- [x] select language by cookie in welcome screen
- [x] add language dropbar to the dashboard
- [x] and after this active selection in the dashboard save it to user profile

**Comment by SabaBaig** [comment]
@dogi Adding a dropdown on dashboard would look like this, please share your views with us. 
![dashboard](https://cloud.githubusercontent.com/assets/13994879/13352675/c0251068-dcb0-11e5-8232-965a2d03302e.png)

**Comment by MWakas** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/56dda00f18ab66461e6573060f2c737b889d233c
https://github.com/open-learning-exchange/BeLL-Apps/commit/5f941bc3c543070aab6cebad3031dfa0e07563c8
https://github.com/open-learning-exchange/BeLL-Apps/commit/bfb2aefe370440948b4620488a036b715c6620d5
https://github.com/open-learning-exchange/BeLL-Apps/commit/ea8af0bb4cf0470dfacd01480b9069949b6d0366
https://github.com/open-learning-exchange/BeLL-Apps/commit/a5493e98b099100dcee1069bb33e17205b9b23b7
https://github.com/open-learning-exchange/BeLL-Apps/commit/af41343ae2f436e459c6b46c060c9d0214676b5a
https://github.com/open-learning-exchange/BeLL-Apps/commit/71e8eb558c38f3fa66840fb11ec08bf69e2a6bfe
https://github.com/open-learning-exchange/BeLL-Apps/commit/a2d403097c4bb5751d05348c60e95083b1ad6c2d
https://github.com/open-learning-exchange/BeLL-Apps/commit/c5f7a9e379c3b0c6dbf2c296b04200994cd8516c
https://github.com/open-learning-exchange/BeLL-Apps/commit/ab57b3c21db1f6c443b93b474e34e0f7e18c41aa

**Comment by MWakas** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/243d46843b6c35312797a0b38b4d2d4a6280c565
https://github.com/open-learning-exchange/BeLL-Apps/commit/17e7b3469bcf61264fcd2bb426d4d0ebcf09d52f
https://github.com/open-learning-exchange/BeLL-Apps/commit/f1e8d06400646f81da419138cf43ba0baa7f3b17

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/dc410127e33cb5db1b9dd4916a9ddbd29975b0dd
https://github.com/open-learning-exchange/BeLL-Apps/commit/10857e50089306c864233bf7e3ff45d9d950be03
https://github.com/open-learning-exchange/BeLL-Apps/commit/de5c5a1fe849a39f8a8ab9152d6ca5e0e02ab972
https://github.com/open-learning-exchange/BeLL-Apps/commit/6e1a56df2d04235e5b1f5fd74c543c6a1af464cf
https://github.com/open-learning-exchange/BeLL-Apps/commit/8818e7a18a0deba2a7e3bfa6432a94e1e4a942dc

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/85beb45c4d9ccdbb581a805181f6a4fb7951c518
https://github.com/open-learning-exchange/BeLL-Apps/commit/6337b1db24dd8c28035aee67692312e89be6ffbc
https://github.com/open-learning-exchange/BeLL-Apps/commit/a32519aafd5939972166fb03a4162ab8c7f2c4ea
https://github.com/open-learning-exchange/BeLL-Apps/commit/20604d1140e66eb97b7f247638e0f15a2a6dad39

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/d66f3a772014f896c704e6b5d9b85c28931ffed8
https://github.com/open-learning-exchange/BeLL-Apps/commit/051ffabc5f9de47af066e23affcfa4af949295d2
https://github.com/open-learning-exchange/BeLL-Apps/commit/298d87dd6773a1cc4f4bb43102b5803dd3126e84
https://github.com/open-learning-exchange/BeLL-Apps/commit/f956d75e56eeabc5f0900e37a8463157555d7db7
https://github.com/open-learning-exchange/BeLL-Apps/commit/ae1dd8679a42daeb5a29b4de2abeb805325186c6
https://github.com/open-learning-exchange/BeLL-Apps/commit/7c2e5fad2fce27ad26ced375e249e97f350b1c8e
https://github.com/open-learning-exchange/BeLL-Apps/commit/f7f86b6cef1231cd7e6d5eb74adbf253b79aef9e
https://github.com/open-learning-exchange/BeLL-Apps/commit/37f283eb3ccc1bde230e8ef246b4b63410717522
https://github.com/open-learning-exchange/BeLL-Apps/commit/37f283eb3ccc1bde230e8ef246b4b63410717522
https://github.com/open-learning-exchange/BeLL-Apps/commit/7ed99de8c7718018cec110878ef2830db0423063
https://github.com/open-learning-exchange/BeLL-Apps/commit/2d1c5751336f1e71ed0ac3c4cff8824acc618c45
https://github.com/open-learning-exchange/BeLL-Apps/commit/7183cb5abf915dfb8fd7a3628734dda84c366410
https://github.com/open-learning-exchange/BeLL-Apps/commit/da72757c6c995531120d7ad41e40967ad936ff80
