### ISSUE TITLE
Unable to open course resources from "Courses"

### ISSUE THREAD

**Issue by EmilyLarkin** [open-learning-exchange/BeLL-Apps#197]
On all nation BeLLs (Kenya, Somalia, Syria, Open, and QA), a user is unable to open/view resources from course under "Courses" and "Manage"a specific course. The only way they can open/view a resource from a course is under "Open" in "My Course Progress"; while this is good, it should be available under "Courses" and "Manage" too. Please follow the steps below to find this bug:
1) First you have to create a course on QA BeLL. Go to "Courses" and select "Add Course". You get to the page below and you fill out the essential information to create the course. 
![screen shot 2016-03-04 at 4 39 39 pm](https://cloud.githubusercontent.com/assets/15271637/13540990/b3bd589a-e227-11e5-9df3-b78735213651.png)
2) Then, you add a step to the course by clicking on "Add Step". You once again fill out the basic information and after creating it, you edit the step by clicking on "View Details" and then 
![screen shot 2016-03-04 at 4 04 43 pm](https://cloud.githubusercontent.com/assets/15271637/13541054/1894c1a4-e228-11e5-8fee-4a4ab127ca04.png)
click on "Add Resource".
![screen shot 2016-03-04 at 4 04 21 pm](https://cloud.githubusercontent.com/assets/15271637/13541028/ef5cc67e-e227-11e5-8f93-f95adfc16245.png)
![screen shot 2016-03-04 at 4 04 48 pm](https://cloud.githubusercontent.com/assets/15271637/13541062/24521848-e228-11e5-81f4-a25e570f2bec.png)
3) After clicking on "Add" a resource, search for anything and add any resource. I added the below resource as it was easy. Click "Add to Level" and then you'll be back at the details of that specific step. It should look like below. 
![screen shot 2016-03-04 at 4 05 08 pm](https://cloud.githubusercontent.com/assets/15271637/13541107/5fd5de72-e228-11e5-9b40-1bb312ac5bef.png)
![screen shot 2016-03-04 at 4 05 16 pm](https://cloud.githubusercontent.com/assets/15271637/13541113/62efcdac-e228-11e5-89a8-4c18037b8dea.png)
4) Then click on "View" when looking at the resource of a step. It will open a new tab, but no resource will be there and the screen will be white. This is the bug as there should be a resource there. The resource should be available and it should open like all other resources. 
![screen shot 2016-03-04 at 4 05 20 pm](https://cloud.githubusercontent.com/assets/15271637/13541145/844c9066-e228-11e5-82da-b3e61ef1b4bf.png)
![screen shot 2016-03-04 at 4 06 14 pm](https://cloud.githubusercontent.com/assets/15271637/13541154/8ee37c24-e228-11e5-8b3b-afdcf1105ada.png)

**Comment by SabaBaig** [comment]
There was problem in the URL as it was not appending the title of Resource to be opened with it. This issue is resolved now for you to rest it.
![Issue#197_Screenshot](https://cloud.githubusercontent.com/assets/13994879/13562172/21184bf8-e457-11e5-8c03-750a2cb84a61.PNG)

**GitHub Commit Link**
[Issue#197](https://github.com/open-learning-exchange/BeLL-Apps/commit/ea842c1ea34792fefb5cca9e9f2a876ee92c128c)
