### ISSUE TITLE
Download Survey Response in CSV format

### ISSUE THREAD

**Issue by MWakas** [open-learning-exchange/BeLL-Apps#202]

**Comment by MWakas** [comment]
http://code.ciphertrick.com/2014/12/07/download-json-data-in-csv-format-cross-browser-support/
http://www.hybridplanet.co.in/tutorial/javascript/how-to-create-csv-or-excel-file-from-json-via-javascript
http://stackoverflow.com/questions/8847766/how-to-convert-json-to-csv-format-and-store-in-a-variable
http://www.zachhunter.com/2010/11/download-json-to-csv-using-javascript/
http://jsfiddle.net/hybrid13i/JXrwM/

**Comment by MuhammadWaqas05** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/f9119ea32439a0260d170f7b3fd852a8d6613019

**Comment by MuhammadWaqas05** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/2e7aefc6b3d03efb18cf0c6aee7d6ed65fba743f
https://github.com/open-learning-exchange/BeLL-Apps/commit/9fe695dc610aa9144e1dbd16c855f136c9c5045f
https://github.com/open-learning-exchange/BeLL-Apps/commit/f119bde72291314e602677902ed913c951dd90e0
https://github.com/open-learning-exchange/BeLL-Apps/commit/dc2db9a056d98cffc995519dde3170fde4de85c5
