### ISSUE TITLE
Opening directly from shelf without step in between

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#206]

**Comment by SabaBaig** [comment]
@dogi we can get rid of the resource-detail page by adding a small icon on the shelf with each resource with an image of cancel(to remove it from shelf). For this purpose, we have to add another table for each resource in shelf and accordingly add up columns and rows to achieve the goal.

**Comment by dogi** [comment]
I suggest an tiny icon (X or trashbin) on the end of the resource text or in the top right corner

**Comment by umarWaris** [comment]
-[Issue#206(shelf resources can be opened and deleted from dashboard)](https://github.com/open-learning-exchange/BeLL-Apps/commit/671c35c04f016ae2d65507ab216ce38e5bd0ee3b)
-[Issue#206(corrected the styling in dashboard, go to back page after feedback and title should be changed in dashboard if that is changed in library)](https://github.com/open-learning-exchange/BeLL-Apps/commit/1a270afb2a0cb09a25bd0d040972b629c1d83eb9)

**Comment by umarWaris** [comment]
-[Issue#206(title is central aligned and cross button placed at correct location)](https://github.com/open-learning-exchange/BeLL-Apps/commit/aa21b7bbe6f26a8ab5c6684a7aad4a2035b113ea)
