### ISSUE TITLE
MUI | Communities module at Nation

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#208]

**Comment by SabaBaig** [comment]
- [Generate Report](https://github.com/open-learning-exchange/BeLL-Apps/commit/7266f46c1ece10108cc48b3d8bd2e36a7cf708e3)

**Comment by umarWaris** [comment]
-[Issue#208(community page is updated)](https://github.com/open-learning-exchange/BeLL-Apps/commit/97c0333b4147d8a6f9c0bde304308f520ef45fb7)
