### ISSUE TITLE
MUI | Improvements for managerial page at Nation

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#212]
The managerial page at Nation is currently having few UI elements existing for no reason apparently. 

###  Suggested Improvements
* Remove the buttons named as *"Click for more"*  since their alternative ways exist on the navbar.
* Remove unwanted columns in the preview table like *Databases and Requests*.
*  Instead, *add column for Survey* which is of more important in terms of usage at Nation.
* *Remove the hard-coded data in these preview columns* and fetch data dynamically from the server.
* *Change the symbol of icon that leads to profile management* of admin to some other more meaningful symbol from gear-icon.
* *Remove the button of Configuration* at the bottom of page.
*  Now, *make the gear-icon lead to Configurations* of Nation.

**Here, is a prototype of managerial page at Nation after recommended changes**
![POC_ManagerOfNation](https://cloud.githubusercontent.com/assets/13994879/14043683/b7e00b2a-f2a8-11e5-956b-b166326c36b8.png)

**Comment by dogi** [comment]
Can we get ride of the "Manager Menu Bar"? and still have a functional managerial page

**Comment by SabaBaig** [comment]
@dogi we can get rid of the "Manager Menu Bar"  according to the layout suggested by you in today's meeting,
![Improvement at Nation](https://cloud.githubusercontent.com/assets/13994879/14104300/ecc19cec-f5bd-11e5-9068-b77248de014a.PNG)

**Comment by SabaBaig** [comment]
@dogi here is another suggestion from our side that encompasses both previously presented ideas,
![poc_nation](https://cloud.githubusercontent.com/assets/13994879/14244046/80356ff4-fa72-11e5-8ac5-4f1a5bd1e0eb.png)

**Comment by SabaBaig** [comment]
@dogi please guide me what to do in such scenario.
![suggestion](https://cloud.githubusercontent.com/assets/13994879/14562692/9048394e-0337-11e6-9a87-3c7c13ed2005.PNG)

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/b9b4b2a12b7b6c479f5b75de8a7096956fb6e2af
https://github.com/open-learning-exchange/BeLL-Apps/commit/9a14945d3985bb37b7840a9ec924afd99888b166
https://github.com/open-learning-exchange/BeLL-Apps/commit/8af645ada72587124a7dfce22b747a030360d410
https://github.com/open-learning-exchange/BeLL-Apps/commit/9b34bf4d8365eeeca6218309a4f8c936a871ad38

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/076909fca9f15e034599ebba98ac78527e405e5d

**Comment by dogi** [comment]
menu disappeared ...

![7-1](https://cloud.githubusercontent.com/assets/13684059/14709606/818cbad0-079f-11e6-835e-a197d127e742.PNG)
