### ISSUE TITLE
exact numbers in activitylog

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#213]

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/85bfe2ec445c5171b693d2e4cd80f57f81756bf3

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/9ee2671342043e49cab7b51fe167fe59a3beba7d
