### ISSUE TITLE
manager of course is not the creator of it

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#216]

**Comment by dogi** [comment]
lets go more in dept with the different roles:
- Supermanager
- Manager
- Leader
- ...

**Comment by SabaBaig** [comment]
@dogi as per my exposure in courses, I believe there are three roles 
- **Manager**
- **Leader**
- **Learner**

We broke down the problem _Anyone should be able enough to manage any course_ into a basic use-case that _Learners of any course should be able  enough to manage it_. For this purpose, I did R&D and found out there are few implementations in [MyApp/Views/GroupRow.js](https://github.com/open-learning-exchange/BeLL-Apps/blob/dev/app/MyApp/app/views/GroupRow.js) which cause only leader to manage any course. Here, if we add the check that _if the person who has logged in is a member of this course then he/she should be able enough to see that manage button_.

**Comment by dogi** [comment]
define QA CourseCases

also remember:
1 add course credit
2 success /completion
3 show on Badges/Credits page for each member

**Comment by SabaBaig** [comment]
https://docs.google.com/a/northbaysolutions.net/document/d/1tbkb29xCnvT4gk0a4g1Fhiublkiqe-giAjz1yfrZev4/edit?usp=sharing

**Comment by SabaBaig** [comment]
- [Course Leader cannot be specified at course creation time](https://github.com/open-learning-exchange/BeLL-Apps/commit/f1ee157a5e4696c73048f36fef9af63f9e7bd2cf)
- [Disable the select an option text from course leader](https://github.com/open-learning-exchange/BeLL-Apps/commit/ce8df2c8ecdec8cf2bb60fb36fe2e92a2a991455)
-  [Make more than one leaders selectable for one course](https://github.com/open-learning-exchange/BeLL-Apps/commit/07ae10657e1d501e846f599fbea27ab018fe247d)
- [Display on current bell's members for leader](https://github.com/open-learning-exchange/BeLL-Apps/commit/a079130bd3fa46cbc7ef1a41728983795f180740)
  -  [Only managers can add course](https://github.com/open-learning-exchange/BeLL-Apps/commit/bb7e70ae0e3611c43afd7dff903b738c8e1a5798)
  -  [make Copies based upon leaders selected](https://github.com/open-learning-exchange/BeLL-Apps/commit/2004fb7b87763907895c8dc4d94816476455f1a5)
  - [Differentiate courses by their leader names](https://github.com/open-learning-exchange/BeLL-Apps/commit/46b0736d5f88d002ed4df5392f5a94139d9dc1e1)

**Comment by SabaBaig** [comment]
The underlying issues are resolved in branch 'course-leader' which is now a part of 'dev'.
