### ISSUE TITLE
reverse sort of publications

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#220]
split publications into 2 groups:
- first unsynced
- followed by already downloaded isses

and sort:
- unsynced by increasing issue number
- already downloaded by decreasing issue number

**Comment by SabaBaig** [comment]
- [Reverse sort of Publications](https://github.com/open-learning-exchange/BeLL-Apps/commit/75ec4350e9d8c7b118dda45ee2d285288f5e487b)

**Comment by dogi** [comment]
awesome for community, but forgot to mention that we want reverse sort always also on nation

**Comment by MuhammadWaqas05** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/bed2fbbc7e4b3eabec7c039e8f721e4b5d2ab394
