### ISSUE TITLE
Feedback answers are backwards

### ISSUE THREAD

**Issue by EmilyLarkin** [open-learning-exchange/BeLL-Apps#229]
When you go to the main dashboard (or any page) and click on the "Feedback" button on the top of the screen, you are prompted with this feedback page. We need to switch the order of the buttons (from left to right) to from "Cancel" "View" "Submit" to "Submit" "View" "Cancel". In English, the submit is always on the left while the cancel is normally on the right. Please look at the picture below for clarity. 

![screen shot 2016-04-22 at 3 20 17 pm](https://cloud.githubusercontent.com/assets/15271637/14752665/a7f8446e-089e-11e6-8b33-2ddb5180134d.png)

**Comment by umarWaris** [comment]
-[Issue#229(Feedback answers are backwards)](https://github.com/open-learning-exchange/BeLL-Apps/commit/2747d54e71762c693edfe1d414b38ee0046a14fe)

**Comment by umarWaris** [comment]
-[Issue#229(Nation side Resolved)](https://github.com/open-learning-exchange/BeLL-Apps/commit/f653990b2e43c77b6b1d68e22733f8a1f7b9fb30)
