### ISSUE TITLE
Sending survey to community members based on criteria

### ISSUE THREAD

**Issue by MuhammadWaqas05** [open-learning-exchange/BeLL-Apps#234]

**Comment by MuhammadWaqas05** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/ef9d5c05cdbdaa253cdb39f806073f6854653412
https://github.com/open-learning-exchange/BeLL-Apps/commit/8fdec52c1d3e8658d335b58333f571be7afda3ec
https://github.com/open-learning-exchange/BeLL-Apps/commit/d1e7419f67f2d23b7ad71e151659a55a75ef478f

**Comment by MuhammadWaqas05** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/26ccf239b8f9d5fea807f25d8eb4b77d7a5dbf26
https://github.com/open-learning-exchange/BeLL-Apps/commit/9f4164d5827b86fbb7ab6e4b564998314b860731
https://github.com/open-learning-exchange/BeLL-Apps/commit/376dd49ffd43b32877669037a466853fa75a0b82

**Comment by dogi** [comment]
make nation same as community (optional)

**Comment by MuhammadWaqas05** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/f7762b5b009b74c577d0dd83fb2a7bcc6342ce5a
