### ISSUE TITLE
First member in the list is not getting survey at new nation

### ISSUE THREAD

**Issue by MuhammadWaqas05** [open-learning-exchange/BeLL-Apps#235]

**Comment by MuhammadWaqas05** [comment]
This issue is not related to first member in the list or with new/old nation.This error is due to something else which is described in the following issue#245  https://waffle.io/open-learning-exchange/BeLL-Apps/cards/5726ffd9cb8df68300b83571

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/issues/245
