### ISSUE TITLE
Invalid login at nation side

### ISSUE THREAD

**Issue by MuhammadWaqas05** [open-learning-exchange/BeLL-Apps#245]
In nation's members database, we have members of that nation + the members of communities registered with that nation.If a member of nation and a member of a community has the same login, then there may be some errors when the member of nation will get login. For example, if there are two members 
1: nation-Member with login test 
2: community-Member with login test
Now, nation-Member will login to bell-Apps by login-Id test, then it is possible that he may not get the valid information on his dashboard like survey's count etc. , instead he may get the data of community-Member. So we have to add some check to validate that only the valid member(in this case it is nation-Member) should get login if there are duplicate logins exist.

**Comment by dogi** [comment]
this is related to https://github.com/open-learning-exchange/BeLL-Apps/issues/235

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/7671f93bf5d675b144dfe1cccdbb4c9b174a29bf

**Comment by dogi** [comment]
On my QA cycle all the "admin"s are squeezed out

https://github.com/dogi/ole--rpi-bells/tree/master/qa

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/e39efde686bae93366cbbab0fddb8e260486df15

**Comment by SabaBaig** [comment]
Problem: On a fresh install of community and nation, once admin has logged in (with default configurations) then his "community" attribute is going to be set as say "TestCommunity" as in configurations-community.txt. Later on, if in that same session if community name and code is changed then admin won't be able to log in again.

**Comment by dogi** [comment]
this is also on Community side:
- [x] Configurations Form should show up after fresh install
- [x] Configurations Form has to update the community of the "admin" when Field CODE is changed

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/a0c21188ffbaabb6d907b7f4103bbd85e6338e17
https://github.com/open-learning-exchange/BeLL-Apps/commit/31248e7a9359adea3c9b857a4fcaed3d6dbe78b7
https://github.com/open-learning-exchange/BeLL-Apps/commit/b093552e12a6cb10f2d7e7851fa4e8ac3d53d1d8
