### ISSUE TITLE
MUI | Same logins distort language at Nation

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#249]
At nation side,  when there are more than one members of same login though belonging to different bells (i.e they differ based upon their attribute of "community" in document) then when the "bellLanguage" attribute is fetched to render application in that particular language. Whichever document is on the top is fetched and hence one user is mistakenly displayed the language of another user of the same login.

**Comment by umarWaris** [comment]
-For getting Language at Nation side, fetch all the documents with the same login as that of the cookie and then match community attribute to code attribute of configuration to correctly fetch the user language

**Comment by umarWaris** [comment]
-refactor the code at both nation and community side for getting language correctly if the nation has 2 or more than 2 members with the same login

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/2e1ecb8fe91bfffa3772d075bd5f659d6dba5ddb

**Comment by dogi** [comment]
this is also solving issue https://github.com/open-learning-exchange/BeLL-Apps/issues/247
