### ISSUE TITLE
Courses | Create a leader-less course at nation-side

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#251]
- Everybody should be able to create courses.
- This Creator should be able enough to skip the leader name at the time of creating any course and yet specify course steps for that course; so as to send that course later-on to communities.

**Comment by SabaBaig** [comment]
- Only manager(s) should be able to create courses.
- Manager(s) should be able enough to skip the leader name at the time of creating any course and yet specify course steps for that course; so as to send that course later-on to communities.

**Comment by SadiaRasheed** [comment]
- leaderless courses are being created already in Courses. 
- The Creator is able to skip leader name at the time of creation
