### ISSUE TITLE
Courses | Specify leader(s) at community-side

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#252]
- Once a course is received as publication at community-side, manager(s) of that community should be able to specify course leader(s).
- Without creating more than one document in couch of that course against each leader.

**Comment by SabaBaig** [comment]
- Once a course is received as publication at community-side, manager(s) of that community should be able to specify course leader(s).

**Comment by SabaBaig** [comment]
@dogi if we are specifying more than one leaders for any course, then in that case the question rises that which of the following scenario are we following??
- One course being managed by 2 leaders, both share the members. Its more like that one of them serves as an alternative option of other; in case he is sick
- One course is being managed by 2 leaders and each of them is maintaining his own set of members.
  Similarly what about the course steps?

**Comment by SabaBaig** [comment]
The "Select an Option" text does not seems to be of any use once after multiple selection is enabled so its text should be disabled for better UX.

**Comment by SabaBaig** [comment]
Another suggestion, so as to avoid selecting any false member as a Leader is to display only those members who belong to the given bell.
https://github.com/open-learning-exchange/BeLL-Apps/commit/64c0e8fb0a2168bedd8fec5db0c11d49a4540dfb

**Comment by SadiaRasheed** [comment]
Select multiple leaders and update the course
https://github.com/open-learning-exchange/BeLL-Apps/commit/e9de21ef52f7435d8775e1b52688b69900db08ea

**Comment by SabaBaig** [comment]
[Select Multiple Leaders on Course/add](https://github.com/open-learning-exchange/BeLL-Apps/commit/a038995c3b15bdae7b0123926a3e1a379caa39ff)

**Comment by SabaBaig** [comment]
Problem: Each time select an option is selected in course leader's place and we click on continue /update a member with 0000 ID is added into member of that course.

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/ed9d8c57006c334e4201debb73ccaed32796a7bd

**Comment by SabaBaig** [comment]
Improved the selection of Course Leader
[Union Operation on courseLeader selection](https://github.com/open-learning-exchange/BeLL-Apps/commit/0405f5c70082af7f3c8eb743af38361ba6b92a7f)

**Comment by EmilyLarkin** [comment]
@SabaBaig and @SadiaRasheed: works from the GUI perspective but @dogi will followup shortly about the couch side of your concerns
