### ISSUE TITLE
Courses | Send emails to leader(s) for admission

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#253]
In case of more than one leaders for any course, to whom should be the email for admission in any course be sent?
One suggestion is to prompt from the learner that whom he want to send the email out of list of leaders for the course under-consideration.

**Comment by SadiaRasheed** [comment]
If there are multiple leaders of a course then email should be sent to all of them. 
@dogi: What will happen if there are two leaders of a course and one accepts the request but other leader "rejects" it.
Please share your views on this?

**Comment by SadiaRasheed** [comment]
If any of the leaders has accepted the Admission request email then the member will be granted admission of that course. There is OR operator working here.

**Comment by SadiaRasheed** [comment]
commit links
https://github.com/open-learning-exchange/BeLL-Apps/commit/2263ba2bfa2e4ba0fc11c5e01dc557d9da7bf479
https://github.com/open-learning-exchange/BeLL-Apps/commit/2263ba2bfa2e4ba0fc11c5e01dc557d9da7bf479
