### ISSUE TITLE
Courses | Add/Update Leader(s) after course being created

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#254]
- Manager should be able to update the leader(s) for any course.

**Comment by SabaBaig** [comment]
@dogi at the moment, a leader cannot change the leader himself but he may resign from the course. As per the option provided in courseInfo page, see screenshot.
![Leader resigns from course](https://cloud.githubusercontent.com/assets/13994879/15205540/a04bbee2-1831-11e6-8687-821ade323020.PNG)

**Comment by EmilyLarkin** [comment]
![screen shot 2016-07-20 at 12 13 32 pm](https://cloud.githubusercontent.com/assets/15271637/16993919/597b982a-4e73-11e6-9fd7-ea9cd93fcd8b.png)
