### ISSUE TITLE
Courses | 'Admission' button should show proper message in leader-less course

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#256]
In a leaderless course, when user clicks on admission button it should display a proper message e.g., "Email can't be sent as Leader has not been specified"

**Comment by SabaBaig** [comment]
There is another suggestion that if some learner requests to become member of a leaderless course then he should be added to the course directly. @dogi please share your views on this.

**Comment by SadiaRasheed** [comment]
@dogi: If there is no leader of a course then email should be sent to the "manager"/"managers" of that course. What do you say?

**Comment by SabaBaig** [comment]
Email to every manager of that community if there is no leader

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/6863e8c5015ff69f691b3b1a187ab366b13a06cd
https://github.com/open-learning-exchange/BeLL-Apps/commit/5a4b01e6be9226273234c0ada459c5a19b170c5c
https://github.com/open-learning-exchange/BeLL-Apps/commit/dd55adbc7bb9535f59af0c906da4e812c1a624b7
https://github.com/open-learning-exchange/BeLL-Apps/commit/c3e9e5ddafdecc2149b0217c640498c904bb5a0d
