### ISSUE TITLE
Courses | Missing  leaderName

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#262]
- In case of course having multiple leaders the course detail page is not showing up leaders names and rather says "undefined undefined".
- All leaders of any course are not pre-selected when you click on manage button for any course.

**Comment by umarWaris** [comment]
![course page](https://cloud.githubusercontent.com/assets/17467658/15285968/f20ad9d0-1b73-11e6-9efa-83c4a6df309f.PNG)

**Comment by umarWaris** [comment]
leader detail is separated by comma(,). e.g in case of more than 1 leader their names, emails, phone numbers would be separated by comma

**Comment by umarWaris** [comment]
If the email or phone number does not exist or empty then this would be replaced by (-)

**Comment by umarWaris** [comment]
![capture](https://cloud.githubusercontent.com/assets/17467658/15287217/c8c30258-1b7a-11e6-9585-6f74ee7b344b.PNG)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/6c60396684b775b50be7200d735391feab23f95e

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/6c60396684b775b50be7200d735391feab23f95e

**Comment by umarWaris** [comment]
![capture](https://cloud.githubusercontent.com/assets/17467658/15318046/94ff26fe-1c3d-11e6-8f1b-d971b4151dd1.PNG)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/b201f53e34128e6776dd903a642987363b3fc7bc
