### ISSUE TITLE
Hide/Unhide button on Resources is malfunctioning

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#266]
It is observed that the "Hide/Unhide" button doesn't work on first click, as on first click the spinning wheel goes on spinning. The action is performed when you click on it for the second time.Such malfunctioning was seen on v0.12.12 and correct behavior can be found on v0.12.3. Meanwhile, from which release the issue actually started occurring  is still unknown.

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/db014f9df020b9f00f2481f24abec5dfcb289022
