### ISSUE TITLE
Courses | Course Steps do not show up at once

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#267]

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/1843e698150c3484aa84c22c981db0ebdb60ae34

**Comment by EmilyLarkin** [comment]
@umarWaris @SabaBaig I am still seeing this issue where the Steps do not load automatically. It's quicker than I remember it when this issue was created, but still needs further testing and improvement before this issue can be closed
