### ISSUE TITLE
Courses | Ambiguous  "Invalid Allowed Errors" message

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#268]
When you add values into the form of Courses>>Add Steps then there comes an alert when you do not enter correct values for allowed errors. The alert does not guides the user the correct criteria to follow. It should be more descriptive.

**Comment by umarWaris** [comment]
Title, Description and Allowed Errors are necessary fields on the add step form

**Comment by umarWaris** [comment]
Now the respective message would be shown to the user if not filled

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/4d823028424f0f3daf58e0d22b940d65299e1dc8
https://github.com/open-learning-exchange/BeLL-Apps/commit/30cd9a4a1588ffd59a779b2e480fe594aa3bf146
