### ISSUE TITLE
Courses | Incorrect text in invite email's body

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#269]
When any user receives the invite email for course then after submitting his response in the form of Accept/Reject the user is delivered an incorrect message that does two things
- Displays wrong name of Sender
- From more technical point of view its not following rules of MUI.
  Please see attached screenshot for more details and resolve this issue for both Accept and Reject cases.
  ![Incorrect message](https://cloud.githubusercontent.com/assets/13994879/15390050/1f7b9d3a-1dd3-11e6-8a2e-7cadc53839ed.PNG)

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/5a34bde4a085616a5f2e622cf4f08691af22e57e
