### ISSUE TITLE
Courses | Duplicate members in case of Multiple Leaders

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#270]
When one user sends request for admission in one course. Course has multiple leaders. Then If all the leaders accept that invitation then that user is duplicated each time a leader accepts the request.
**Proposed Solution**
_At the time of accepting or rejecting admission request it should check whether that person is already added to course or not and thus notify the current leader_

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/d2516d1acb02358ae93eb3842d65e0f158581a8d
