### ISSUE TITLE
Courses | Course Steps not appearing for multiple Leaders

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#271]
Under the route of **usercourse/details** the course steps only show up for first leader only not multiple.

**Comment by SabaBaig** [comment]
After doing R&D on this issue, it was found that the **memberprogress** document was not being saved correctly for those members and hence it was related to [Issue#257](https://github.com/open-learning-exchange/BeLL-Apps/issues/257)

**Comment by EmilyLarkin** [comment]
Looks good
