### ISSUE TITLE
Survey: Non-English languages text in csv should be human readable

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#273]
Wonder what the right encoding will look like. Anyhow right now it is not human readable ...
![15-1](https://cloud.githubusercontent.com/assets/13684059/15438390/f2ad9110-1e99-11e6-9e57-63d1d3fa7384.png)

**Comment by dogi** [comment]
http://syriabell.ole.org

**Comment by sente** [comment]
After digging this a little bit, I think the problem is because of the `escape(CSV)` method, see:

https://github.com/open-learning-exchange/BeLL-Apps/blob/967bd6ff48659b2564f032655cdd67c6b56ed190/app/nation/app/Router.js#L3537

_(edited for permalink)_

**Comment by sente** [comment]
without the escape: http://sente.cc/c/S5kS/without_escape.csv

**Comment by MuhammadWaqas05** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/4c154e2f11b4317bd3a36bd0e1cca53a9a627de0
