### ISSUE TITLE
MUI | Send to bell members button functionality on survey detail page

### ISSUE THREAD

**Issue by MuhammadWaqas05** [open-learning-exchange/BeLL-Apps#280]

**Comment by umarWaris** [comment]
Before
![capture](https://cloud.githubusercontent.com/assets/17467658/15818984/dbfbefe4-2bf9-11e6-88b1-d78c61512648.PNG)

After

![capture](https://cloud.githubusercontent.com/assets/17467658/15819088/7e2521fa-2bfa-11e6-82ae-efa4c17e7ee1.PNG)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/32d89fdae88aa5b32c1129c076f9ef6d2527300b
