### ISSUE TITLE
MUI | Get members list button functionality

### ISSUE THREAD

**Issue by MuhammadWaqas05** [open-learning-exchange/BeLL-Apps#281]

**Comment by umarWaris** [comment]
Before

![capture](https://cloud.githubusercontent.com/assets/17467658/15819296/cc805896-2bfb-11e6-9822-d81d380bf703.PNG)

After

![capture](https://cloud.githubusercontent.com/assets/17467658/15819341/16b80b34-2bfc-11e6-8a00-0f8cfb44d6c5.PNG)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/aef5b00845934e8ca9aa219c21464c9419587120
