### ISSUE TITLE
MUI | Send by criteria button functionality

### ISSUE THREAD

**Issue by MuhammadWaqas05** [open-learning-exchange/BeLL-Apps#282]

**Comment by umarWaris** [comment]
Before

![capture](https://cloud.githubusercontent.com/assets/17467658/15819413/6461d78e-2bfc-11e6-8459-63a8f9ceb4d0.PNG)

After

![capture](https://cloud.githubusercontent.com/assets/17467658/15818155/1f02cbaa-2bf5-11e6-8116-b12bb9130508.PNG)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/b4e8318e1c7b76391f7172580916349aed8bb0b9
