### ISSUE TITLE
MUI | Members survey page

### ISSUE THREAD

**Issue by MuhammadWaqas05** [open-learning-exchange/BeLL-Apps#283]

**Comment by umarWaris** [comment]
Before 

![capture](https://cloud.githubusercontent.com/assets/17467658/15819479/d333baba-2bfc-11e6-9a7b-c42dcb27e1f2.PNG)

After

![capture](https://cloud.githubusercontent.com/assets/17467658/15771277/ff7efb42-2982-11e6-8ca5-76fe3b46f9fb.PNG)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/4e32f38dc4fcbb3fa0e37bdcdb9904c1b4445956
