### ISSUE TITLE
Make BeLL-Apps more easy to install

### ISSUE THREAD

**Issue by MuhammadWaqas05** [open-learning-exchange/BeLL-Apps#288]
Refer to following document for further details,
https://docs.google.com/a/northbaysolutions.net/document/d/1EwyepvC2clNaUyk568_nuhr9u_xmx_vknPEnRqFQccs/edit?usp=sharing

**Comment by MWakas** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/c73dfd333160d03168caa4f121ef4e59c199d64d
https://github.com/open-learning-exchange/BeLL-Apps/commit/64ea12480da5c031e353d189a1ab8a45f5b5b6c4
https://github.com/open-learning-exchange/BeLL-Apps/commit/c4eb6577f124537bbfe094bcd481c0c4715a1067

**Comment by MWakas** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/29bec27bd94c6f20009a4c36594e6ff1ed41e5c5
https://github.com/open-learning-exchange/BeLL-Apps/commit/e169304d8a3a2bb4232463d02e5cbcc5b8020cc4

**Comment by MuhammadWaqas05** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/cc69b3bf2475b1d0d7539d5490363837c1a8067c
