### ISSUE TITLE
Courses | Remove "Allowed Errors"

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#291]
![issue291](https://cloud.githubusercontent.com/assets/13994879/15778054/34c8c8ee-29ad-11e6-92f2-a4f11a05075d.png)

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/3534d89192ef704d1228d9831cfa45fd3f847f2e

**Comment by SadiaRasheed** [comment]
![allowed erros](https://cloud.githubusercontent.com/assets/10362799/15891891/35541fb6-2d90-11e6-93eb-2a6861709dde.PNG)

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/6e1976fb8c6dc106275c1018e33e4230c8fa41f1

**Comment by SadiaRasheed** [comment]
There was a ripple effect due to removal of allowed errors, course steps were not being opened. So we had to clean the code up to make the course steps work properly.
