### ISSUE TITLE
Courses | Make "Add Question" in Courses similar to Survey

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#293]
Allow all four basic question types to be added in Quiz of Courses just like in Survey.

**Comment by EmilyLarkin** [comment]
@SabaBaig I agree- I think this is a very important functionality to have as it will drastically improve quizzes in Courses. Let me know if you need additional support on this issue.

**Comment by lmmrssa** [comment]
@dogi  I believe this issue is already resolved so can we have this issue closed.
