### ISSUE TITLE
Courses | Change orientation of "Upload Paper" button

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#294]
![issue1](https://cloud.githubusercontent.com/assets/10362799/15775044/2b9900e0-2999-11e6-8ac2-1343195401e3.PNG)

**Comment by SadiaRasheed** [comment]
It should be entirely in blue area

**Comment by umarWaris** [comment]
![capture](https://cloud.githubusercontent.com/assets/17467658/15855669/335fe12a-2cca-11e6-9be6-0ce4a23a59c5.PNG)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/3650fc0a44c6d11a167f8ec865214dcc2b3b05b6

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/a0835cb4b9b6eb58279988bc701620298e9074da
