### ISSUE TITLE
Courses | Remove "Upload Quiz" button in course step for Learner

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#296]
![issue3](https://cloud.githubusercontent.com/assets/10362799/15778586/8d466348-29b0-11e6-887c-aac75ed44da7.PNG)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/1ba4de421bc1817a51fff9a79a422fc0b54764bd

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/103de2ca15cd5dd935e5c29eda79cc3e3da7dc0c

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/6e1976fb8c6dc106275c1018e33e4230c8fa41f1
