### ISSUE TITLE
Courses | Put a check-mark when document is uploaded

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#297]
- There should be a checkmark in course step to show that user has uploaded paper
- At the moment, we're saying that when user will submit some document. His step should be cleared. (If that step involves not quiz but a paper only)

**Comment by SabaBaig** [comment]
![issue297](https://cloud.githubusercontent.com/assets/13994879/15777989/c288e6d8-29ac-11e6-98a9-9b34ceda83df.png)

**Comment by SadiaRasheed** [comment]
If the user has submitted both paper and quiz the there will be a check mark and 100% as shown in picture given below
![quiz and paper](https://cloud.githubusercontent.com/assets/10362799/15964588/bb1496a0-2f32-11e6-8a23-9455f0f538f6.PNG)

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/266f9a045b13854b40b149a5d64aa5f60b77f34a

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/a7dab7f2ec6b3b8867ca5a86594b1f20b28df2cd

**Comment by SadiaRasheed** [comment]
This issue will be resolved in Issue#350 ( Courses | Paper evaluation )

**Comment by EmilyLarkin** [comment]
As @SadiaRasheed mentioned, this is staying open for issue #350

**Comment by SadiaRasheed** [comment]
@EmilyLarkin : you can test this issue and close it.
If this issue is working fine then Issue#400 will also be working fine
Please letme know if this works fine on your side as it is working on my side
