### ISSUE TITLE
Survey | resolve misleading admin download

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#303]
The problem is that admin download the new survey and then click onto the open button and wonder why they can't submit the answers

How do we differentiate this view from the actual survey?

**Comment by sente** [comment]
Perhaps we should say something along the lines: _This is how the survey will appear to users_.

**Comment by MuhammadWaqas05** [comment]
![commsurveys](https://cloud.githubusercontent.com/assets/10882476/15883681/f36826e6-2d63-11e6-9e9d-77f29f64c983.PNG)

@dogi The above is the page you are talking about contains the surveys which community receives from nation.Admin will download a survey on this page and also can see the content of survey.If downloaded survey is also for admin then it will be shown to him and he can submit by opening the following page(like all the members can view/submit their surveys):
![membersurveys](https://cloud.githubusercontent.com/assets/10882476/15883761/ad02d38a-2d64-11e6-8470-3e6ddd4502e8.PNG)

If downloaded survey is only for non-admin members, then he/she will not be shown that survey on above page.So for submiting/view the surveys, every member(either he/she is admin or not) have to click on this button:
![dashboard](https://cloud.githubusercontent.com/assets/10882476/15883486/ee0629ca-2d61-11e6-97b0-20fc1c444c94.png)
At the moment, both the pages are handled nicely.If we allow admin to submit the survey on community's surveys page, then the functionality of members page will also be disturbed.

**Comment by dogi** [comment]
@MWakas yes I know
I think @sente is on the right path

Can we just add his line somewhere on this view where the admin can see which survey he downlaoded

**Comment by MuhammadWaqas05** [comment]
@dogi yes sure, we can add that line on this view.That will be more helpful for users to understand the purpose of this page.

**Comment by MuhammadWaqas05** [comment]
This issue is resolved. Here you can view commits on Github:
https://github.com/open-learning-exchange/BeLL-Apps/commit/aec4caa87fb934b39b9a370d2816355a81c813e2
https://github.com/open-learning-exchange/BeLL-Apps/commit/88384ce09b29f18be8e9d09ff36abfa532462f1a

**Comment by sente** [comment]
Thanks for the quick turnaround, @MWakas!

The screenshots are really helpful in understanding the situation.

Could you include a final screenshot of how this message is displayed on the page?

Also, is the `*` intentional the message: `This is how the survey will appear to users.*"?`

**Comment by MuhammadWaqas05** [comment]
@sente Thanks for your nice feedback. Here is the screenshot with message on that page:

![surveymsg](https://cloud.githubusercontent.com/assets/10882476/15919379/39e4a0ce-2e2a-11e6-9311-9562ef5e5783.PNG)

If you want to change the message, we will change it for sure.
