### ISSUE TITLE
Overhaul Registration of Communities at Nation-side

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#307]
In the continuation of  https://github.com/open-learning-exchange/BeLL-Apps/issues/286 and https://github.com/open-learning-exchange/BeLL-Apps/issues/287 next step is implementation at nation-side.
- There should be a page at Nation-side to see which communities are already registered with it and the ones which have pending registrations.
- Next, Auto-fill "Communityfrom" with the information provided by community in the form of a read only document.
- At the end of the form, nation should be privileged enough to either accept or reject the request.

**Comment by MuhammadWaqas05** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/0413f8ace2bab12f9cb11f5ffb3987891208321a
https://github.com/open-learning-exchange/BeLL-Apps/commit/dfafd73e382480f0868aeef06ec87a43a5325136
https://github.com/open-learning-exchange/BeLL-Apps/commit/67ac3d3a648b5df906871270db2086fda9d52a03
https://github.com/open-learning-exchange/BeLL-Apps/commit/effd5fc3a90632117463609bb49f28264f74db7a
https://github.com/open-learning-exchange/BeLL-Apps/commit/ceced5ddf6d9373d56a4ddd4ba20d2a1d76bd69d
https://github.com/open-learning-exchange/BeLL-Apps/commit/9d6deda51b641bcb781af9996a5a6c531dc6ddf4
https://github.com/open-learning-exchange/BeLL-Apps/commit/9f701efe0372706c44f8ff21010aee397cbffa60
https://github.com/open-learning-exchange/BeLL-Apps/commit/293ae84bcd72b6b24375620fd57dc23525fb63af
![admin page](https://cloud.githubusercontent.com/assets/10882476/16031581/324b06ba-3216-11e6-9200-f73b87049b38.PNG)
![commconfig](https://cloud.githubusercontent.com/assets/10882476/16031584/36e6862c-3216-11e6-91f2-60dd7e9fa41b.PNG)
![commdetails](https://cloud.githubusercontent.com/assets/10882476/16031585/3a947234-3216-11e6-8a73-ab98b95150e7.PNG)

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/bb5727379732a3168dae3700b666344e9517cea1

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/f5934cb8690b577e87b8864e3d353bc6066409ba
