### ISSUE TITLE
courses | If user uploads new paper then override previous paper

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#310]
Right now a user can upload multiple papers in a course step. So change this functionality so that new paper will override the previous paper

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/b83e832cdce8c6001c9413024044a09da88bba68

**Comment by EmilyLarkin** [comment]
Closed as [345](https://github.com/open-learning-exchange/BeLL-Apps/commit/80893226013a4bf53bc0c961f3b688549892d41b) now addresses bug that was created with this issue
