### ISSUE TITLE
Improving initial load time of app

### ISSUE THREAD

**Issue by rjsteinert** [open-learning-exchange/BeLL-Apps#32]
Our Javascript files are adding up so the initial download of the app is starting to slow things down.  Check out the `grunt-concat-and-uglify` branch. Check it out, install node.js on your system, run `npm install -g grunt-cli` and then from the root directory of the repo run `grunt`.  You'll see that the files listed in Gruntfile.js [here](https://github.com/open-learning-exchange/BeLL-Apps/blob/grunt-concat-and-uglify/Gruntfile.js#L8) are then compiled in the file listed [here](https://github.com/open-learning-exchange/BeLL-Apps/blob/grunt-concat-and-uglify/Gruntfile.js#L9). This will decrease the size of the initial page load as well as decrease the number of files that need to be loaded. Hopefully this will have a noticeable effect on the load time, only one way to find out though.

**Comment by MWakas** [comment]
Exploring Grunt right now.

**Comment by MWakas** [comment]
http://blog.teamtreehouse.com/getting-started-with-grunt
http://enzolutions.com/articles/2014/08/26/grunt-how-to-list-available-tasks/

**Comment by MWakas** [comment]
http://www.sitepoint.com/5-grunt-tasks-improve-performance-website/

**Comment by MWakas** [comment]
I have learned and tested some of the commands in grunt. I have also read about some ways to speedify our app as I shared some links above.Here are the tasks we can do using grunt(by running the command "grunt tasks"):
compass: Compile Sass to CSS using Compass.
concat: Concatenate files.
default: Alias for "concat", "uglify", "imagemin", "compass" etc.
imagemin: Minify PNG and JPEG images.
uglify: Minify files with UglifyJS.
watch: Run predefined tasks whenever watched files change.

After analyzing the above tasks and commands in grunt, I am thinking about how should we proceed further .We can discuss this in today's meeting.If you have any ideas about that,please comment here if possible.

**Comment by MWakas** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commits/grunt_uglify_and_concat
https://github.com/open-learning-exchange/BeLL-Apps/commit/b8cccb105fde660202c161fa0d02b068a00d20f4
https://github.com/open-learning-exchange/BeLL-Apps/commit/1c0df17cba8f0d56f758c94b2dc628280dd4bbfb
https://github.com/open-learning-exchange/BeLL-Apps/commit/7cc84d1c6ec055fd524e14e5df6a2b18ec8ec03d
https://github.com/open-learning-exchange/BeLL-Apps/commit/a6580ba35e0d4733a059944e3a9771e5f637b3ed

**Comment by MWakas** [comment]
Here are the steps I did follow for this task:
>>Install grunt my machine.
>>Install grunt in the Bell-Apps repository.
>>Added Gruntfile which is necessary one.
>>Install concat, uglify and other handy plugins of grunt.
>>Run grunt for concatenation of the JavaScript  and css files.
>>Run grunt for uglifying(minifying) the above concatenated files.
>>The above tasks have been performed at community and nation level.
It seems the load time of the application decreased from 11 seconds approx to 2.7 seconds.You can find changes in the code at the link I pasted in the above comment.

**Comment by MWakas** [comment]
Session with Stephan.We discuss that there will be a script.This script will:
-clone of a new release from Bell-Apps repository non GitHub.
-apply the new changes from the above cloned repository to the Grunt/Production repository.
-push the Production code to its Production repository and will also make a new production release on GitHub.

**Comment by MWakas** [comment]
The Gruntfile.js has been finalized to use for the production-script.

**Comment by dogi** [comment]
let's try to setup automatic version of it on dev.ole.org

**Comment by MWakas** [comment]
I did experiments on Gruntfile.js for third party code concatenation and minification. As per my findings,following are the ways, we can proceed with:
1): As third party code is not so often changed  and there are no chances of it, in near future as well,  so we can concatenate and uglify third party code for the first time only and can use those optimized files(As I proposed in the beginning also in this way everything works fine). If ever there will be a change we can replace the optimized files with the newest ones as this is not so much time taking  process, only 15 minutes to do all this stuff.
2):  There is a Grunt Plugin named as "usemin", I started examining it and found out that we can use this plugin for third party code but it requires to learn it first(2-3 days required for it) and then we may apply it but still its not guaranteed that whether application will work fine or not with it(As there are a lot of third parties in the application and when they are combined in single file they start throwing undefined errors ).
3): We can leave third party libraries in there original format(without concatenation and minification). They won't make any nominal difference in loading time of application (just a difference of about 1 second fast when they are processed according to #1 and about 1 second slow when we leave third party libraries Untouched ).
Please share your views on above.

**Comment by dogi** [comment]
for 1) https://www.npmjs.com/package/hashcat

**Comment by dogi** [comment]
- [ ] streamlining dev.ole.org
- [ ] full QA between production and new fast build
- [ ] automatic fast build

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/pull/744
