### ISSUE TITLE
Community side integration of 288

### ISSUE THREAD

**Issue by MuhammadWaqas05** [open-learning-exchange/BeLL-Apps#333]
The easy install functionality should be integrated into the older functionality at community side e.g:  at configurations page etc.

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/6ed00a7f66d3933f204a077adf3a277640b80db5
https://github.com/open-learning-exchange/BeLL-Apps/commit/c31d5fa1138a7914891517327e99d9150601447e

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/283725a21a41279240035ae90691da2620233750
https://github.com/open-learning-exchange/BeLL-Apps/commit/a4b403f87622f3caaa157c35a3752d795582b7d7
https://github.com/open-learning-exchange/BeLL-Apps/commit/750f692ccaf8ba4b1f9446d35df049d46de11345
https://github.com/open-learning-exchange/BeLL-Apps/commit/b26d69383ce2f168130c9e741db437b333f6b202
https://github.com/open-learning-exchange/BeLL-Apps/commit/05fa564b78edeebcdf9b1c1c0daa66ee20b2cd2a
https://github.com/open-learning-exchange/BeLL-Apps/commit/38863da8ef89903bff9402df0f5bf13492d67ec2
https://github.com/open-learning-exchange/BeLL-Apps/commit/cd2bc8c86e97088738df3f4d70adbe8a4b9ffdd7
https://github.com/open-learning-exchange/BeLL-Apps/commit/ad7e1f8c841943a1a5602a710b570057b740af86

**Comment by MuhammadWaqas05** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/fb0904b41ad7750f2267dcc8c0db13d1724cae5b
