### ISSUE TITLE
Awareness of nation by community

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#336]
Right now if a community is online under the right constellation there is the possibility that the special buttons (software update, publication and issue) are showing up.
This is the only form of awareness right now to know that a nation is visible from a community ...

![23-7](https://cloud.githubusercontent.com/assets/13684059/16346424/427901fc-3a15-11e6-9e47-009dd69cf499.png)

wonder where on the dashboard we should a green light to symbolize that nation is visible?

**Comment by dogi** [comment]
```
nation is visible
nation is not visible
```

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/6b5dba99a625b24695dd8221807c76090f37910c

**Comment by dogi** [comment]
awesome so far  ;)

would like to see also a popup on click saying 

```
nation is visible
```

or

```
nation is not visible
```

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/ea2d3af0fcb3d1b754e118e58df818fe5a193713

**Comment by dogi** [comment]
As the title says this feature should only show up on a Community

Folling picture is a nation
![46-1](https://cloud.githubusercontent.com/assets/13684059/18348929/57191bde-759c-11e6-9be7-bea885d3a251.png)

Please remove or transparent the awareness feature for nations

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/0cb7d61731ea3b02194fe6bdea5b0a735f0d5852
