### ISSUE TITLE
VIPlinks to communities page on nation

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#337]
Richard wants to give some people a priority access to the community overview pages on nation and I was wondering if we can create something like with google docs share by like which give people the ability to access these pages 

by the way since these VIPs are nor learners or managers they should not see the edit, delete button  and navigationbar

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/3d28583d4bea198c50c4871c2087211cfe56b59b

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/30cebb250e2802b9e7d1e03647f5bdaf24689eb8

**Comment by dogi** [comment]
http://umar.nbs.ole.org:5980/apps/_design/bell/nation/index.html#listCommunityPage/9c154a274261c466efb4e45b9c0067c9

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/0ab89e1578286d543644d6c795022f802b39e6fb

**Comment by dogi** [comment]
Logo: http://open-learning-exchange.github.io/pages/uploads/images/logo.png

**Comment by umarWaris** [comment]
![capture](https://cloud.githubusercontent.com/assets/17467658/17135280/5a7a76cc-5348-11e6-9a9b-cb726d3b3cec.PNG)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/adda7f63d03a06b8df610df177823e188af69e12

**Comment by dogi** [comment]
Creating the database and the link was very timeconsuming

I ended up replicating db

![37-1](https://cloud.githubusercontent.com/assets/13684059/17401986/bc360cfa-5a1e-11e6-9c60-c79fbaac279e.png)

**Comment by dogi** [comment]
create db already on update and install

and by init_docs create following user

``` json
{
   "name": "dummy",
   "visits": 0,
   "lastVisit": "",
   "url": "/apps/_design/bell/nation/index.html#listCommunityPage/"
}
```

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/5d54f42aa7a7dc4a60eaa19f2ee1083682df914d
