### ISSUE TITLE
upload of resources from community to nation

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#338]
If everything works out with http://open-learning-exchange.github.io/#!pages/htmlresources.md our Virtual Interns will soon create lots of resources on their communtiies.

That is why we want now work on an easy way to bring their work to the nations ...

**Comment by dogi** [comment]
Only mangers should be able to trigger this upload

Wonder where is the best way to hide such feature?

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/7c9863056bb1af61c8bfe08b064b8153d7c688f6

**Comment by dogi** [comment]
got reverted back

**Comment by umarWaris** [comment]
![capture](https://cloud.githubusercontent.com/assets/17467658/16766202/1e38214c-4852-11e6-9746-235464917691.PNG)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/d48a1ddf69ee9902515e040b62e1a45bf18d0cd1

**Comment by umarWaris** [comment]
1) while replicating resource from community to nation, whether we have to reset the certain attributes like number of visits and number of times the members rated the resource?
2) Also tell me if any resource is replicated from nation to community through publication, then that specific resource should also display button(add to Nation) at resource detail page at community side?

**Comment by EmilyLarkin** [comment]
@umarWaris @dogi just did a simple test of this and it seemed to work quite well. Will try to stress test for better quality QA but looks good right now

**Comment by EmilyLarkin** [comment]
@dogi you may be the better person to answer @umarWaris's questions above

**Comment by dogi** [comment]
Add an alert "Are you sure you want to upload this resource?" with button's "cancel" and "OK"

also "add to Nation" button should disappear when nation is not visible

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/fdec7fdb547231eb9c39dd36bb9894c1b34671e6

**Comment by dogi** [comment]
If resource already exists on the nation add an alert "Resource is already at Nation" and don't add to Nation

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/a9202fa9609962d1167f876d6d09ab34d19f6885
