### ISSUE TITLE
Badges|  Badges implementation for learner

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#341]
Make UI for Learner to see his badge(result of a course). When "Open button", from page of badges, is clicked  then this page will show up

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/3a7565f51c315413c8013cdc4fae3ff5a4b62d2d

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/a99d8ad6f5482a2e549f0bf501cbf2c94c04f65d

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/957873ff957390ff63cf06dec6d278b66428b635

**Comment by SadiaRasheed** [comment]
![learner details page](https://cloud.githubusercontent.com/assets/10362799/16830188/d5eaf570-49b6-11e6-8133-b0d3f6aebd80.PNG)

**Comment by SadiaRasheed** [comment]
Issue #341 and Issue #387 are related

**Comment by EmilyLarkin** [comment]
@SadiaRasheed page is up, but I want to keep this issue open as it will be helpful to the related issues.

**Comment by SadiaRasheed** [comment]
![bp](https://cloud.githubusercontent.com/assets/10362799/18128763/dc65b812-6fa0-11e6-92aa-946a7f904c52.PNG)

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/ffcf9bccd568caec6726575c0d89522f7b36117d

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/87a4764662ea2f4ea917ed36dc83fe9c6407db3a

**Comment by SadiaRasheed** [comment]
![341](https://cloud.githubusercontent.com/assets/10362799/18669559/096a6a74-7f55-11e6-94b6-99f50f21d7ff.PNG)
