### ISSUE TITLE
Courses | Paper evaluation

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#350]
Paper evaluation has not been implemented yet. 
If a step has both quiz and paper then there is no way that we can save values for both paper and quiz after the user has submitted them.
If user submits the quiz and after quiz he submits paper then paper replaces the marks saved for quiz and vice versa.
Moreover, there is no way to evaluate and give marks to the paper.

**Comment by SadiaRasheed** [comment]
Step 1: While creating a step at least one should be checked either paper or quiz or both to specify the outcome of the step.
Step 2: There should be a way for saving both paper and quiz marks (values) in case of "paper and quiz" step.
Step 3: Differentiate 3 categories of steps ( 1) Paper 2) Quiz 3) Paper and Quiz ) when user submits a step

**Comment by SadiaRasheed** [comment]
I will add more steps as I complete these 2 steps given above

**Comment by SadiaRasheed** [comment]
Step 4: Save values in database based upon step category. In case of quiz and paper step, both quiz and paper values should be save separately and handled separately
Step 5: Fetch values based upon step category and show it to the user. in case of paper and Quiz step, both values should be fetched i.e one for paper and one for quiz
Step 6: Show a check mark if paper has been submitted
Step 7: Show marks if quiz has been submitted
Step 8: Show check mark and marks if " both paper and quiz " have been submitted for "Paper and quiz" step

**Comment by SadiaRasheed** [comment]
This issue will resolve the Issue#297 ( Courses | Put a check-mark when document is uploaded )

**Comment by SadiaRasheed** [comment]
## For Testing of this Issue:

-You need to edit the step which has both " Paper and Quiz" in order to populate the database.
-From now on, you must select at least one outcome either paper or quiz while creating a step.

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/f95b4a6c45f912cd53a147c0061ba73b6d9ea541

**Comment by EmilyLarkin** [comment]
So @SadiaRasheed, the paper is almost gradable, but there are still some errors. You can see the box where you could submit the grade, but the box is grayed out and does not look clickable. However, I can enter a grade (although the text doesn't change) and hit submit which will lead to some strange fraction that isn't quite right yet.

**Comment by EmilyLarkin** [comment]
![screen shot 2016-08-26 at 2 28 21 pm](https://cloud.githubusercontent.com/assets/15271637/18016291/88c486bc-6b99-11e6-85da-0427a5005006.png)

**Comment by EmilyLarkin** [comment]
![screen shot 2016-08-26 at 2 28 58 pm](https://cloud.githubusercontent.com/assets/15271637/18016294/8e62e1b8-6b99-11e6-8386-16a86464cb6b.png)

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/002a0f6be63c7eac97f66b76133d901010ce7fb8

https://github.com/open-learning-exchange/BeLL-Apps/commit/f88112edc302c11a0c496c1b4ebc6717e13eb38e

https://github.com/open-learning-exchange/BeLL-Apps/commit/14be6f1857e36f1c9c812159dda5db2138d970b0

https://github.com/open-learning-exchange/BeLL-Apps/commit/cb5fa375d440758c0536d9205f41be8954023eec

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/87a4764662ea2f4ea917ed36dc83fe9c6407db3a
