### ISSUE TITLE
Courses | Nation>>Community Undefined user created

### ISSUE THREAD

**Issue by EmilyLarkin** [open-learning-exchange/BeLL-Apps#355]

**Comment by EmilyLarkin** [comment]
When you send a course from the nation to the community, a "course member" is created called "undefined undefined" which is under the "Course Members" (Dashboard>>Course under "My Course Progress">>"Course Members"). 

![bbb14b9b-72f2-43db-beb2-c1d5bc1eabd3](https://cloud.githubusercontent.com/assets/15271637/16623056/65df6fc4-436a-11e6-831c-79c65fce5463.png)

As you can see below, there is an extra member here. However, under Dashboard>>Members there is no other member called "undefined undefined".

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/1c0b014500b43d0fb09107a5fa6507e59f4fe707

**Comment by EmilyLarkin** [comment]
@SabaBaig tested it (dev) and it looks great!
