### ISSUE TITLE
Courses | Course Details Error

### ISSUE THREAD

**Issue by EmilyLarkin** [open-learning-exchange/BeLL-Apps#356]

**Comment by EmilyLarkin** [comment]
![screen shot 2016-07-06 at 9 51 57 am](https://cloud.githubusercontent.com/assets/15271637/16623329/789d3802-436b-11e6-87e9-d46089117fc1.png)

**Comment by EmilyLarkin** [comment]
As you can see from the screenshot above, there is an error of the course details (Dashboard>>Courses (any course)>>View Details) where Leader Name is repeatedly undefined undefined

Leader Email and Leader Phone Number are repeated - -.

If a Course Leader is added, then their email is added to both Leader Email and Leader Phone Number. If there are multiple leaders of a course, multiple leaders are not added- it remains as undefined undefined.

**Comment by umarWaris** [comment]
![capture](https://cloud.githubusercontent.com/assets/17467658/16726302/eae8707c-4774-11e6-8307-90c69450bf77.PNG)

**Comment by umarWaris** [comment]
@EmilyLarkin 
I have created a new course and added 3 members as leader of the course. i am not finding any error of undefined undefined etc...

Leader email show the emails of all leader/leaders and leader phone numbers show the phone numbers of all leader/leaders

If you still find out this issue, then describe the use case for which the above error is occurring.

**Comment by EmilyLarkin** [comment]
@umarWaris This happens when you send the leaderless course from the nation to the community- I would assume you have no error because you created it on the same nation/community that you are using when trying to find this error. When you send the course from the nation to the community, it generates a lot of these errors. And in the field and in deployments, we almost exclusively use courses by creation on the nation and then sending it to communities. Let me know if you are still able to recreate the error.

**Comment by EmilyLarkin** [comment]
Sorry for the confusion, I meant to include that in the description but must have forgotten:)

**Comment by SabaBaig** [comment]
This issue is resolved with https://github.com/open-learning-exchange/BeLL-Apps/issues/355
