### ISSUE TITLE
Courses | Delete Course Member and Add Back

### ISSUE THREAD

**Issue by EmilyLarkin** [open-learning-exchange/BeLL-Apps#357]

**Comment by EmilyLarkin** [comment]
![screen shot 2016-07-06 at 10 27 25 am](https://cloud.githubusercontent.com/assets/15271637/16623833/5dd2ba72-436d-11e6-88d5-a8f86460e006.png)

**Comment by EmilyLarkin** [comment]
If a learner gains admission to the course, then leaves the course and then returns, there are multiple progress bars shown. The Course Members list is correct, but it shows the graph all of the members even if they have left the course. To access this page, go to Dashboard>>Courses>>Progress as a manager or a course leader.

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/f33c39769573773591afe9ca7305a72fbc5a1699
**Please test this issue on dev branch**
