### ISSUE TITLE
Courses | Multiple Leaders cannot be removed

### ISSUE THREAD

**Issue by EmilyLarkin** [open-learning-exchange/BeLL-Apps#358]

**Comment by EmilyLarkin** [comment]
![bd620d10-160e-4f62-844a-f6eb919c3872](https://cloud.githubusercontent.com/assets/15271637/16624262/0aa3fc9c-436f-11e6-9237-5e91e7160739.jpg)

**Comment by EmilyLarkin** [comment]
![0802a8f6-6faa-413d-a971-9098ec665a65](https://cloud.githubusercontent.com/assets/15271637/16624292/1edfcc72-436f-11e6-9a1d-ff5cfdf5379c.jpg)

**Comment by EmilyLarkin** [comment]
On a course, when you select multiple members to be course leaders and then try to change it back to a single leader, this change is not made. As you see from the picture above, this course had three managers. And below, you can see that the change was made back by a manager to to only have one course leader.

**Comment by EmilyLarkin** [comment]
![0aa3fc9c-436f-11e6-9237-5e91e7160739](https://cloud.githubusercontent.com/assets/15271637/16625501/e8ba3304-4372-11e6-951d-89e32ed2b196.jpg)

**Comment by EmilyLarkin** [comment]
You can find this page at Dashboard>>Courses>>Manage. However, when you reload the page and reclick on Manage and see this above page, there are still three managers from the original list. Additionally, you can see under Dashboard>>Course under My Courses Progress>>Course Members from the image below, these course leaders are still considered leaders even after the attempt to change them from leaders to learners.

**Comment by EmilyLarkin** [comment]
![ea09601c-59e1-4b4e-903f-4a7875741342](https://cloud.githubusercontent.com/assets/15271637/16625695/c564df2a-4373-11e6-8a01-dbd1d6c04301.jpg)

**Comment by SabaBaig** [comment]
This thing was implemented this way, so as to avoid the scenario where the manager unintentionally selects one leader and then the previous leaders are all gone. We believe that removing a leader should be a more procedural and shouldn't be done this way as it can ruin whole course if not handled carefully. So, as per now, a leader can be deleted by only a manager under the page of Courses>>Manage>>Members page.
@dogi  and @EmilyLarkin  Please share your views on my point.
