### ISSUE TITLE
easy install | improve UX for 2nd Form

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#363]
I mostly speak the form we call internally call "Become a Community", which right now is functionally working, but compared to "Become an Administrator" in the realm of "Graphics and Appeal" aka is fairly underdeveloped.

Since this 2 "Forms" is part of the first impression we need to clean them up ;)

**Comment by MuhammadWaqas05** [comment]
Ok, so can you please suggest us about layout of this form OR any suggestions/improvements/changes for current layout.

**Comment by dogi** [comment]
generally I would like that the two form's kinda have the same look and feel

also the indention needs to be congruent

**Comment by MuhammadWaqas05** [comment]
ok,We will do it. :)

**Comment by MuhammadWaqas05** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/2e36178e66b863bede95a1d336fa9a8c03afbebd
