### ISSUE TITLE
easy install | create awareness on dashboard of a join request

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#364]
As already discussed in our meeting, when a nation has a request from a community to join, the dashboard should show this, so that we do not need to click to the community overview page if we want to find out that there is maybe a potential new community

Would like that we solve it analog to the publications on communities in form of a button on the bottom of the dashboard page

**Comment by MuhammadWaqas05** [comment]
yes, sure and thanks for this nice description.

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/9c250a160540079cdd4d1178515c714df340e5d3
