### ISSUE TITLE
Credits | Notify Leader to mark credits for Paper

### ISSUE THREAD

**Issue by SabaBaig** [open-learning-exchange/BeLL-Apps#375]
Notify Leader on Credits page, about learners who have completed all the steps involved (i.e passed all quiz(s) (if any) and submitted papers (if any)) to mark credits for the paper.

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/321100e67c10317595bd1a3c45e9193b2a1d1f9f
https://github.com/open-learning-exchange/BeLL-Apps/commit/7c13eab462fd755a9acdfd1d7ae12ff8352240d4

**Comment by SabaBaig** [comment]
I also have one question here related to Issue#375: Credits | Notify Leader to mark credits for Paper
Currently, I've implemented it so as to notify Leader about number of Learners who have completed those course for which he is the leader. But if that course has multiple leaders, then should one leader be given a notification to mark credits for other leader(s) too (if they attempt that course )?? What do you say?
Please share your views on this with me.

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/855c362b427939131e690806c6bf3144d9558f3a

**Comment by SabaBaig** [comment]
**Need to implement:**
Whenever a learner submits a paper for any step, there should be a notification to respective leader(s) and manager(s).

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/967acb7ff9df002d07030c3b891b28449388a467

**Comment by SadiaRasheed** [comment]
It is related to Issue#432: https://github.com/open-learning-exchange/BeLL-Apps/issues/431
