### ISSUE TITLE
Multiple Leader not completely shown as Leader

### ISSUE THREAD

**Issue by EmilyLarkin** [open-learning-exchange/BeLL-Apps#377]

**Comment by EmilyLarkin** [comment]
I found this on new.qa.ole.org by testing a course with multiple added leaders. 

Currently, learner c c should be a Leader as they are a Leader in the course as you can see below. But c c is half Leader/half Learner (as they have all four buttons available on Dashboard>>Courses) and are shown as a Leader everywhere but the Dashboard, but on the Dashboard, they still appear as a Learner. Basically, the name on the Dashboard should also show that they are now a Leader.

**Comment by EmilyLarkin** [comment]
![screen shot 2016-07-20 at 12 13 32 pm](https://cloud.githubusercontent.com/assets/15271637/16994217/71ff6b5a-4e74-11e6-903b-619789d111e4.png)

**Comment by EmilyLarkin** [comment]
![screen shot 2016-07-20 at 12 13 47 pm](https://cloud.githubusercontent.com/assets/15271637/16994220/75e66700-4e74-11e6-95bb-eb22c5814ea6.png)

**Comment by EmilyLarkin** [comment]
![screen shot 2016-07-20 at 12 18 29 pm](https://cloud.githubusercontent.com/assets/15271637/16994226/78d72120-4e74-11e6-8768-023806c40776.png)

**Comment by umarWaris** [comment]
@EmilyLarkin  you just need to refresh the dashboard page.
