### ISSUE TITLE
Repetition of step ids in membercourseprogress database

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#379]

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/3ec10fbfb4f260038e9d5397a16e8821b015b4a1

**Comment by EmilyLarkin** [comment]
@SadiaRasheed @umarWaris Please provide more description on this issue and how to test it.

**Comment by umarWaris** [comment]
1) Go to Courses
2) Click on add new course button or "manage" of existing course
3) Click on "Add Step" then provide required fields but don't tick outcome(Neither paper nor quiz), initial error would be "please select outcomes", then select appropriate outcome and click on the button 
4) Now open the membercourseprogress database on the futon, and open the required document you would see repetition of stepsIds.

**Comment by EmilyLarkin** [comment]
@umarWaris Just to clarify and confirm, the stepIds should NOT be repeated, correct?

**Comment by umarWaris** [comment]
@EmilyLarkin  yes
