### ISSUE TITLE
Community application version not changing through configurations edit view

### ISSUE THREAD

**Issue by omeryousaf** [open-learning-exchange/BeLL-Apps#38]
The version attribute in the configuration model is not updated while other attributes are through the configuration edit view before the model is saved. Hence community application version cannot be manually changed.
https://github.com/open-learning-exchange/BeLL-Apps/blob/dev/app/MyApp/app/views/Configurations.js#L37

**Comment by SadiaRasheed** [comment]
Community' App version changes as it gets update from the Nation. If you need to change the version manually, you should change it in couchdb but still the functionality will remain the same.

**Comment by MWakas** [comment]
This issue was resolved.It should be in done column.

**Comment by dogi** [comment]
thanks
