### ISSUE TITLE
Deleting the steps the step ids are not removed from the coursememberprogress

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#380]

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/369132a2b0c0f435004afb664beeabeef8e24186

**Comment by EmilyLarkin** [comment]
@SadiaRasheed @umarWaris Please provide some description on this issue and how to test it.

**Comment by umarWaris** [comment]
1) Go to Courses
2) Click on "manage" of existing course
3) Click on "Delete" button for step, the given step would be removed. 
4) Now open the membercourseprogress database on the futon, and open the required document you would see the stepIds still exist.
