### ISSUE TITLE
Correction in method of 'Fetch by URL'  for community requests

### ISSUE THREAD

**Issue by MuhammadWaqas05** [open-learning-exchange/BeLL-Apps#383]

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/f44d1441631a75cc82a675994dcbfda081b1b4db

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/f44d1441631a75cc82a675994dcbfda081b1b4db
