### ISSUE TITLE
Incorrect Configs form for freshly installed nation

### ISSUE THREAD

**Issue by MuhammadWaqas05** [open-learning-exchange/BeLL-Apps#384]
For freshly installed nation, an odd configurations form is appearing.

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/88c09b67511d61d558fb5654d525d6f3b62c21d4
https://github.com/open-learning-exchange/BeLL-Apps/commit/80cce0cdd0b384949eba92a3b24609295b0d581c
https://github.com/open-learning-exchange/BeLL-Apps/commit/8c43feffbea06716b28314a360dff137e0e1b4b1
