### ISSUE TITLE
Courses | Gray bar error GUI fix

### ISSUE THREAD

**Issue by EmilyLarkin** [open-learning-exchange/BeLL-Apps#386]

**Comment by EmilyLarkin** [comment]
![screen shot 2016-07-21 at 3 52 40 pm](https://cloud.githubusercontent.com/assets/15271637/17036645/26b1c3fe-4f5b-11e6-8aba-43ed2fc881e4.png)

**Comment by EmilyLarkin** [comment]
This is a minor change, but the gray bar of Title and Action should be extended to the end of the screen. Action should stay directly above Manage, but the gray bar should extend. This page can be found by Dashboard>>Courses.

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/d4279d358025dcfdf14ab27db06a0f10ffd29b4e

**Comment by umarWaris** [comment]
this issue is resolved on badges branch

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/83e71f63864901dca1812dc16f96af4ba70e4be0
