### ISSUE TITLE
Login by click vs by enter key

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#39]
Cannot login by pressing the enter key after keying in the username and password credentials.
Also known as *tabindex*
![login screen](https://cloud.githubusercontent.com/assets/7746327/8242995/55a7076e-15e1-11e5-8d41-1ef5f34e7155.png)

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/2c7b06564f2c40b3f3b1cfdd8e5e37c771d81c67
