### ISSUE TITLE
Badges | membercourseprogress document is not being created correctly for learner of a course

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#400]

**Comment by SadiaRasheed** [comment]
This issue is cause behind issue#297 : Courses | Put a check-mark when document is uploaded

**Comment by SadiaRasheed** [comment]
This issue has been resolved and member course progress document is being created properly

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/d6b4b090ad8b1b6ba7f89369284b5b9af680c2b8

**Comment by EmilyLarkin** [comment]
@SadiaRasheed Can you provide some information on how to test this issue? I just need a bit more background to test for you
