### ISSUE TITLE
Dashboard | remove Release notes button

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#404]

**Comment by SabaBaig** [comment]
@dogi Release Notes button is already removed from Dashboard on "badges" branch because we had to make some space for two new buttons "badges" and "credits" respectively.

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/b43941e01c9893a26befa76dc09fa5c73ff6567e

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/b43941e01c9893a26befa76dc09fa5c73ff6567e
