### ISSUE TITLE
Dashboard | move "Update Welcome Video" button to manager page

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#409]

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/dbbd794af8cae4db388a56c6218db7b5f6a1f55c

**Comment by umarWaris** [comment]
![capture](https://cloud.githubusercontent.com/assets/17467658/17844735/fb8713f0-6855-11e6-8b06-b7896ec0419b.PNG)

**Comment by umarWaris** [comment]
Now the width of the buttons is set to auto

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/5498e9c9eac1082cf10696703b28ba590d34bab5
