### ISSUE TITLE
Improve Search Functionality

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#42]
Refer to:  https://docs.google.com/a/ole.org/document/d/1FER9o-Nd8m2jcvhMQjRcNY6TJbjHEwcNh5JhUC5l2Q4/edit?usp=sharing

What is NBS's approach/strategy for improving the search functionality? Is NBS able to find a good base script to start with so that we don't have to reinvent the wheel?

**Comment by jpierce7** [comment]
- keyword searching now provides much more limited results: we can only search for entire title and not just keywords from title, which was not the case before

- QA of the new nation with v0.11.54 installed 

![01error_no_resources_appear_publications](https://cloud.githubusercontent.com/assets/7746327/8813130/ffbcb2a6-2fce-11e5-97dd-290351fc60cf.JPG)

![02error_no_resources_appear_publications](https://cloud.githubusercontent.com/assets/7746327/8813131/02141c92-2fcf-11e5-82f2-dec28b0921c8.JPG)

**Comment by jpierce7** [comment]
For both v0.11.54 and v0.11.55, none of the search features on the nation are working but they are working at the community level. Here are screenshots:
![01_search_error_nation](https://cloud.githubusercontent.com/assets/7746327/9010854/8a7ee10c-3777-11e5-9587-9a7c2e66812d.JPG)

![02_search_error_nation](https://cloud.githubusercontent.com/assets/7746327/9010858/8e27c904-3777-11e5-9339-60931c99717b.JPG)

![03_search_error_nation](https://cloud.githubusercontent.com/assets/7746327/9010859/90032d18-3777-11e5-95ff-6377cc5eb3ff.JPG)

**Comment by MWakas** [comment]
This task should be in done as the search feature is complete and I hope so that QA is also complete.

**Comment by dogi** [comment]
qa'ed and error in progress in https://github.com/open-learning-exchange/BeLL-Apps/issues/52 and https://github.com/open-learning-exchange/BeLL-Apps/issues/95
