### ISSUE TITLE
Badges | Add 'Open Button' on Courses page

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#422]

**Comment by SadiaRasheed** [comment]
![open button](https://cloud.githubusercontent.com/assets/10362799/17585222/ece7b230-5fd3-11e6-88a3-16dc7aef375f.png)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/be533a60ada41558261eb7ee5748e4ae339adedc
