### ISSUE TITLE
Add A Resource: Change Order of tabindex

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#43]
Reorder *tabindex* in the add a resource page

**Comment by dogi** [comment]
please "assign" yourself

**Comment by jstearnsw** [comment]
The tabindex is fixed - thank you.

After further discussion, we've decided that we would like the "Add New" button out of the tabindex.  Please remove this button from the tabindex and instead have the "Save" button highlighted after the "Browse" button is highlighted.

**Comment by SadiaRasheed** [comment]
It has been completed
