### ISSUE TITLE
Credits | Add Grade button on submissions page

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#432]

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/e5b972b14d7b68d3d4476989a87c06570de83178

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/2c9f1f0b5744074f9c4d518db261eb0dd923bb87

**Comment by SadiaRasheed** [comment]
![grade button](https://cloud.githubusercontent.com/assets/10362799/17960608/939245fe-6ac0-11e6-9682-cfd41cf7800b.PNG)

**Comment by EmilyLarkin** [comment]
Great work!! @SadiaRasheed
