### ISSUE TITLE
Use Tablet Away From Router (Offline Use)

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#44]
A learner/leader should be able to load a tablet with his/her bookshelf resources, courses, and meetups while connected to the router and then can take that tablet home (or at least disconnect it from the router) and still be able to use those features.  Then when the tablet is reconnected to the router, the learner's/leader's activity that was produced during the offline time should then be synced with the community and added to the trend activity report.

Dogi mentioned that RJ had created a prototype that is in its early stages and it would be worth revisiting this to see how far RJ got.

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/take-home
