### ISSUE TITLE
nation: manager confirmation of from community uploaded resources

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#446]
Since right now resources uploaded by a community differ by the attribute "type" : "community", we are able to identify them.

We will create a button like "resourses(<number>)" which leads to a library view with for each resource following buttons: "Open", "View Details", "Accept" and "Decline"

Accept will remove the attribute "type"
Decline will remove the whole resource 

Also resource of this type should no show up in the normal library view

**Comment by umarWaris** [comment]
I wanted to tell you that we would not remove attribute "type" instead we would change its value from "community" to "nation".

Like , when we create a new resource at community , "type" has value "community".
and so, when we create a new resource at nation , "type" has value "nation".

**Comment by sente** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/blob/50ec2ce5d5837b7701c6bac27db812b36c508746/app/MyApp/app/views/PendingResourceTable.js

Is creating a new `PendingResources` model the best way to go about this?  I very well may be but the code is 95% the same as Resources.. makes me think there may be a better way.

Thoughts, @dogi, @umarWaris?

**Comment by umarWaris** [comment]
@dogi @sente , i am not creating new model, i am just creating some views

**Comment by dogi** [comment]
thanks @sente - sorry did not see your comments earlier

I was once suggesting similar way to @umarWaris but he convinced me that this other is also viable  ...

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/be75a2f851c5ac590736fc93d7f18ec26a6f7c48
