### ISSUE TITLE
Upload Software/App as a Resource to the BeLL (.apk)

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#45]
Be able to upload software/applications especially .apk files (i.e., Tak Tak Tak) as a resource and then be able to download(?) and open the software on the tablet. It would also be good to capture the activities (at least star ratings, comments, and number of times opened) of the learner.

**Comment by SadiaRasheed** [comment]
I have added a .apk file as a resource and then downloaded it and installed on an android tablet

**Comment by SadiaRasheed** [comment]
I am going to check feedback for this .apk resource now

**Comment by treehouse-su** [comment]
thanks

**Comment by SadiaRasheed** [comment]
Feedback is also working for .apk file. You can give rating and save the feedback.
![apk1](https://cloud.githubusercontent.com/assets/10362799/9993161/bdbe2e38-608f-11e5-9b7e-eaa8905edd0b.PNG)
![apk2](https://cloud.githubusercontent.com/assets/10362799/9993166/c4139188-608f-11e5-8978-ad8268e36b1a.PNG)
