### ISSUE TITLE
Change the Nav Bar direction

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#450]
Change the nav Bar direction for badges functionality

**Comment by SadiaRasheed** [comment]
![navbar](https://cloud.githubusercontent.com/assets/10362799/18546520/d65605fe-7b57-11e6-9214-8e9f57f40363.PNG)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/c6a160b69c814d57683d24f818c216a164726569
https://github.com/open-learning-exchange/BeLL-Apps/commit/c6ac3ae01b0506019f5103cff06b60fb48b6c335
