### ISSUE TITLE
Manager should be able to see contents of the course after clicking "Open" button

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#452]
In a Leaderless Course, Manager should be able to see contents (steps) of the course when he clicks on Open button.
Course->Open

**Comment by SadiaRasheed** [comment]
To see the contents of the course, Manger should be a member or leader of the course. It is already implemented this way.  Each member and leader of the course have a member courseprogressdocument in the memebercourseprogress database, which is responsible for tracking the progress for the course. If a manager don't have this 
membercourseprogress document in the database, he won't be able to see the contents as he can't upload the paper or take the quiz.  

If a manager want to see the contents of a course, he should enroll himself in the course or become leader of that course. By doing so, he will have his own membercourseprogress document in the database and will be able to see course contents.

As by clicking on open button, member sees his own paper quiz contents ( if he has upload a paper or quiz , he will see a check mark and quiz marks which are fetched from his membercourseprogress document from the database). So if he does not have one, how can course contents be shown to him?

If we change the existing implementation, we will have to change the databases and even the existing code in so many ways, which will be very time consuming.
So the simplest solution is that we don't change the existing functionality 

I think the open button functionality should be hidden for the manager if he is not a leader and neither a member of the course. Manager still can see the course contents by using "Manage" button. Manager can also grade the papers and give 
credits to the learners.

In case to make the course contents visible to the Manager, even if he is neither a learner and nor a leader,  we will have to enforce the creation of membercourseprogress document each time a manger is created or a member is promoted to Manager role and we have to do this for each course. It means if there are 10 courses then there will be 10 membercourse progress documents for each Manager even if they are neither learner nor leader.

**Comment by umarWaris** [comment]
If manager is neither a learner nor a leader then Hide "Open" button
