### ISSUE TITLE
Library search: in Arabic language last resources gets displayed off the grid

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#459]
![screen-shot-2016-09-28-at-3 21 51-pm](https://cloud.githubusercontent.com/assets/13684059/18940331/43cd7c98-85d5-11e6-9213-a5f5c36d26ae.png)

**Comment by lmmrssa** [comment]
This is what i'm getting on search result for **rtl layout**. Checked on both _0.12.46_ and _0.12.49_ version.

![rtl_layout](https://cloud.githubusercontent.com/assets/2909490/18997470/35ee06f8-8754-11e6-97cd-988cde1d30da.png)

Could you please re-confirm the issue.

**Comment by dogi** [comment]
hmm not reproducible ;)
