### ISSUE TITLE
Nation: non-manager created resources should be verified by managers

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#461]

**Comment by umarWaris** [comment]
In resources "addedBy" attribute must save the creator's id

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/4a7e18fbc364bf9b94bdeb4dd0dc9500cd13821c

**Comment by dogi** [comment]
the creator should still be able to see, change and delete the resource before the "accept".

after the "accept" the resource is as any other already accepted resource not change- and delete-able

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/a02a8197d3b64188214e5918cef6f2080293d127

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/86b40cc8a61291ca27a691660be4d11d3bfe718f

**Comment by dogi** [comment]
for managers `Local Resources` will be replaced by `Pending Resources` and the Dashboard Button will link to that

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/4cdf01ea136ad6afe05f4cca8ee8987bb8564f97
