### ISSUE TITLE
If a step, which contains both paper and quiz, is completed. It is not indicated in "My Courses Progress"

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#464]
There are three places where this should be corrected.

**Comment by SadiaRasheed** [comment]
1) Dashboard => MyCoursesProgress
![part 1](https://cloud.githubusercontent.com/assets/10362799/19148864/3830f550-8bd8-11e6-8afa-a4a2a84a73d3.PNG)

**Comment by SadiaRasheed** [comment]
2) Courses shown on Dashboard
![part2](https://cloud.githubusercontent.com/assets/10362799/19148887/60021000-8bd8-11e6-971f-9dcc4fc6c077.PNG)

**Comment by SadiaRasheed** [comment]
3) Courses=>Progress
![part 3](https://cloud.githubusercontent.com/assets/10362799/19148897/6c081b6a-8bd8-11e6-9f65-15ba7033cc67.PNG)

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/cf41581ae9c64a2687e619bfc9e4a8573d2af908
