### ISSUE TITLE
Create Multilingual Interface

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#47]

**Comment by dogi** [comment]
- https://en.wikipedia.org/wiki/Modern_Standard_Arabic

**Comment by dogi** [comment]
please suggest a path to get this done.
also split this hole task into tinier issue if necessary
e.g. task of translation, task of json, task of ...

**Comment by SabaBaig** [comment]
https://docs.google.com/document/d/13XJ3QEe0iAEKjmfK2XAkRq6bWh0s_u-Jqtb7lFAwIYo/edit?usp=sharing

**Comment by dogi** [comment]
this issue will get worked on in https://github.com/open-learning-exchange/BeLL-Apps/issues/103
