### ISSUE TITLE
Hide " Open " button for manager

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#484]
If admin is neither a learner nor a leader, Make " Open" button invisible for him

**Comment by SadiaRasheed** [comment]
@dogi : I have assigned this to @umarWaris as he has already worked on this
Solution for Issue#452 as requirement was changed for Open button

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/2216a465c9e9e8d2b12d5351ef1ab9218b3ec5da
