### ISSUE TITLE
Investigate how to remove some of the 404 error on loading time

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#491]
First step here is to make a list of the different errors

**Comment by prajwol5667** [comment]
removed some extra codes and corrected some typo errors  due to  which some 404 errors were occurring .

**Comment by prajwol5667** [comment]
some codes are removed because it is causing file not fond errors

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/cd8ae7abe578c7c995da33819346b56746229c70
https://github.com/open-learning-exchange/BeLL-Apps/commit/0aba0bef7cb145e031cc85dcee47bd4967c4b777
https://github.com/open-learning-exchange/BeLL-Apps/commit/0029636cf8eea21efcba579a0352a24c4ffda0c0
