### ISSUE TITLE
Nation: members page show also members of communities in an editable/deletable way

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#492]

**Comment by lmmrssa** [comment]
@dogi  It seems there is nothing identical in the record to identify is the record from nation itself or from the community. So we might require some identifier to be included to know is the member from nation or community.

**Comment by lmmrssa** [comment]
Figured out the requirements and working out the required changes

**Comment by subashshakya1** [comment]
working on drop down button to fetch data according to it. And also working on search button if the option from drop down is selected.

**Comment by lmmrssa** [comment]
code has been pushed on branch 492-community-members-filter which has the search view update but membersByCommunity view is giving error of invalid json.
So far dropdown and filter on member page has worked.

**Comment by lmmrssa** [comment]
Summary of changes done
- Created the open 'view' for member of all nation and community which will disabled form only to review.
- Added filter for community in case of nation
- Updated the search to work only on the nation/community selected
- Condition for 'Edit' and 'Delete' only for same community/nation
- Update the email address to have the related community/nation code
