### ISSUE TITLE
multiple community publication parallel download are not able to inform nation about success

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#493]

**Comment by umarWaris** [comment]
- Code understanding
- reproducing this issue on my side
- installing vagrant community
- Testing of this Issue
- 1st scenario: when publication is synced on community side, fetch the document "publications" document from nation and get attribute "DownloadedBycommunities" to get latest list of community names and push your community name into this array.
- Publication/for_community
     1) If two communities simultaneously download publication then it leads to "Merge Conflict"
     2) One community downloads publication without refreshing and other community downloads it with refreshing page 
     3) Sequential Downloading of publications. one downloads after other community (Merge conflict)

**Comment by umarWaris** [comment]
a) Simultaneously Download
 1) hit on sync button of both communities
 2) hit on sync button for one community and hit on sync button of other after 
b) refreshing the page
Sequential Download
 1) hit on sync button of both communities
 2) hit on sync button for one community and hit on sync button of other after refreshing the page

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/f7041ff5f92a32d56aca554a50976080403e4722
