### ISSUE TITLE
Add Last Activities Sync Date to Activity Report On Nation For Individual Communities

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#50]

**Comment by SadiaRasheed** [comment]
This task is related to the Reports and can be started right away.

**Comment by SadiaRasheed** [comment]
![issue 50 last activities sync date](https://cloud.githubusercontent.com/assets/10362799/9930565/096ffc98-5d4e-11e5-846a-0015dfb5ab67.PNG)

**Comment by jstearnsw** [comment]
Thank you for the update.
After a team discussion, we would like to change the text from the current format to "Trend Activity Report for xyz Community as of xx/xx/xxxx"

**Comment by SadiaRasheed** [comment]
Okay. I am going to change it right away

**Comment by SadiaRasheed** [comment]
![issue 50 header](https://cloud.githubusercontent.com/assets/10362799/9986074/fe567e4e-6050-11e5-865b-9e16396542b5.PNG)

**Comment by dogi** [comment]
We tested this on 3 different communities with 2 different nations (nations 1 & 4 in the qa process).  The date does not show on the Trend Activity Report  on the nations.



we are a little confused right now because we saw this working before last QA test run ...

**Comment by SadiaRasheed** [comment]
I don't see any problem here as I checked it on http://old.qa.ole.org:5984/ and http://new.qa.ole.org:5985/. Please see the screenshots below.
![newnew](https://cloud.githubusercontent.com/assets/10362799/10217443/23a7dc56-6849-11e5-8e52-738d2c9ef9d5.PNG)
![travel](https://cloud.githubusercontent.com/assets/10362799/10217444/23a9e0e6-6849-11e5-913f-ccb0b9f2c554.PNG)
Moreover I checked it for communities here ta nbs but there is no problem. 
![centigrade](https://cloud.githubusercontent.com/assets/10362799/10217541/fa2218c8-6849-11e5-88e4-f7627326ddb2.PNG)
Please let me know if the problem persists

**Comment by jstearnsw** [comment]
We just tried looking at this again, on the community overview page we don't have this problem (the date shows up), but when we run a report on the first day of a community being active, the date does not show up on the report.  We were eventually able to get the date to show up, but that solution required refreshing the page over a dozen times.  Is there any way to get the date to show up on the report without having to refresh repeatedly?

**Comment by SadiaRasheed** [comment]
What should I do to reproduce this issue? Please write the necessary steps so that I could see this Issue on my Machine and work on it
Or you can show me a demo in Tomorrow's meeting

**Comment by SadiaRasheed** [comment]
Github commit link 
https://github.com/open-learning-exchange/BeLL-Apps/commit/c660de85c56c0c38aae283792f6e99f901caea8d
https://github.com/open-learning-exchange/BeLL-Apps/commit/7fd57b2e0ede1e062e196dfdb57707583e88060c

**Comment by SadiaRasheed** [comment]
I could not reproduce this issue on my side
