### ISSUE TITLE
Community: update of resources design document is not working when was manually fixed

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#502]

**Comment by dogi** [comment]
@lmmrssa is working on a site which will compare the design docs of each database between the community and the regarding nation

**Comment by SadiaRasheed** [comment]
Issue#532 is related to this

**Comment by dogi** [comment]
@lmmrssa 

button should be called `Update Status`

we should also print the number of community dbs -> 38

**Comment by lmmrssa** [comment]
changes done
* added database count
* updated text
* updated style to have rtl for urdu and arabic
* change position of button
