### ISSUE TITLE
Re-submission message should show up to all the leaders

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#505]
Re submission was showing up to one of the leaders which was saved before other
When learner failed a paper, he was able to submit and showed up for submission grade.
Re-submission message of passed paper was not showing up for both of the leaders

**Comment by SadiaRasheed** [comment]
https://docs.google.com/document/d/1aQeYsg-U4yr8TA7bvARAGcrJNY-QBfno-PM-NVgKL1A/edit?usp=sharing

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/5897c72656e86bb0eabf60d683b886b3165870d2

**Comment by SadiaRasheed** [comment]
5897c72
