### ISSUE TITLE
Submission message

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#508]
Submission message
_________________________
          - Leaderless course
            -- Show message to admin/manager
           - Course with leader/Leaders
              -- Show submission message to leader not manager

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/3954954a1d2570782617149fd87c47a733a0a4b3

**Comment by SadiaRasheed** [comment]
3954954
