### ISSUE TITLE
show check mark for paper and 0% for quiz

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#514]
Paper and Quiz step
----------------------------------------
Quiz attempted and got 0 marks. 0% didn’t show up.
Check mark for paper should show up even if the quiz has not been submitted

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/5897c72656e86bb0eabf60d683b886b3165870d2

**Comment by SadiaRasheed** [comment]
5897c72
