### ISSUE TITLE
At Nation, Remove Design Doc in Configurations Database With Both Fresh Install and Update Nation

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#52]

**Comment by MWakas** [comment]
I analyzed this issue.It just needs one file to be changed which is push_nation_design_docs.js in update_nation folder.We will skip the configurations,communities and languages databases as these three databases are skipped in install.js and install_windows.js as well as in install.bat file.It seems it will not take much time.We will do testing after skipping the databases.

**Comment by MWakas** [comment]
This issue has been solved.Here you can find changes in the code on github:
https://github.com/open-learning-exchange/BeLL-Apps/commit/90055fcbc04852a4542db3ea4b97f684561ea9e6
