### ISSUE TITLE
No. of attempts for a step should be saved

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#522]
Number of times a learner attempted a step. The count of number of attempts should be saved

**Comment by SadiaRasheed** [comment]
@dogi : Please add further requirements to this issue if there are any.
Please tell me the complete scenario what you want and where you want me to show these attempts

**Comment by dogi** [comment]
@SadiaRasheed we (mostly Richard) would like to know how often a new paper got submitted and also how often a multiple choice test was done ...
right now we mostly want know just save the attempts

**Comment by SadiaRasheed** [comment]
@dogi : You just want to save the attempts for now?

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/a10a05ae6b912abfd5576ac5501f43e589e71b0c

**Comment by SadiaRasheed** [comment]
@dogi : Right now what it is doing 
 If a learner submits a paper then there is an increment in attempt count even Leader has not graded it.
Is this fine or I need to change it that there should be increment in attempts count  after the leader has graded paper

**Comment by SadiaRasheed** [comment]
![522](https://cloud.githubusercontent.com/assets/10362799/20706860/23289436-b64b-11e6-8a81-f99bd0ebd229.PNG)

**Comment by SadiaRasheed** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/88e88f45b0e4d13200be818834bda81954ed9687
