### ISSUE TITLE
Mark resubmitted papers red

### ISSUE THREAD

**Issue by SadiaRasheed** [open-learning-exchange/BeLL-Apps#525]
Those paper that are resubmitted should be distinguished. Mark them red to show that they need to be re-evaluated.

**Comment by SadiaRasheed** [comment]
@dogi : Please explain via screenshot where I should highlight?
 On Credits page or on Submission's page?

**Comment by umarWaris** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/76b12b485b63e5dd98a5333ea90ddf9c13d30f57
