### ISSUE TITLE
Open’ input section and ‘Upload Date’ input section should be aligned.

### ISSUE THREAD

**Issue by prajwol5667** [open-learning-exchange/BeLL-Apps#527]

**Comment by prajwol5667** [comment]
some misaligned were corrected and when new files are uploaded it will show uploaded file as a notice.

**Comment by dogi** [comment]
last thing to do start all left elements in the same column

**Comment by prajwol5667** [comment]
https://docs.google.com/document/d/142-YUeU8G1d8cAYco28Ss2NPgkpkLGW-6HLpFL0XP7Y/edit
