### ISSUE TITLE
Update buttons on the My Library page on Dashboard

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#54]
Update the location and colors of the "Remove" and "Open" buttons within the My Library Shelf page on the Dashboard.  When a resource has been selected by the member to be added to his/her library shelf and then that resource is opened, there is a Resource Detail page that opens and it has "Remove" and "Open" buttons on it.  However, the locations and colors of the buttons are not intuitive.  Please reverse the location of each button and change the View button to green, make the Remove button gray and make the Remove button smaller.

**Comment by SadiaRasheed** [comment]
Reviewing this

**Comment by SadiaRasheed** [comment]
It has been completed and was included in September 18, 2015 release

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/9e4fded163f5e59b95dc38f537b46347bf832fb2

**Comment by SabaBaig** [comment]
Here are the screen-shots,
For resource, that does not has any attachment with it
![p1](https://cloud.githubusercontent.com/assets/13994879/10015731/8e6a770c-613b-11e5-8fb9-6c037d3a24cd.PNG)
and  for resource, that has some attachment with it.
![p2](https://cloud.githubusercontent.com/assets/13994879/10015760/b3cec476-613b-11e5-84e9-e4ea32cd97dd.PNG)

**Comment by jstearnsw** [comment]
We tried using Linux Firefox and Windows Firefox in both the community and the nation to test this - We had problems finding the green 'View' button, we enlarged the window and saw that the 'View' button was not in line with the rest of the layout. (see screenshot)

**Comment by SabaBaig** [comment]
Github commit link
https://github.com/open-learning-exchange/BeLL-Apps/commit/842271933c5bce1d71faa565ac6aae88887010cf
