### ISSUE TITLE
nav bar radius

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#560]

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/6a0ecf22219c8bf038b798379b460cc28108f9ee

**Comment by dogi** [comment]
@Rupesh87 on nation manger menu there are still radiuses/circles
![67-1](https://cloud.githubusercontent.com/assets/13684059/21010538/92f769d8-bd1a-11e6-83b9-16eced0cc11f.png)

**Comment by Rupesh87** [comment]
nation is running from badges branch so it is not showing the changes @dogi
