### ISSUE TITLE
Meetups in the dashboard is not aligned to center.

### ISSUE THREAD

**Issue by subashshakya1** [open-learning-exchange/BeLL-Apps#565]

**Comment by subashshakya1** [comment]
![alt text](https://raw.githubusercontent.com/subashshakya1/img/master/Capture2.PNG)

**Comment by Rupesh87** [comment]
**Commit Number**
https://github.com/open-learning-exchange/BeLL-Apps/commit/b573bf7c991e681570df8ca294c6564405d55c03

**Changes Done**
* my meetup scroll center
* styling correction

**Comment by dogi** [comment]
![68-2](https://cloud.githubusercontent.com/assets/13684059/21128444/f6af0ad8-c0c8-11e6-9b4a-04a58b265680.png)

please make this awesome fix also work for arabic styled languages ;)
