### ISSUE TITLE
Dashboard: elements of it should also align in Arabic-like languages to the grid

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#569]
![68-1](https://cloud.githubusercontent.com/assets/13684059/21128738/4ec679d4-c0cb-11e6-88e8-5908cd021d10.png)

**Comment by subashshakya1** [comment]
![capture5](https://cloud.githubusercontent.com/assets/16514080/21136774/19657c7a-c14f-11e6-8dc5-5770ce7a738d.PNG)

After the commit. Fixed the elements of dashboard in arabic-like alignment.

**Comment by subashshakya1** [comment]
2dc5d7140f5d864712303d19454c640795a4ebdd
