### ISSUE TITLE
In a leader less course anybody can enroll but they can not leave on their own

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/BeLL-Apps#570]
Member should be able to leave the course on their own (only if the course does not have any leader)

**Comment by prajwol5667** [comment]
![leave](https://cloud.githubusercontent.com/assets/19973606/21301702/07f2ae58-c5d8-11e6-931f-4c0a603e88d1.PNG)

**Comment by lmmrssa** [comment]
There is already the feature to *resign* from leaderless course its just that its location is not visible.
