### ISSUE TITLE
[Meetup] Need 'Never' Recurring option

### ISSUE THREAD

**Issue by waryhermit** [open-learning-exchange/BeLL-Apps#578]
Currently if you select the `Daily` or `Weekly` options there is no way to make it not recurring anymore. There should be a `Never` option so that you don't have to reload the page to select none of them.

![image](https://cloud.githubusercontent.com/assets/5189447/21279036/4d221ec4-c3ac-11e6-9f12-18afedc1cd7e.png)

**Comment by dogi** [comment]
What do you think if we would add an addtitional radio button `None` which is already preselected

**Comment by waryhermit** [comment]
@dogi Yes, that would fix the problem.

**Comment by Pr0chin** [comment]
![issue](https://cloud.githubusercontent.com/assets/24644003/21519060/86c3b434-cd12-11e6-8e15-3d667e85ced7.jpg)
 
Regarding to issue 578 ..I have added label" None" in recurring's checkbox  option as per required.

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/pull/590/files
