### ISSUE TITLE
Cannot cancel on the 'Start a New Meetup - Invite' Screen

### ISSUE THREAD

**Issue by waryhermit** [open-learning-exchange/BeLL-Apps#586]
Steps to reproduce:

- Go to meetups tab
- Click `Add Meetups`
- Fill in the required information
- Click `Save`
- When the pop up window appears, click cancel

**Actual Result:** Instead of canceling, it creates a meetup.
**Expected Result:** Return to the meetup form so you can edit the details.

**Comment by lmmrssa** [comment]
The work flow is as follows
* When _save_ button is clicked it actually save the meetup
* Popup screen is supposed to be only for invitation for Meetup. It does not actually save the meetup after popup, its just the optional step.
* So if someone does not want to invite anyone then just can click the cancel, which is the feature of cancel button.

@dogi  could you confirm the work flow of Meetup setup

**Comment by waryhermit** [comment]
That is a logical workflow, but in my opinion it is not intuitive considering I mistook it for a bug at first. If there is a dialog and you can see a screen behind the dialog I think most people would predict that you would return to the window you can see when you hit cancel. I know I was surprised when I went to a new screen.

**Comment by dogi** [comment]
@waryhermit I kinda feel you there - you are right misleading - but right now I still think your potential solution can be even more simplified ;)

`less = more`

**Comment by lmmrssa** [comment]
@dogi @waryhermit
I feel like we can take the user to the Meetup View page and get them do the invitation over there.
