### ISSUE TITLE
In the new member form, it should not be possible to add invalid dates

### ISSUE THREAD

**Issue by aberdean** [open-learning-exchange/BeLL-Apps#588]
Right now, on the form to become a member, it is possible to insert as date of birth something like 30 February, or 31 November, and so on.
It may be a nice improvement if the app would allow only valid dates.

**Comment by lmmrssa** [comment]
changes done on release [0.12.71](https://github.com/open-learning-exchange/BeLL-Apps/releases/tag/0.12.71)

**Comment by dogi** [comment]
![72-1](https://cloud.githubusercontent.com/assets/13684059/21794331/65b880a8-d6c7-11e6-94a6-54a4a28ec7fa.png)

my favorite date 31 dec 2007 is still not working in become a member dialog

it is also not working on the add a member dialog

**Comment by lmmrssa** [comment]
looks like issue is the local date format so will have to use something that does not depend on local format
