### ISSUE TITLE
Calendar: Add Event button should stay on the designated place

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#591]

**Comment by lmmrssa** [comment]
changes done on release [0.12.71](https://github.com/open-learning-exchange/BeLL-Apps/releases/tag/0.12.71)

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/8e0f6903ec44e30c5c06cf213c039d9ca42d516f
