### ISSUE TITLE
course quiz question section

### ISSUE THREAD

**Issue by Rupesh87** [open-learning-exchange/BeLL-Apps#594]
![fireshot capture 31 - bell myapp__ - http___localhost_5984_apps__design](https://cloud.githubusercontent.com/assets/18145146/21562755/80ebcadc-cea3-11e6-934b-303109c9bacb.jpg)

![fireshot capture 32 - apache couchdb - futon_ view doc_ - http___localhost_5984__utils_document html](https://cloud.githubusercontent.com/assets/18145146/21562758/80f4107a-cea3-11e6-9a2c-c2d4579bd7c2.jpg)
![fireshot capture 34 - apache couchdb - futon_ view doc_ - http___localhost_5984__utils_document html](https://cloud.githubusercontent.com/assets/18145146/21562757/80f2668a-cea3-11e6-98bd-e33229a374ec.jpg)

created view for course quiz question
data saved to coursequestion and coursestep table have new field questionlist where quiz record are saved

**Comment by dogi** [comment]
features|[rupesh](http://rupesh.ole.org)|[pr0chin](http://pr0chin.ole.org)
---|---|---
auto-multiple-choice | | X
no old courses | X |
