### ISSUE TITLE
Create new field to identify resources (i.e., textbook, lesson plan, discussion questions, etc)

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#60]
It would be great if, in addition to indicating the media format of the resource (text, audio, video), we could also select the pedagogical use of the resources, e.g. lesson plan, textbook, activities, exercises discussion questions, etc. This would make selection easier for both the course creator and future student.

**Comment by SadiaRasheed** [comment]
It has been completed and was included in September 18, 2015 release

**Comment by SabaBaig** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/3585f8f30db5b22f3b05b26ddc6ba7aa64d4ea18

**Comment by SabaBaig** [comment]
Here is the screenshot
![p3](https://cloud.githubusercontent.com/assets/13994879/10015879/721c5e98-613c-11e5-8298-697f6edc90fa.PNG)
