### ISSUE TITLE
Nation: make it possible to see data of older months

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#604]
We speak about maybe next view

![72-6](https://cloud.githubusercontent.com/assets/13684059/21835576/062e73fc-d78c-11e6-85da-e643881867e2.png)

but specially about the Reports like this

![72-7](https://cloud.githubusercontent.com/assets/13684059/21835578/0be8e7c8-d78c-11e6-9387-c0be8307bce4.png)

@lmmrssa @Rupesh87 @Pr0chin and @yogenpaneru any suggestion how to do that?

**Comment by lmmrssa** [comment]
@dogi  has converted the current overview of Community request to have filter datepicker when there are communities older than current month only. so it will not show the filter if is new setup.

**Comment by dogi** [comment]
@lmmrssa good job this is the right direction

2 things still need to be done:
- [ ] urls need to be representing an actual date (-1) ;)
- [ ] selector element should only show months and years

**Comment by dogi** [comment]
based on qa test

jan2017 2 vists
dec2016 6 visits
nov2016 11 vistis

data of dec is shown in nov

![75-1](https://cloud.githubusercontent.com/assets/13684059/22236090/5742db12-e1d1-11e6-88e6-3259af4d0bf1.png)

**Comment by dogi** [comment]
@lmmrssa awesome now the functionality works

wonder if we also improve UX
think if we move the "select field" from the left to the right and make it also smaller it would look much better
