### ISSUE TITLE
Request for Manager

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#609]
![76-3](https://cloud.githubusercontent.com/assets/13684059/22453595/e456a4a8-e74d-11e6-87ae-e9e3ab53e569.png)

- [x] add request for `Manager` to this form
- [x] send Email to all Managers
- [x] accepting/decline that as a Manager
- [x] feedback to requestor

**Comment by dogi** [comment]
Awesome basic function works
still some tiny fixes required:
- [x] remove `Request Manager` button from Become a Member form
- [x] Button alignment more "centered"
- [x] also missing feedback to requestors (positive&negative)

keep also `arabic` like languages in mind
![78-1](https://cloud.githubusercontent.com/assets/13684059/22679810/cd9f5036-ecd2-11e6-9791-bf1e567f77e3.png)

**Comment by dogi** [comment]
everything so far requested works ...

but:
- [x] Accept and Reject message should be structured differently
![79-1](https://cloud.githubusercontent.com/assets/13684059/22780612/4c3b08e8-ee8d-11e6-83d5-56a1f1b92265.png)
```
Hi w w,

"message"
```

- [x] brainstorm about requestor and manager different languages
![79-2](https://cloud.githubusercontent.com/assets/13684059/22780754/d4efe334-ee8d-11e6-80fc-3377f63ae778.png)
Can we send the message in preferred language of the person receiving the message?

- [x] fix from right to left languages like `arabic` and `urdu` login 
![79-3](https://cloud.githubusercontent.com/assets/13684059/22780763/dd0eca58-ee8d-11e6-9111-5c4849304b50.png)
**this is release critical**

**Comment by sente** [comment]
How is it ready, and a bug?

**Comment by dogi** [comment]
- [x] Accept and Reject message should be structured differently
![79-1](https://cloud.githubusercontent.com/assets/13684059/22780612/4c3b08e8-ee8d-11e6-83d5-56a1f1b92265.png)
```
Hi w w,

"message"
```
  - [x] additional line between `hi..` and `<message>`

  - [x] Manager Request should also follow same guidelines as `Accept and Reject`
    - [x] missing name
    - [x] missing empty line between messages

**Comment by dogi** [comment]
Congrats @razu9861  @sthasuman @Pr0chin @Rupesh87
