### ISSUE TITLE
Update buttons Add Feedback form when rating a resource

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#61]
When rating a resource, there should be a "Save" button (as there currently is) and a "Save and Add To My Library" button (not there).  The "Save" button should save the rating/feedback with one click (remove the message window that pops up). The "Save and Add To My Library" button should save the rating/feedback and also add the resource to the member's library - these should both be done with one click, instead of several clicks as it is now.  
Also, once either button is pressed, the window is closed and the member is returned to the previous library page that they were on prior to opening the resource.

**Comment by SadiaRasheed** [comment]
It has been completed and was included in September 18, 2015 release

**Comment by MWakas** [comment]
This task is completed.Here is the screenshot: 
![fdbck](https://cloud.githubusercontent.com/assets/10882476/10015499/f643e3b0-6139-11e5-9795-98e0bb6fcb28.png)
