### ISSUE TITLE
Error, Unable to update BeLL Apps to version 0.12.77

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/BeLL-Apps#613]
This happened when I tried to update my local bell instance to  **version 0.12.77** .
![screen shot 2017-02-06 at 11 19 35 am](https://cloud.githubusercontent.com/assets/2836302/22645422/d97b1cd8-ec5e-11e6-950e-95f2052914d1.png)

Since it failed anytime I login, it shows me below after loading my dashboard. Can I reverse the process??
![screen shot 2017-02-06 at 11 19 19 am](https://cloud.githubusercontent.com/assets/2836302/22645485/1e43adbc-ec5f-11e6-9d54-dfbf188b7885.png)

**Comment by dogi** [comment]
￼@leonardmensah I assume in the update process there was a interruption or similar which cause your update to fail ...

**Comment by dogi** [comment]
thanks @leonardmensah to confirm that it was working after that again
