### ISSUE TITLE
Nation and Community: what when I lost my password

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#629]
Please write down some solution scenarios

**Comment by lmmrssa** [comment]
**Model 1: Secret Question**
1. User setup secret answer in profile
2. When user request for password reset question will be asked to provide secret answer
3. Then user will get reset password page

**Model 2: Support Section**
1. User will get the link to ask for support or email address to connect with manager
2. User will follow up with the manager
3. Manager will reset the password and send back the detail to user

**Model 3: Email reset link**
1. Enable email sending feature in the system (possibly **SMTP**)
2. When user request reset password email will be send with code
3. User can then reset password using that email reference

**Model 4: Invisible Character or Hint**
1. User request reset password with Username
2. Part of password is provided like `a******m*****1` or some hint will provided
3. User will have to figure out the password based on this hint

**Comment by dogi** [comment]
@lmmrssa thanks - so far I think about a combination of option 1 and 2

**Comment by lmmrssa** [comment]
As per discussion with @dogi  and @leonardmensah
**Model 2 is the one to be implemented on community**
* Forget Password button on Login page
  * It will send Mail to Admin/manager within system
  * Message will show up on page that will notify request sent and try within certain time period
  * Mark the status in profile that change request is set
* Button on Dashboard that will show how many request for password change
  * It will take to different page where admin can accept or reject request.
  * Accept and reject will change the status of member's reset status
* Auto approval setting
  * In admin there will be config that will set the auto approval duration (0 being no approval and certain number for certain duration)
* User retries login w/o password
  * Even if password is incorrect it will show the message that gives status of the reset request (Accepted/Rejected/Pending) with message
  * If approved it will take to the password reset page to set new password
  * If auto approval enabled and request duration exceed then it will take to reset page considering approved

**Comment by dogi** [comment]
https://cloud.githubusercontent.com/assets/17865137/24983880/47cee3a6-1fa7-11e7-922a-dfac66719521.PNG

**Comment by dogi** [comment]
![106-2](https://cloud.githubusercontent.com/assets/13684059/25698106/8ba71bbc-308b-11e7-9bcf-f2099958386d.PNG)

I would love to you kinda this design

**Comment by dogi** [comment]
ToDo:
- [x] change design to above pic ;)
- [x] remove 8 character limit
- [x] nation is not working
- [x] no extra notification button
- [x] trigger and min input for automatic allow password reset
