### ISSUE TITLE
nation: check/add changing date structure also with viplinks

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#632]

**Comment by nirojdyola** [comment]
![sketch](https://cloud.githubusercontent.com/assets/7495421/23455905/7d156c08-fe99-11e6-86c5-d7a96151e070.png)

Datepicker has been included to filter the list and generate report.

**Comment by dogi** [comment]
@nirojdyola awesome picture

@dogi wonders since `vi.ole.org` still has the old/right code,
what do you needed to do (replicate) to create this awesome picture ;)

**Comment by nirojdyola** [comment]
@dogi changes has been release in [0.12.85](https://github.com/open-learning-exchange/BeLL-Apps/releases/tag/0.12.85) so you can use that code to be merged in vi code base. Or you can update the nation from the new release.

**Comment by dogi** [comment]
It works great ;)

questions:
- [ ] should we create a functions for this and the manager overview
- [ ] in the `generated Request` can we have there this date changing selector


Please start of both an new issue and then close this issue ;)
