### ISSUE TITLE
solve possible regression of travis test

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#633]
travis test of release [0.12.84](https://travis-ci.org/open-learning-exchange/BeLL-Apps/builds/206043089)  and commit before that fail https://saucelabs.com/beta/tests/c4d93119700d443aa8ecb717de1dc5aa/commands#0

Please check what changed there

**Comment by dogi** [comment]
Sorry both links are wrong ...

... but as you can see in https://github.com/open-learning-exchange/BeLL-Apps/commits/dev
it stopped working when we added an additional button in the nation manager menu:

- commit: https://github.com/open-learning-exchange/BeLL-Apps/commit/8ed24fc4b583c9447a69ce4c3925c66ee55764cd
- travis: https://travis-ci.org/open-learning-exchange/BeLL-Apps/builds/206039381
- saucelabs: `Link to test_login:` https://saucelabs.com/jobs/e327dcb6ec234d0c9d1bf54c39084198
`E`

**Comment by waryhermit** [comment]
@dogi The travis logs won't load for me. Have you tried running the tests locally with the dev branch?

**Comment by dogi** [comment]
@waryhermit travis had some problem today

found the error output 
```
File "/home/travis/build/open-learning-exchange/BeLL-Apps/tests/test_publication.py", line 57, in test_login
    WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, "//*[contains(@id, 'code')]")))
```

**Comment by waryhermit** [comment]
The element is not visible, supposedly. Is there any way I can view the `HTML` for that page before and after these changes?

Perhaps adding `driver.execute_script("return arguments[0].scrollIntoView();", input_element)` between line 150 and 151 of `test_publication.py` would fix it.

**Comment by dogi** [comment]
@waryhermit yes there is:
- long way: you install ole--vagrant-nation and update this nation with the right releases https://github.com/open-learning-exchange/BeLL-Apps/releases (before 0.12.83 after 0.12.84)
- short (and temporary) way: you look at http://new.qa.ole.org for after (0.12.84) and at old.qa.ole.org for before (0.12.83)

**Comment by dogi** [comment]
@lmmrssa and @waryhermit if you look inhttps://github.com/open-learning-exchange/BeLL-Apps/commits/633-test 
I added back this `App.Views.GroupRow` and test works again

**Comment by waryhermit** [comment]
@dogi ? That commit seems to be marked as failed to me, but maybe I am confused. 

**Edit:** I ran the build a few times, it worked after a while.

**Comment by waryhermit** [comment]
My pull request also seems to work: https://github.com/open-learning-exchange/BeLL-Apps/pull/635

**Comment by dogi** [comment]
@waryhermit perfect ;)

**Comment by lmmrssa** [comment]
@dogi It seems to pass without that view App.Views.GroupRow on @nirojdyola  last commit
https://travis-ci.org/open-learning-exchange/BeLL-Apps/builds/208073410

**Comment by dogi** [comment]
@lmmrssa yes ;) - @waryhermit fixed the problem and we committed the solution  to BeLL-Apps https://github.com/open-learning-exchange/BeLL-Apps/pull/641
