### ISSUE TITLE
viplinks brainstorm about ways how to get from here to be "logined"

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#636]

**Comment by lmmrssa** [comment]
- We can have the Login button at the top right of the page.
- Also I feel we can have the language switch on the page as all VIP will not be from the native English or native of community language.

**Comment by dogi** [comment]
@lmmrssa language switch - great idea ;)

**Comment by dogi** [comment]
![91-2](https://cloud.githubusercontent.com/assets/13684059/24140890/023945f4-0df8-11e7-91bd-82de22675c4a.png)

**Comment by razu9861** [comment]
![screen shot 2017-03-22 at 10 55 21 am](https://cloud.githubusercontent.com/assets/24647983/24183093/1c573b2a-0eee-11e7-8e01-f7efd7b407cf.png)

**Comment by dogi** [comment]
@razu9861 thanks for the pictures
