### ISSUE TITLE
Filter generate report

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/BeLL-Apps#637]
In the page of report of community, need to have the filter of date

**Comment by nirojdyola** [comment]
![activityreport](https://cloud.githubusercontent.com/assets/7495421/23542719/dda43242-0016-11e7-8c40-2ee2a8bddad4.png)

Added datepicker to generate report.

**Comment by dogi** [comment]
@nirojdyola generally good job
think that first graph is broken,
but the four other seam to work

ToDo:

- [ ] create new issue to fix first graph
- [ ] create also an issue for a nice test data sample which we all share (something between vi and somaliabell)
