### ISSUE TITLE
takehome: update design document of resources

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/BeLL-Apps#651]
So far I have this filter in a design/apps document
```json
{
   "_id": "_design/apps",
   "_rev": "1-a5b4fff49618e88e026c8d4216d96901",
   "filters": {
       "by_resource": "function(doc, req){return doc._id === req.query._id;}"
   }
}
```
We want to get it rather into `_design/bell` document under resources database.

**Comment by lmmrssa** [comment]
pull request created with design doc filter in it. https://github.com/open-learning-exchange/BeLL-Apps/pull/654
