### ISSUE TITLE
remove 404 javascripts

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#666]
![91-3](https://cloud.githubusercontent.com/assets/13684059/24141278/5c6f469e-0df9-11e7-9b49-38ea269feae3.png)

**Comment by sarvanivadali** [comment]
Re-purposing this issue to fix the following 404 issues in nation instead:

![image](https://cloud.githubusercontent.com/assets/8753852/24421245/90b31b18-13c3-11e7-8db6-e187a3be5234.png)
