### ISSUE TITLE
Update on UI of Course feature

### ISSUE THREAD

**Issue by Rupesh87** [open-learning-exchange/BeLL-Apps#694]

**Comment by Rupesh87** [comment]
[] Take test button fix.

**Comment by lmmrssa** [comment]
- [x] Remove 'Submit Credit' button from review
- [x] Add 'Back' button on Test edit
- [ ] Fix buttons on 'Test'. Change Next to 'Finish' and rename 'Exit' to 'Leave Test'
- [x] Update dialog message of Review and Test
- [x] Fix 'undefined' text in Progress graph
