### ISSUE TITLE
Typo: Dashboard-My Library-open resource-text

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#72]
From the Dashboard, click on "My Library", then open any resource and under "Resource Detail' the word "Attachment" is spelled with an extra "e":  Attachement

![screen shot 2015-07-21 at 2 30 31 pm](https://cloud.githubusercontent.com/assets/7746327/8809202/1966904c-2fb5-11e5-8549-b9feaa9aa139.png)

**Comment by MWakas** [comment]
The issue has been resolved.You can find changes here in the github:
https://github.com/open-learning-exchange/BeLL-Apps/commit/f1c99fd6d467ffc2b0bc020469535b8905c2a412
Here is the screenshot:
![add-to-my-library](https://cloud.githubusercontent.com/assets/10882476/9755696/846a1a6c-56ed-11e5-9b11-8af02d8bcf09.PNG)
