### ISSUE TITLE
Test Setup ViewOnly

### ISSUE THREAD

**Issue by Rupesh87** [open-learning-exchange/BeLL-Apps#721]
view test button while will show questions as take test in step view detail

**Comment by dogi** [comment]
@Rupesh87 can you explain more about this issue? cause so far it is a little bit cryptic

**Comment by Rupesh87** [comment]
![capturee](https://cloud.githubusercontent.com/assets/18145146/24743816/69533c48-1acf-11e7-92f9-37aeca4170ab.PNG)
it will show question list as take test for manager in step view detail
