### ISSUE TITLE
Typo: Nation BeLL name

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#73]
The first three letters of a nation bell get cutoff when the admin clicks on Manager:

![screen shot 2015-07-21 at 2 38 53 pm](https://cloud.githubusercontent.com/assets/7746327/8809396/61c7a7bc-2fb6-11e5-826b-70f84fd83549.png)

![screen shot 2015-07-21 at 2 44 15 pm](https://cloud.githubusercontent.com/assets/7746327/8809500/05dd0284-2fb7-11e5-90c3-5d51743aa0f7.png)

**Comment by MWakas** [comment]
This issue has been resolved.You can find changes in the code right here:
https://github.com/open-learning-exchange/BeLL-Apps/commit/8b167acb4c6a98f1111477d0d2d7fa0ef6660635
Here is the screenshot after resolving the issue:
![nation_name](https://cloud.githubusercontent.com/assets/10882476/9755564/6bc93d2c-56ec-11e5-8371-dce9a9b89ba9.png)

**Comment by dogi** [comment]
both titles (overall and manger) should be driven by the same code

**Comment by MWakas** [comment]
The names are now same at every place.Here are the screenshots:
![gnrl](https://cloud.githubusercontent.com/assets/10882476/9816478/b7c8052a-58b6-11e5-84bf-04a3448b504d.png)
![mgr](https://cloud.githubusercontent.com/assets/10882476/9816479/b7cc4202-58b6-11e5-98eb-abd060b1919e.png)

And here you can find changes in the code:
https://github.com/open-learning-exchange/BeLL-Apps/commit/7d55e2700bbeccefdf9547f640895168eacfb624

**Comment by jstearnsw** [comment]
name should come out of configuration not from url

**Comment by jstearnsw** [comment]
Following our [QA](https://docs.google.com/document/d/1p9ngaliC8h5mxCRWXi7IEb-SqDMV4RFbBgtcND4K0pc/edit) document, this solution only worked on 1 and 2, but not on 3.  Since it did not work on 3, we did not test further.

**Comment by dogi** [comment]
thanks to a not finished fix of https://github.com/open-learning-exchange/BeLL-Apps/issues/95 you not able to see it ... with tampering or luck I got to see it working on a successful on 6
