### ISSUE TITLE
VIP hide delete button if not logged in

### ISSUE THREAD

**Issue by razu9861** [open-learning-exchange/BeLL-Apps#735]

**Comment by dogi** [comment]
Keep in mind there are 3 different kinds of communities showing up in that view:
- registered community [no edit and delete button] 
- aspiring community [if click on view button then no reject or accept button next view]
- old style community (needs still to update to the `center` way) [no delete button]

**Comment by dogi** [comment]
![101-3](https://cloud.githubusercontent.com/assets/13684059/25128375/89735e0e-2407-11e7-899f-54e7ffb912a0.png)

@razu9861 as you can see something went wrong ;)

**Comment by razu9861** [comment]
@dogi which version is old community,

**Comment by dogi** [comment]
both I mean nation and community are version 0.12.101 even in the picture is written 0.12.102

**Comment by dogi** [comment]
the main error is that it shows it as it was an old community even as you can see in the top picture that is just a normal one ...

**Comment by dogi** [comment]
@razu9861 awesome - delete button is gone
unfortunately also `View Details` button disappeared  with it  ;)
please fix that
