### ISSUE TITLE
Error: Login already exists

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#75]
On the community: tried to create two new members by using the Become A Member button on the login page. The first member was created successfully. Tried creating the second member immediately after creating the first member (without logging in as any member) but received this error:
![login_already_exists](https://cloud.githubusercontent.com/assets/7746327/8812585/eda7c23a-2fca-11e5-9d78-a27a56722627.JPG)

After logging in as the admin (to confirm there was no member with those credentials) and then logging out, we were able to successfully create the member with the original credentials. 

We were not able to reproduce on v0.11.54

**Comment by MWakas** [comment]
The issue has been resolved.Here you can find changes on Github:
https://github.com/open-learning-exchange/BeLL-Apps/commit/10c9d9b7082f3c45a49b1aa4aa6b93ba4bbe5df8
