### ISSUE TITLE
UnAccepted community should not request nation

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/BeLL-Apps#761]
Community which are not approved from nation should not try to get data from nation.
Things should not be there.
* check for update
* sync with nation or option to sync
* receive publication or any resources

**Comment by dogi** [comment]
![101-8](https://cloud.githubusercontent.com/assets/13684059/25229791/9eaf6f80-259f-11e7-980a-902bd41d34c3.png)

**Comment by dogi** [comment]
![106-2](https://cloud.githubusercontent.com/assets/13684059/25697708/0332778c-308a-11e7-91d1-137cebb39765.png)

`Nation not visible` should be `waiting for registration`
