### ISSUE TITLE
Progress Detail static error

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/BeLL-Apps#762]
Badges detail page does not seem to be working properly.
It is showing /100  or  just % and also the total is not being calculated appropriately.

**Comment by dogi** [comment]
![101-7](https://cloud.githubusercontent.com/assets/13684059/25229887/108bef66-25a0-11e7-8986-fdfb6d7ef866.png)

**Comment by Pr0chin** [comment]
![badges](https://cloud.githubusercontent.com/assets/24644003/25372252/5bb8cf14-29b4-11e7-834e-d5f23a51c263.PNG)

**Comment by dogi** [comment]
@Pr0chin thanks

Can you add link for PR?
