### ISSUE TITLE
Problems with Subject in Library

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#77]
While adding the resources.couch files provided by Waqas (July 31) from his and Sadia's local QA machines, we noticed the following:
- We only copied the resources.couch files and noticed that some of the Subject fields used by Waqas and Sadia were not in our library. We were not able to select those new subjects in order to add the new resources to a publication. We also did not know how to add those new subjects to our current library. Which database is the Subject field located in?

Here you see that the subject "Environment" is identified in the resource on the left but there is no "Environment" subject when the search is conducted:
![error_subject_environment](https://cloud.githubusercontent.com/assets/7746327/9012575/f807889e-3783-11e5-93d4-4b363aacde39.JPG)

**Comment by MWakas** [comment]
I noted this issue and updated the "drop-down lists" on "search page" as well as on the "add new resource" page.Now all the "subject drop-down lists" have same number of subjects and same format as well.Here are the screenshots:
![res_subject](https://cloud.githubusercontent.com/assets/10882476/9518455/45f38ec0-4cd0-11e5-8ea8-d43ba93ee99f.PNG)
![search_sub](https://cloud.githubusercontent.com/assets/10882476/9518456/45fa3a86-4cd0-11e5-8d41-304027647d39.PNG)
