### ISSUE TITLE
Change document ranking within search results

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#78]
Decide how the search results should be ordered - they are currently (v0.11.55) sorted alphabetically. One solution is to order the results by most relevant. Example when searching for "women health":
- first results would show the resources that contain both keywords adjacent (i.e., "everything about women health")
- next results would show resources that contain both keywords that are not adjacent (i.e., "health for women")

- need to decide how single words will be returned when multiple words are searched - maybe they show up at the end of the search when two words are searched but not when three or more words are searched since that will produce numerous results?

**Comment by MWakas** [comment]
This issue was resolved and results were ordered by most relevant.It was related to search functionality, so i think it should not be in backlog.
