### ISSUE TITLE
Add Report button on the Communities page at nation

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#80]
When logged into nation as a manager and on the Communities page:
Add green report button to the left of Edit button (still under Actions header) on the Communities page. When this button is clicked, it generates the same Trend Activity Report graphs, facts and figures that get generated through the Reports-->Trend Activity Report-->Select Community-->Generate Report.  The goal with this button is to cut down on the number of clicks needed to view each community report.

**Comment by SadiaRasheed** [comment]
I have added a green report button here.
![issue80](https://cloud.githubusercontent.com/assets/10362799/9787806/166c2a3a-57df-11e5-9aed-c01a1d522bae.PNG)
Functionality behind this button is needed to be implemented.

**Comment by SadiaRasheed** [comment]
git hub link for this task
https://github.com/open-learning-exchange/BeLL-Apps/commit/e8fd77e2244c311eb7201e4ab397c25d5e904932

**Comment by SadiaRasheed** [comment]
Some screenshots for this task
![issue 80final](https://cloud.githubusercontent.com/assets/10362799/9875133/23257a3a-5bc5-11e5-8260-88844aba85ce.PNG)
![issue 80graph2](https://cloud.githubusercontent.com/assets/10362799/9875134/27decbf8-5bc5-11e5-937a-3a38e8851f29.PNG)
