### ISSUE TITLE
Change trend activity report graph titles and rearrange graphs

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#81]
- change graph title: "Total Members" to "Total Registered Members Past 12 Months"
- change graph title: "Total Visits" to "Total Visits Past 12 Months"
- move graph: "Total Registered Members Past 12 Months" to be located above "Total Visits Past 12 Months"

**Comment by SadiaRasheed** [comment]
Completed
![issue 81](https://cloud.githubusercontent.com/assets/10362799/9785573/b9f59870-57cc-11e5-93c9-20edfada3d31.PNG)

**Comment by SadiaRasheed** [comment]
Here you can find the commit for this Issue on Community level:
https://github.com/open-learning-exchange/BeLL-Apps/commit/b63a71b618d3e9bd8640e174b2d7e3e392b67937
At Nation Level:
https://github.com/open-learning-exchange/BeLL-Apps/commit/033c8a7c196c604810a40e26f4a73291c775c7d3

**Comment by jstearnsw** [comment]
Update works on QA process 1 & 3, but not 2. The updated graph titles do not show up on an old community that has been updated to the new version.

**Comment by dogi** [comment]
there is an interference with https://github.com/open-learning-exchange/BeLL-Apps/issues/95
-> I put this issue back to QA
