### ISSUE TITLE
Update trend activity report graph data to reflect graph titles

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#82]
- the "Active Members This Month" graph does not show the correct information - it is currently showing cumulative data but should only show data for the month
- make sure the code for the "Total Visits Past 12 Months" graph should reflect the title (i.e., months beyond 12 months are cutoff)
- code for the "Total Registered Members Past 12 Months" graph should reflect the title (i.e., months beyond 12 months are cutoff)

**Comment by SadiaRasheed** [comment]
1-the "Active Members This Month" graph does not show the correct information - it is currently showing cumulative data but should only show data for the month:

This is not an issue. It is the required functionality that we have implemented. please see the below screenshots
I had four members in my database i.e., 2 males and 2 females. Graphs looked like this
![reports issue1](https://cloud.githubusercontent.com/assets/10362799/9781157/ac57d524-57aa-11e5-98a7-a15341c38db0.png)
Then I deleted a member.
![reports issue 1-delete member](https://cloud.githubusercontent.com/assets/10362799/9781184/da022060-57aa-11e5-8428-b1912b4a29bd.png)
Only three members left as you can see in the above screenshot. Now if we see the graphs then we can easily differentiate that these two graph are not serving the same purpose
![reports issue 1 - graphs](https://cloud.githubusercontent.com/assets/10362799/9781209/1fd9c4e4-57ab-11e5-94e6-14a1ce294bca.png)
The "Total Members Graph" show the number of members that exist in members db excluding the deleted members while "Active Members This Month graph" show the total number of members that have been active in a specific month including the deleted members.

**Comment by SadiaRasheed** [comment]
Reviewing the other two issues

**Comment by SadiaRasheed** [comment]
Could you please attach screen shots for the second and third point to make them more understandable

**Comment by SadiaRasheed** [comment]
Active Member This Month showing the data only for the month
![issue 82-part1](https://cloud.githubusercontent.com/assets/10362799/9811041/43eb48b0-588e-11e5-90bc-bcfed4af9b71.png)

**Comment by SadiaRasheed** [comment]
Some Correction in Total count :
![issue 82-part1-total](https://cloud.githubusercontent.com/assets/10362799/9812489/233a91bc-5897-11e5-99af-3542829703bc.png)

**Comment by dogi** [comment]
Decided that bullet points 2 and 3 will be handled an other time

**Comment by SadiaRasheed** [comment]
Thanks.



*Sadia Rasheed | *Software Engineer | *NorthBay Solutions (Pvt.) Ltd.*

Address: 410 G4, Johar Town, Lahore.
sadia.rasheed@northbaysolutions.net
www.northbaysolutions.com
