### ISSUE TITLE
Take test status fails while giving Multiple choice answer

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#820]
For multiple choice question or objective question. Test should be Auto-Reviewed

**Comment by Pr0chin** [comment]
![capture](https://cloud.githubusercontent.com/assets/24644003/26234129/f99bb720-3c81-11e7-84d0-96eb0d08498a.PNG)

**Comment by dogi** [comment]
@Pr0chin did this issue already get fixed?

**Comment by Pr0chin** [comment]
yes @dogi  :D
