### ISSUE TITLE
Courses: Change functionality of instruction button

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#830]
attachment functionality should be replaced by text.

**Comment by Pr0chin** [comment]
![bell mya](https://cloud.githubusercontent.com/assets/24644003/26482744/db5a14d2-4208-11e7-9252-c1c0e86084d3.png)

**Comment by Pr0chin** [comment]
![capture](https://cloud.githubusercontent.com/assets/24644003/26539812/098f5fbc-446e-11e7-8c8b-99ee3ae3cdea.PNG)

**Comment by Pr0chin** [comment]
![capture1](https://cloud.githubusercontent.com/assets/24644003/26539820/109874ce-446e-11e7-983d-d8619343766b.PNG)
![capture3](https://cloud.githubusercontent.com/assets/24644003/26539819/10918ccc-446e-11e7-88cb-9b167df89d76.PNG)

**Comment by Pr0chin** [comment]
@dogi  is this the stuff that u have mentioned in the issue :D

**Comment by dogi** [comment]
@razu9861 and @Pr0chin as discussed in the team meeting I convinced Richard to completely remove the instruction button/dialog/textfield ...
