### ISSUE TITLE
Nation: introduce region on manager menu

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#834]

**Comment by Pr0chin** [comment]
![capture](https://cloud.githubusercontent.com/assets/24644003/26537108/4239f0c8-445c-11e7-86c0-2b32929ec959.PNG)

**Comment by Pr0chin** [comment]
or else you can send some snap shot @dogi :D

**Comment by dogi** [comment]
@Pr0chin please fix this as discussed in the meeting ;)
