### ISSUE TITLE
Course:  Text-area's Description formatting

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/BeLL-Apps#839]
![moodle1](https://cloud.githubusercontent.com/assets/2836302/26569718/618144ee-44da-11e7-9933-1c7ac40b53a4.PNG)

Make Textarea should give users chance to format text.i.e, Bold, Italics, Underline, Billeting / Listing etc.

**Comment by dogi** [comment]
@leonardmensah awesome suggestion - we should run it by Richard

**Comment by Rupesh87** [comment]
List of content to change
[] -

**Comment by Rupesh87** [comment]
[] List of content to change

**Comment by Rupesh87** [comment]
List of content to be change
- [x] Add Course Description, Manage Course Description, View Course Detail
- [x] Add Step Description, view details step Description
- [x] Creating Step Question
- [x] Take test (comment/essay)
- [x] Email
- [x] Feedback(textarea)
- [x] Add Meetup/Edit Meetup 
- [x] Add Resource (Add Collection Description)
- [x] Survey Add Question
