### ISSUE TITLE
Fill in blank resource title name(s) in trend activity report Facts & Figures

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#84]
When a resource is available in a community but not in the nation and then the community syncs activities with the nation, the resource title does not get carried over to the nation in the trend activity report - it is just a blank, see example from Kibera below:

![error_resource_title_blank_reports](https://cloud.githubusercontent.com/assets/7746327/9068199/fc9a2be4-3aaf-11e5-90c9-ff8a745fd407.JPG)

**Comment by SadiaRasheed** [comment]
This task can  also be started.

**Comment by SadiaRasheed** [comment]
Reviewing this

**Comment by SadiaRasheed** [comment]
-At Community Level:  need to add resources name attribute in activity log database
- need to make changes in daily log views, routers and models related to activity logs
-need to save opened resource name in activity log database
-While syncing the activity log reports with nation, resources names needs to be sent with reports 
-At nation level: need to access the resource name and display it in trend activity report facts and figures

**Comment by SadiaRasheed** [comment]
I have added an attribute for resources names in activityLog database. now I need to save resources names

**Comment by SadiaRasheed** [comment]
Sub Task #1: Adding attribute (resources_names) to Activity Log database
Sub Task#2: Saving names of resources to (resources_names) attribute of Activity Log database
Sub Task#3: Sending resources names to nation in syncing process
Sub Task#4: Get Community-resources names at nation and display it in trend activity report facts and figures

**Comment by SadiaRasheed** [comment]
Here is the screenshot for Centigrade community facts and Figures at Nbsbell 
![issue 84](https://cloud.githubusercontent.com/assets/10362799/10193493/eb78d670-679c-11e5-900f-645fe7825201.png)

**Comment by SadiaRasheed** [comment]
Github commit link
https://github.com/open-learning-exchange/BeLL-Apps/commit/0beeca78ab177bc2a250b87e43d591e2786fff1c
https://github.com/open-learning-exchange/BeLL-Apps/commit/6e52e6984d27bd03f2597fba64b56959b8973842
