### ISSUE TITLE
Nation: Fix AutoAccept

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#848]

**Comment by Pr0chin** [comment]
![113-2](https://user-images.githubusercontent.com/24644003/26862606-730b73e0-4b6c-11e7-8201-cebc9bc8ff26.png)

**Comment by Pr0chin** [comment]
![1](https://user-images.githubusercontent.com/24644003/26862944-dc973ad6-4b6e-11e7-909f-b22aec8a6d3f.PNG)

**Comment by lmmrssa** [comment]
duplicate #736
