### ISSUE TITLE
Search Error: Missing resources with keyword search "ole"

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#86]
- When searching for "ole" (without quotes) on the community with v0.11.56, the results were unexpected (i.e., some resources were missing that should have been there):
![error_search_ole_missing_resources](https://cloud.githubusercontent.com/assets/7746327/9072985/7f2f30b0-3acc-11e5-83b5-9ffb2a74aa63.JPG)

**Comment by jpierce7** [comment]
This problem appears to be associated with when the resources were added to a new publication at the nation level - when all of the subject boxes were selected (which should theoretically be selecting all resources in the library because all resources are required to have a subject), it looks like not all of the resources were truly selected.  So this is not a problem with the community level search. Refer to https://github.com/open-learning-exchange/BeLL-Apps/issues/85

**Comment by MWakas** [comment]
The above comment is related to the issue#85,please check it.
