### ISSUE TITLE
Add resource to course step

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#862]
The process should be easy to navigate like..
- I click on add resource
- I get a dialogue with the search page
- I select the search variables
- I click on search and I am presented a table in the dialogue with the list of resources

**Comment by Pr0chin** [comment]
![june13_4_courses_2](https://user-images.githubusercontent.com/24644003/27115573-52458a22-50eb-11e7-92a2-1566b5595008.PNG)

**Comment by Pr0chin** [comment]
![june13_4_courses](https://user-images.githubusercontent.com/24644003/27115581-5f95e7ee-50eb-11e7-90c6-b5aabc124666.PNG)

**Comment by razu9861** [comment]
- [x] click Add Show Popup
- [x] Show Search Option on Popup
- [x] search by function working
- [x] check box are functional
- [x] back/Add/next button functional
- [x] PR created
