### ISSUE TITLE
Nation: Member Menu-Link is not clickable

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#886]
- In Nation: in Member Part Link is not clickable

**Comment by Pr0chin** [comment]
<img width="563" alt="screen-shot-2017-06-19-at-11 41 31-pm" src="https://user-images.githubusercontent.com/24644003/27324924-71bcf270-55c6-11e7-9533-17535e51777d.png">

**Comment by Pr0chin** [comment]
<img width="210" alt="screen-shot-2017-06-19-at-11 41 47-pm" src="https://user-images.githubusercontent.com/24644003/27324931-794b7764-55c6-11e7-9e3d-00a96a20345e.png">

**Comment by nirojdyola** [comment]
![memberlink.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58aeb9eb257d931a000df4b2/125516c66e82c728ace21e0d46e59197218791a586e7b401e81fe086264c22703d46f96925d0e67fb9472b59585849a8400b5f11fcf98b7df0b73d75984019af80330b2b9b645bf9fa9015ad03bc2a8a4b8cbebd8b48c3ee3524ee899d02.png)

 Link has been fixed.
 Underline the digit where the page is.
