### ISSUE TITLE
Courses: display resources in tabular format

### ISSUE THREAD

**Issue by razu9861** [open-learning-exchange/BeLL-Apps#888]

**Comment by razu9861** [comment]
Example: 
![screen shot 2017-06-21 at 9 57 44 am](https://user-images.githubusercontent.com/24647983/27366816-34669c12-5668-11e7-809e-402adcd2ea29.png)

**Comment by nirojdyola** [comment]
Before :
![Table.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58aeb9eb257d931a000df4b2/125516c66e82c728ace21e0d46dc95982f87c1e5cdf9ad4cae58f3806b1c65267c01f42d75d5bb7fe8152f500c5f1bac415a0912fdf88c39baa47e21d40854b088270a36d43703aebe881ebb08b2248d4681b5b48d4ac7fa70.png)

After changing style :
![table1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58aeb9eb257d931a000df4b2/125516c66e82c728ace21e0d46fc95982f87d2ebc3abaf51ab57f5973d047d317c51a67c7680b370e8152c555e0c4ef941585d12aaf8882eb4aa2e32db025fb28c341521842f1bbeba8415be05b3288f498cb2b98d4bc0ee2f68.png)
![table2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58aeb9eb257d931a000df4b2/125516c66e82c728ace21e0d46fc95982f87d1ebc3abaf51ab57f5973d047d317c51a67c7680b370e8152c555e0c4ef941585d12aaf8882eb4aa2e32db025fb28c341521842f1bbeba8415be05b3288f498cb2ba834dc4ee2f68.png)

**Comment by Pr0chin** [comment]
![addresource.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5860f49dee006e0e0082488f/125516c66e82c728ace21e0d46e9909e318790a69afbbc46e611b2843b492d762a10e17132d0b62de8447e51575849ab45590c44a9f98929f0e03d718f4e17ff933c0120996048e6edc00db513b921814e81bfb48d45c9e03c23e6838a5d73.png)
