### ISSUE TITLE
Course Creation - Quiz - Multiple Choice

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/BeLL-Apps#893]
<img width="1631" alt="screen shot 2017-06-23 at 6 40 09 am" src="https://user-images.githubusercontent.com/2836302/27478728-e4e86a94-57de-11e7-9531-e5f6f4d1dbf0.png">
When a course is created and quiz is added by entering question and multiple options, after selecting the right answer and saving, when quiz is displayed (On top of the screen) with options entered, **the correct answer selected is not bolden / highlighted /emphasized /clearly indicated**.

**Comment by Pr0chin** [comment]
- [x] Made bold for Correct answer/s .
- [x] Put tick mark icon for correct  answer/s.
- [x] Completed Task.
