### ISSUE TITLE
Learners should not be able to  edit question textfield in essay test

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/BeLL-Apps#894]
<img width="1424" alt="screen shot 2017-06-23 at 6 42 57 am" src="https://user-images.githubusercontent.com/2836302/27479004-f03713e0-57df-11e7-85fd-56f62480313e.png">
When learners are taking a quiz / test, they are able to edit the essay TextArea which shouldn't be editable for learners. Although they cant save / replace the question, the **Textarea shouldn't be editable**

**Comment by Pr0chin** [comment]
Text area has been removed .. @leonardmensah  you need to update your environment 👍 😄
