### ISSUE TITLE
Nation: Manager(Communities is broken)

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#900]
Data is broken.

**Comment by Pr0chin** [comment]
![4-1](https://user-images.githubusercontent.com/24644003/27620078-d6755fc4-5be6-11e7-9b3d-703ae0aca08c.png)

**Comment by Pr0chin** [comment]
![4-4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5860f49dee006e0e0082488f/125516c66e82c728ace21e0d46bcd9ce61cec1b99de6b546a749b2ce6b1372767e02a67b28d2b47feb1378510a5f4eae170e5e45f9eb9539e4e76224d50152a7842f4d7ed43f17a6b98616b707b822824d82beba885e8d.png)

**Comment by dogi** [comment]
@Pr0chin @lmmrssa @nirojdyola this phenomenon only happens in Chrome

**Comment by lmmrssa** [comment]
@dogi so shall we leave this request as we only prefer firefox?

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/issues/961 close due duplicate
