### ISSUE TITLE
Course:edit step merge into parent dialog

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#902]

**Comment by Pr0chin** [comment]
![2-3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5860f49dee006e0e0082488f/125516c66e82c728ace21e0d46bad9c961cec1b99de6b546a749b2ce6b1372767e02a67b28d2b47feb1378510a5f4eae170e5e45f9eb9539e4e76224d50152a7842f4d7ed43f17a6b98616b707b823884a80b2ba8b5e8d.png)

**Comment by Rupesh87** [comment]
![capture](https://user-images.githubusercontent.com/18145146/27678416-d9d23f04-5cd4-11e7-9818-802331c5e95e.PNG)
