### ISSUE TITLE
Search Error: Old resources are "invisible" to new search feature

### ISSUE THREAD

**Issue by jpierce7** [open-learning-exchange/BeLL-Apps#91]
On a community (v0.11.57), we are not able to use the updated search features to search for old content that is in the BeLL.  We "implanted" the resources.couch file that we used on the nation (via stopping couchdb, replacing file, restarting) and did not have success.  We then uploaded new resources by using the usual library form interface and then also tried adding a new document in the _utils interface, and we WERE successful with searching for those resources.   We then had a nation with v0.11.52 and successfully searched old resources but after updating to v0.11.57, the searching was broken - this makes the nation update a no-go since all of our resources in the BeLLs would not be "visible" to the new search features.

**Comment by dogi** [comment]
similar to [issue #90](https://github.com/open-learning-exchange/BeLL-Apps/issues/90)
