### ISSUE TITLE
Search is not triggered by enter key

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#93]

**Comment by jstearnsw** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/issues/39

Similar problem was solved already here

**Comment by MWakas** [comment]
This issue has been resolved.Here you can find changes in the code on Github:
https://github.com/open-learning-exchange/BeLL-Apps/commit/63bc1728ac9b8b14ff8f946185b2e4039143366f
