### ISSUE TITLE
Strange behavior after logout

### ISSUE THREAD

**Issue by jstearnsw** [open-learning-exchange/BeLL-Apps#94]
For both Nation and Community BeLLs - After logging out the screen flashes twice before getting to the login screen.  It looks similar to loading the app for the first time.  I think everything gets loaded twice.

**Comment by MWakas** [comment]
Issue has been fixed.The changes in the code can be found here: 
https://github.com/open-learning-exchange/BeLL-Apps/commit/8c2660d5696c1042c7607d2847d1712737a6cd7e
