### ISSUE TITLE
Add Community is not handling the LeaderEmail right

### ISSUE THREAD

**Issue by dogi** [open-learning-exchange/BeLL-Apps#98]
everytime Community gets edited it forgets to put LeaderEmail into the Form

**Comment by jstearnsw** [comment]
Please leave a comment with how you solved this issue.  eg - link of commit

**Comment by jstearnsw** [comment]
https://github.com/open-learning-exchange/BeLL-Apps/commit/6356597f71640ff553886a44633b703594c6fabb done
