### ISSUE TITLE
Set Auto-publication button on existing publication issue and overview page.

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#995]
both ways
- [ ] turn off when autopublication is on
- [ ] reverse

**Comment by Rupesh87** [comment]
![15-1](https://user-images.githubusercontent.com/18145146/29709982-3f191648-89ae-11e7-97f2-dcfafeceec8b.png)
![15-7](https://user-images.githubusercontent.com/18145146/29709981-3f190a04-89ae-11e7-8c48-5ffe8ba33bbf.png)

**Comment by Pr0chin** [comment]
- [ ] Both places need turn on and/or off for autopublication
