### ISSUE TITLE
Markdown :  Remove button which create HTML like <strike>

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#996]

**Comment by Rupesh87** [comment]
![15-4](https://user-images.githubusercontent.com/18145146/29710107-b44edd94-89ae-11e7-8c9d-be8f84866646.png)
![15-3](https://user-images.githubusercontent.com/18145146/29710106-b44c9b42-89ae-11e7-84b6-935ec404c4e1.png)
