### ISSUE TITLE
Publication: Auto- Publication crashes

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#997]

**Comment by Rupesh87** [comment]
![15-8](https://user-images.githubusercontent.com/18145146/29710183-01d4977a-89af-11e7-9ef3-de911d174916.png)
![15-9](https://user-images.githubusercontent.com/18145146/29710182-01d09990-89af-11e7-90af-4e861779debb.png)
![15-10](https://user-images.githubusercontent.com/18145146/29710184-01d5f390-89af-11e7-9553-71e1517f006d.png)

**Comment by dogi** [comment]
@Pr0chin why did you move 2nd highest issue of the week into QA without any notice ...

**Comment by dogi** [comment]
Anyhow also in version `0.13.16` autoregister and autopublish in combination are still crashing ...

![16-3](https://user-images.githubusercontent.com/13684059/29839978-573fb1c8-8cce-11e7-9cb4-a412913bd7b9.png)

**Comment by Pr0chin** [comment]
![a.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5860f49dee006e0e0082488f/125516c66e82c728ace21e0d46e9d6d6619291a685ecbc57e607b2c17c4370752c54fb7c27d2b779bc127e515f5d18fa40595a56e0ebcb7af8e2632dd3165eafc3674d75cf3710a9b8861fb700b3268d4787b5aec7.png)

**Comment by Pr0chin** [comment]
- [x] Combination of auto register and auto publication is ending in an infinite loop (linux) - manual stop - 192 publication instead of 2

**Comment by Pr0chin** [comment]
@dogi  We tested and fixed bugs me and Rupesh. We can check it while having meeting.
