### ISSUE TITLE
Course :  Test not saved and not able to review test

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#998]
- [ ] courses which was created on nation was not able to be done not saved on community
- [ ] reviewing on nation of courses was also not a success

**Comment by Rupesh87** [comment]
![](https://files.gitter.im/open-learning-exchange/QA/8p7d/15-16.png)
![15-2](https://user-images.githubusercontent.com/18145146/29710357-a138bbd4-89af-11e7-9fc5-07508374c74e.png)
![15-2](https://user-images.githubusercontent.com/18145146/29710390-c4a748ce-89af-11e7-8ea7-b032be9b6107.png)
![15-14](https://user-images.githubusercontent.com/18145146/29710391-c4a9b8a2-89af-11e7-90d8-687b68faf26b.png)
![15-15](https://user-images.githubusercontent.com/18145146/29710389-c4a6db6e-89af-11e7-9228-25798d45b688.png)

**Comment by Pr0chin** [comment]
- [ ] courses which was created on nation was not able to be done not saved on community
- [ ] reviewing on nation of courses was also not a success
