### ISSUE TITLE
Nation: Publication Overview: List of communities in `Send to` that had auto-accepted publication must be shown

### ISSUE THREAD

**Issue by Pr0chin** [open-learning-exchange/BeLL-Apps#999]
- [ ] I do not know if `None` happened because of the crash in auto publication but when fixed I would like also this to be checked

**Comment by Rupesh87** [comment]
![15-12](https://user-images.githubusercontent.com/18145146/29710322-7a6d6b62-89af-11e7-9ace-d72c8d46bb0f.png)
